import type { Skill } from "@/lib/types";

export const compareFractions: Skill = {
  id: "compare-fractions",
  title_ar: "مقارنة الكسور",
  domain: "arithmetic",
  hook_ar: "اضرب تبادلياً، أو وحّد المقام ذهنياً، لتعرف أيّهما أكبر",
  estimated_minutes: 6,
  icon: "≷",
  visual: { kind: "custom", component: "compare-fractions-lab" },
  intuition_ar: [
    "مقارنة كسرين تعني معرفة أيهما أكبر أو أصغر أو إن كانا متساويين.",
    "إن اتحد المقام أو البسط، المقارنة مباشرة بدون ضرب.",
    "وإلا: اضرب بسط الأول في مقام الثاني، وبسط الثاني في مقام الأول؛ الأكبر ناتجاً هو الكسر الأكبر.",
  ],
  trick_ar: {
    statement: "وحّد المقام إن سهل، وإلا اضرب تبادلياً بسرعة.",
    steps: [
      "نفس المقام: الأكبر بسطاً هو الأكبر",
      "نفس البسط: الأصغر مقاماً هو الأكبر",
      "وإلا: بسط أ × مقام ب قارنه بـ بسط ب × مقام أ؛ الأكبر ناتجاً هو الكسر الأكبر",
    ],
    time_target_sec: 20,
    example_ar:
      "قارن 2/3 و 3/5: 2×5 = 10، و 3×3 = 9. بما أن 10 أكبر، فـ 2/3 أكبر من 3/5.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "cf-01",
      prompt_ar:
        "في مسابقة حفظ، أتمّ أحمد 3/8 من القائمة وأتمّ خالد 5/8. أيهما قطع جزءاً أكبر؟",
      choices_ar: ["أحمد", "خالد", "متساويان", "لا يكفي للمقارنة"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى الأصغر بسطاً مع أن المقام واحد.",
        2: "اعتُبر الكسران متساويين رغم اختلاف البسط.",
        3: "المقام موحّد، فالمقارنة ممكنة مباشرة.",
      },
      solve_ar:
        "المقام واحد (8). نقارن البسطين: 5 أكبر من 3، فـ 5/8 أكبر من 3/8. إذن خالد قطع جزءاً أكبر.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-02",
      prompt_ar:
        "ملأ فريقان خزانين بنسبة 4/9 و 4/7 من سعتهما. أيّ النسبتين أكبر؟",
      choices_ar: ["4/9", "4/7", "متساويتان", "لا يمكن المقارنة"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى الأكبر مقاماً مع أن البسط واحد؛ الأكبر مقاماً أصغر قيمة.",
        2: "اعتُبر تساوي البسطين كافياً لتساوي الكسرين.",
        3: "البسط موحّد، فالمقارنة ممكنة مباشرة.",
      },
      solve_ar:
        "البسط واحد (4). الأصغر مقاماً هو الأكبر كسراً. 7 أصغر من 9، فـ 4/7 أكبر من 4/9.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-03",
      prompt_ar:
        "غطّى مسار أ 2/3 من الطريق، وغطّى مسار ب 3/5 منه. أيّ المسارين أطول نسبة؟",
      choices_ar: ["مسار أ", "مسار ب", "متساويان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى كبر البسط أو المقام دون ضرب تبادلي.",
        2: "اعتبر الناتجان متساويين دون حساب.",
        3: "الضرب التبادلي كافٍ للمقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 2×5 = 10، و 3×3 = 9. بما أن 10 أكبر من 9، فـ 2/3 أكبر. إذن مسار أ أطول نسبة.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-04",
      prompt_ar:
        "سجّل لاعب نسبة إصابة 3/4 في الشوط الأول، و 6/8 في الشوط الثاني. ما العلاقة بينهما؟",
      choices_ar: ["الأولى أكبر", "الثانية أكبر", "متساويتان", "لا يمكن"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر إلى صغر أرقام الكسر الأول دون تبسيط.",
        1: "نُظر إلى كبر أرقام الكسر الثاني دون تبسيط.",
        3: "يمكن التحقق بالتبسيط أو بالضرب التبادلي.",
      },
      solve_ar:
        "6/8 تُبسَّط بقسمة البسط والمقام على 2 فتصبح 3/4. أو بالضرب: 3×8 = 24، و 4×6 = 24. الناتجان متساويان، فالنسبتان متساويتان.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-05",
      prompt_ar:
        "امتلأ خزان الوقود إلى 5/6، وامتلأ خزان آخر إلى 4/5. أيّهما امتلأ أكثر؟",
      choices_ar: ["5/6", "4/5", "متساويان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى قرب 4/5 من الواحد دون ضرب تبادلي.",
        2: "اعتُبر الفرق صغيراً فهما متساويان.",
        3: "الضرب التبادلي يحسم المقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 5×5 = 25، و 6×4 = 24. بما أن 25 أكبر من 24، فـ 5/6 أكبر من 4/5.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-06",
      prompt_ar:
        "أنهى قارئ 1/2 من رواية، وأنهى آخر 3/7 منها. أيهما أنجز نسبة أكبر؟",
      choices_ar: ["1/2", "3/7", "متساويان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى كبر البسط 3 دون مقارنة صحيحة.",
        2: "قُرّب الكسران دون حساب.",
        3: "الضرب التبادلي كافٍ.",
      },
      solve_ar:
        "نضرب تبادلياً: 1×7 = 7، و 2×3 = 6. بما أن 7 أكبر من 6، فـ 1/2 أكبر من 3/7.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-07",
      prompt_ar:
        "غطّت لوحة 2/5 من الجدار، وغطّت أخرى 3/8 منه. أيّهما تغطي مساحة نسبية أكبر؟",
      choices_ar: ["2/5", "3/8", "متساويتان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى كبر البسط أو صغر المقام دون ضرب.",
        2: "اعتُبر الناتجان قريبين فهما متساويان.",
        3: "الضرب التبادلي يحسم الأمر.",
      },
      solve_ar:
        "نضرب تبادلياً: 2×8 = 16، و 5×3 = 15. بما أن 16 أكبر من 15، فـ 2/5 أكبر من 3/8.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-08",
      prompt_ar:
        "أُنجز 7/10 من مشروع، و 2/3 من مشروع آخر. أيّ النسبتين أكبر؟",
      choices_ar: ["7/10", "2/3", "متساويتان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى شهرة الثلثين دون حساب.",
        2: "قُرّب الفرق إلى الصفر خطأً.",
        3: "الضرب التبادلي كافٍ للمقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 7×3 = 21، و 10×2 = 20. بما أن 21 أكبر من 20، فـ 7/10 أكبر من 2/3.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-09",
      prompt_ar:
        "أيّ الكسرين أصغر: 3/4 أم 5/7؟",
      choices_ar: ["3/4", "5/7", "متساويان", "لا يكفي"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُكس اتجاه المقارنة بعد الضرب التبادلي.",
        2: "اعتُبر الناتجان متساويين.",
        3: "الضرب التبادلي يحدد الأصغر بوضوح.",
      },
      solve_ar:
        "نضرب تبادلياً: 3×7 = 21، و 4×5 = 20. بما أن 21 أكبر من 20، فـ 3/4 أكبر، إذن 5/7 هو الأصغر.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-10",
      prompt_ar:
        "قارن حصة 4/15 من عرض مع حصة 1/3 من العرض نفسه. أيّهما أكبر؟",
      choices_ar: ["4/15", "1/3", "متساويتان", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 4 دون توحيد المقام.",
        2: "اعتُبر الكسران متساويين خطأً.",
        3: "يمكن توحيد المقام ذهنياً: 1/3 = 5/15.",
      },
      solve_ar:
        "نوحّد المقام: 1/3 = 5/15. نقارن 4/15 و 5/15؛ البسط الأكبر هو 5، فـ 1/3 أكبر.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-11",
      prompt_ar:
        "قطع عدّاء 5/12 من المضمار، وقطع آخر 3/8 منه. أيهما قطع نسبة أكبر؟",
      choices_ar: ["5/12", "3/8", "متساويان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى صغر مقام 8 دون ضرب تبادلي.",
        2: "قُرّب الناتجان إلى التساوي.",
        3: "الضرب التبادلي يحسم المقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 5×8 = 40، و 12×3 = 36. بما أن 40 أكبر من 36، فـ 5/12 أكبر من 3/8.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-12",
      prompt_ar:
        "أيّ الكسرين أكبر: 7/9 أم 5/6؟",
      choices_ar: ["7/9", "5/6", "متساويان", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 7 دون ضرب تبادلي.",
        2: "اعتُبر الفرق مهملاً فهما متساويان.",
        3: "الضرب التبادلي كافٍ.",
      },
      solve_ar:
        "نضرب تبادلياً: 7×6 = 42، و 9×5 = 45. بما أن 45 أكبر من 42، فـ 5/6 أكبر من 7/9.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-13",
      prompt_ar:
        "ظهرت نسبة تحميل 5/8 ثم 10/16 في تقريرين. ما العلاقة بينهما؟",
      choices_ar: ["5/8 أكبر", "10/16 أكبر", "متساويتان", "لا يكفي"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر إلى صغر أرقام 5/8 دون تبسيط الآخر.",
        1: "نُظر إلى كبر أرقام 10/16 دون تبسيط.",
        3: "التبسيط أو الضرب التبادلي يثبت التساوي.",
      },
      solve_ar:
        "10/16 تُبسَّط بقسمة البسط والمقام على 2 فتصبح 5/8. أو: 5×16 = 80، و 8×10 = 80. فالنسبتان متساويتان.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-14",
      prompt_ar:
        "قارن 8/15 و 3/5 بعد توحيد المقام ذهنياً. أيهما أكبر؟",
      choices_ar: ["8/15", "3/5", "متساويان", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 8 دون تحويل 3/5.",
        2: "اعتُبر الكسران متساويين خطأً.",
        3: "3/5 = 9/15، فالمقارنة مباشرة.",
      },
      solve_ar:
        "3/5 = 9/15. نقارن 8/15 و 9/15؛ البسط الأكبر 9، فـ 3/5 أكبر من 8/15.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-15",
      prompt_ar:
        "في استطلاع، أيّد 4/7 من العيّنة الخيار الأول، و 5/9 الخيار الثاني. أيّ التأييدين أكبر؟",
      choices_ar: ["4/7", "5/9", "متساويان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى كبر البسط 5 دون ضرب تبادلي.",
        2: "قُرّب الناتجان إلى التساوي.",
        3: "الضرب التبادلي يحسم المقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 4×9 = 36، و 7×5 = 35. بما أن 36 أكبر من 35، فـ 4/7 أكبر من 5/9.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-16",
      prompt_ar:
        "أيّ الكسرين أصغر: 11/20 أم 5/9؟",
      choices_ar: ["11/20", "5/9", "متساويان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "عُكس اتجاه المقارنة بعد الضرب.",
        2: "اعتُبر الناتجان متساويين رغم فرق واحد.",
        3: "الضرب التبادلي يحدد الأصغر.",
      },
      solve_ar:
        "نضرب تبادلياً: 11×9 = 99، و 20×5 = 100. بما أن 99 أصغر من 100، فـ 11/20 أصغر من 5/9.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-17",
      prompt_ar:
        "قطع مسار قصير 2/9 من الطريق الكلي، وقطع مسار آخر 1/4 منه. أيّ المسارين أطول نسبة؟",
      choices_ar: ["2/9", "1/4", "متساويان", "لا يكفي"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 2 دون ضرب تبادلي.",
        2: "قُرّب الكسران دون حساب.",
        3: "الضرب التبادلي كافٍ.",
      },
      solve_ar:
        "نضرب تبادلياً: 2×4 = 8، و 9×1 = 9. بما أن 9 أكبر من 8، فـ 1/4 أكبر من 2/9.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-18",
      prompt_ar:
        "أيّ الكسرين أكبر: 13/18 أم 5/7؟",
      choices_ar: ["13/18", "5/7", "متساويان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى قرب 5/7 من الواحد دون ضرب.",
        2: "اعتُبر الفرق مهملاً فهما متساويان.",
        3: "الضرب التبادلي يحسم الأمر.",
      },
      solve_ar:
        "نضرب تبادلياً: 13×7 = 91، و 18×5 = 90. بما أن 91 أكبر من 90، فـ 13/18 أكبر من 5/7.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "cf-f01",
      prompt_ar:
        "شغلت كاميرا 3/5 من إطار العرض، وشغلت أخرى 7/12 منه. أيّهما تشغل نسبة أكبر؟",
      choices_ar: ["3/5", "7/12", "متساويتان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى كبر البسط 7 دون ضرب تبادلي.",
        2: "قُرّب الناتجان إلى التساوي.",
        3: "الضرب التبادلي كافٍ للمقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 3×12 = 36، و 5×7 = 35. بما أن 36 أكبر من 35، فـ 3/5 أكبر من 7/12.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f02",
      prompt_ar:
        "أيّ الكسرين أكبر: 4/11 أم 3/8؟",
      choices_ar: ["4/11", "3/8", "متساويان", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 4 دون ضرب تبادلي.",
        2: "اعتُبر الناتجان متساويين رغم فرق واحد.",
        3: "الضرب التبادلي يحدد الأكبر.",
      },
      solve_ar:
        "نضرب تبادلياً: 4×8 = 32، و 11×3 = 33. بما أن 33 أكبر من 32، فـ 3/8 أكبر من 4/11.",
      trick_ref: "compare-fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f03",
      prompt_ar:
        "ظهرت نسبتان 9/12 و 3/4 في تقرير جودة. ما العلاقة بينهما؟",
      choices_ar: ["9/12 أكبر", "3/4 أكبر", "متساويتان", "لا يكفي"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر إلى كبر أرقام 9/12 دون تبسيط.",
        1: "نُظر إلى صغر أرقام 3/4 دون تبسيط الآخر.",
        3: "التبسيط يثبت التساوي فوراً.",
      },
      solve_ar:
        "9/12 تُبسَّط بقسمة البسط والمقام على 3 فتصبح 3/4. أو: 9×4 = 36، و 12×3 = 36. فالنسبتان متساويتان.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f04",
      prompt_ar:
        "حصل فريقان على 2/13 و 5/13 من نقاط الدوري. أيّهما حصته أكبر؟",
      choices_ar: ["2/13", "5/13", "متساويتان", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى الأصغر بسطاً مع أن المقام واحد.",
        2: "اعتُبر المقام الموحّد يعني تساوي الحصتين.",
        3: "المقام موحّد، فالمقارنة مباشرة.",
      },
      solve_ar:
        "المقام واحد (13). نقارن البسطين: 5 أكبر من 2، فـ 5/13 أكبر من 2/13.",
      trick_ref: "compare-fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f05",
      prompt_ar:
        "أيّ الكسرين أكبر: 7/8 أم 8/9؟",
      choices_ar: ["7/8", "8/9", "متساويان", "لا يكفي"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى قرب 7/8 من الواحد دون ضرب.",
        2: "اعتُبر كلاهما ناقصاً جزءاً واحداً فهما متساويان.",
        3: "الضرب التبادلي يظهر الفرق.",
      },
      solve_ar:
        "نضرب تبادلياً: 7×9 = 63، و 8×8 = 64. بما أن 64 أكبر من 63، فـ 8/9 أكبر من 7/8.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f06",
      prompt_ar:
        "أيّ الكسرين أصغر: 5/14 أم 3/8؟",
      choices_ar: ["5/14", "3/8", "متساويان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "عُكس اتجاه المقارنة بعد الضرب.",
        2: "اعتُبر الناتجان متساويين.",
        3: "الضرب التبادلي يحدد الأصغر.",
      },
      solve_ar:
        "نضرب تبادلياً: 5×8 = 40، و 14×3 = 42. بما أن 40 أصغر من 42، فـ 5/14 أصغر من 3/8.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "cf-f07",
      prompt_ar:
        "قارن 6/11 و 5/9 في ترتيب نتائج اختبار. أيّهما أكبر؟",
      choices_ar: ["6/11", "5/9", "متساويان", "لا يكفي"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى كبر البسط 6 دون ضرب تبادلي.",
        2: "اعتُبر الفرق واحداً مهملاً فهما متساويان.",
        3: "الضرب التبادلي يحسم المقارنة.",
      },
      solve_ar:
        "نضرب تبادلياً: 6×9 = 54، و 11×5 = 55. بما أن 55 أكبر من 54، فـ 5/9 أكبر من 6/11.",
      trick_ref: "compare-fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
