import type { Skill } from "@/lib/types";

export const exponents: Skill = {
  id: "exponents",
  title_ar: "الأسس والقوى",
  domain: "arithmetic",
  hook_ar: "نفس القاعدة؟ اجمع أو اطرح أو اضرب الأسّين ثم بسّط",
  estimated_minutes: 6,
  icon: "ⁿ",
  visual: { kind: "custom", component: "exponents-lab" },
  intuition_ar: [
    "عند ضرب قوى لها نفس القاعدة: اجمع الأسّين.",
    "عند قسمة قوى لها نفس القاعدة: اطرح الأسّين.",
    "عند رفع قوة إلى قوة: اضرب الأسّين. وأي عدد غير صفر أسّه صفر يساوي 1.",
  ],
  trick_ar: {
    statement: "ثبّت القاعدة، وحرّك الأسّ فقط حسب العملية.",
    steps: [
      "ضرب: قاعدة أس م × نفس القاعدة أس ن = القاعدة أس (م+ن)",
      "قسمة: قاعدة أس م ÷ نفس القاعدة أس ن = القاعدة أس (م−ن)",
      "أس فوق أس: (قاعدة أس م) أس ن = القاعدة أس (م×ن)، وأي قاعدة أس صفر = 1",
    ],
    time_target_sec: 20,
    example_ar:
      "2 أس 3 × 2 أس 4 = 2 أس 7. و (3 أس 2) أس 3 = 3 أس 6.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ex-01",
      prompt_ar:
        "في تجربة برمجية كُتبت العملية 2^3 × 2^4. ما الناتج مبسّطاً؟",
      choices_ar: ["2^6", "2^7", "2^12", "2^1"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح واحد من مجموع الأسّين.",
        2: "ضُرب الأسّان بدل جمعهما.",
        3: "طُرح الأسّان بدل جمعهما.",
      },
      solve_ar:
        "نفس القاعدة في الضرب: نجمع الأسّين. 3 + 4 = 7، فالناتج 2^7.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-02",
      prompt_ar:
        "خزّن جهاز بيانات بحجم 5^6 وحدة ثم نُقل منها 5^2 وحدة. ما ناتج 5^6 ÷ 5^2 مبسّطاً؟",
      choices_ar: ["5^3", "5^4", "5^8", "5^12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح عدد خاطئ من الأسّ.",
        2: "جُمع الأسّان بدل طرحهما.",
        3: "ضُرب الأسّان.",
      },
      solve_ar:
        "نفس القاعدة في القسمة: نطرح الأسّين. 6 − 2 = 4، فالناتج 5^4.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-03",
      prompt_ar:
        "في نموذج نمو سكاني كُتب (3^2)^3. ما الشكل المبسط؟",
      choices_ar: ["3^5", "3^6", "3^9", "3^8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الأسّان بدل ضربهما.",
        2: "رُفع الأس الخارجي كأنه أسّ للأسّ الداخلي فقط.",
        3: "جُمع أو ضُرب بطريقة خاطئة.",
      },
      solve_ar:
        "أس فوق أس: نضرب الأسّين. 2 × 3 = 6، فالناتج 3^6.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-04",
      prompt_ar:
        "ظهر في جدول نتائج الرمز 7^0. ما قيمته؟",
      choices_ar: ["0", "1", "7", "−7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبر الأس الصفري صفراً.",
        2: "أُبقيت القاعدة كما هي.",
        3: "أُدخل إشارة سالبة بلا سبب.",
      },
      solve_ar:
        "أي عدد غير صفر أسّه صفر يساوي 1. إذن 7^0 = 1.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-05",
      prompt_ar:
        "كم خانة ثنائية تلزم لتمثيل 2^5 احتمالاً في لعبة رقمية؟",
      choices_ar: ["16", "25", "32", "64"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 2^4 فقط.",
        1: "ضُربت القاعدة في الأسّ.",
        3: "حُسبت 2^6.",
      },
      solve_ar:
        "2^5 = 2 × 2 × 2 × 2 × 2 = 32.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-06",
      prompt_ar:
        "ضاعف مصنع إنتاجه وفق 4^3 × 4^2. ما الناتج مبسّطاً؟",
      choices_ar: ["4^5", "4^6", "16^5", "4^1"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب الأسّان بدل جمعهما.",
        2: "ضُربت القاعدتان معاً ثم أُبقي أسّ خاطئ.",
        3: "طُرح الأسّان بدل جمعهما.",
      },
      solve_ar:
        "نفس القاعدة: نجمع الأسّين. 3 + 2 = 5، فالناتج 4^5.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-07",
      prompt_ar:
        "قُسمت سعة خادم 10^5 ملفاً إلى مجموعات بحجم 10^3. ما ناتج 10^5 ÷ 10^3؟",
      choices_ar: ["10", "100", "1000", "10^8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح الأسّان ثم حُسبت قيمة أصغر من المطلوب.",
        2: "حُسبت 10^3 بدل 10^2.",
        3: "جُمع الأسّان بدل طرحهما.",
      },
      solve_ar:
        "نطرح الأسّين: 5 − 3 = 2، فالناتج 10^2 = 100.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-08",
      prompt_ar:
        "في معادلة تشفير مبسطة ظهرت (2^3)^2. ما الشكل المبسط؟",
      choices_ar: ["2^5", "2^6", "2^9", "2^8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الأسّان.",
        2: "رُفع 3 إلى القوة 2 ثم جُمع أو ضُرب بطريقة خاطئة.",
        3: "ضُربت القاعدة في الأسّ الخارجي ثم أُسيء التبسيط.",
      },
      solve_ar:
        "أس فوق أس: 3 × 2 = 6، فالناتج 2^6.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-09",
      prompt_ar:
        "ما قيمة 3^(−1) في تبسيط خفيف لأسّ سالب؟",
      choices_ar: ["−3", "1/3", "3", "0"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "وُضعت إشارة سالبة على القاعدة.",
        2: "أُهمل السالب في الأسّ.",
        3: "اعتُبر الناتج صفراً.",
      },
      solve_ar:
        "الأس السالب يعني مقلوب القوة الموجبة: 3^(−1) = 1 / 3^1 = 1/3.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-10",
      prompt_ar:
        "في ميزان مخزون تساوت الكميتان 6^4 ÷ 6^4. ما الناتج؟",
      choices_ar: ["0", "1", "6", "36"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبرت القسمة صفراً.",
        2: "أُبقيت القاعدة.",
        3: "حُسبت 6^2 خطأ.",
      },
      solve_ar:
        "نطرح الأسّين: 4 − 4 = 0، و 6^0 = 1.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-11",
      prompt_ar:
        "ضاعفت خوارزمية إشارة ثلاث مرات: 2^3 × 2^2 × 2^1. ما الناتج مبسّطاً؟",
      choices_ar: ["2^5", "2^6", "2^7", "2^8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص أسّ واحد من المجموع.",
        2: "أُضيف أسّ زائد.",
        3: "ضُرب عدد الأسس بدل جمعها.",
      },
      solve_ar:
        "نجمع الأسّين الثلاثة: 3 + 2 + 1 = 6، فالناتج 2^6.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-12",
      prompt_ar:
        "كم مربعاً صغيراً في شبكة 5 × 5 إن عُبّر عنها بـ 5^2؟",
      choices_ar: ["10", "20", "25", "50"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمعت القاعدة مع الأسّ.",
        1: "ضُربت القاعدة في 4.",
        3: "ضُربت القاعدة في 10.",
      },
      solve_ar: "5^2 = 5 × 5 = 25.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-13",
      prompt_ar:
        "في تعبير علمي كُتب (10^2)^3. ما الشكل المبسط؟",
      choices_ar: ["10^5", "10^6", "10^8", "10^9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الأسّان بدل ضربهما.",
        2: "رُفع الأس الداخلي إلى قوة ثم أُسيء الجمع.",
        3: "ضُربت أعداد خاطئة: مثل 3^2.",
      },
      solve_ar:
        "أس فوق أس: 2 × 3 = 6، فالناتج 10^6.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-14",
      prompt_ar:
        "خُفّضت طاقة إشارة من 8^5 إلى قسمة على 8^2. ما ناتج 8^5 ÷ 8^2 مبسّطاً؟",
      choices_ar: ["8^3", "8^7", "8^10", "1"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع الأسّان.",
        2: "ضُرب الأسّان.",
        3: "اعتُبر الناتج واحداً بلا طرح صحيح.",
      },
      solve_ar:
        "نطرح الأسّين: 5 − 2 = 3، فالناتج 8^3.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-15",
      prompt_ar:
        "ما قيمة 3^4 في عدّ ترتيبات سريعة؟",
      choices_ar: ["12", "27", "64", "81"],
      correct_index: 3,
      trap_explanations_ar: {
        0: "ضُربت القاعدة في الأسّ فقط.",
        1: "حُسبت 3^3.",
        2: "حُسبت 4^3 أو 8^2 خطأ.",
      },
      solve_ar: "3^4 = 3 × 3 × 3 × 3 = 81.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-16",
      prompt_ar:
        "قلّص نظام تخزين الملفات من 2^7 إلى قسمة على 2^3. ما قيمة 2^7 ÷ 2^3؟",
      choices_ar: ["8", "16", "2^10", "4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت 2^3 فقط.",
        2: "جُمع الأسّان.",
        3: "حُسبت 2^2.",
      },
      solve_ar:
        "نطرح الأسّين: 7 − 3 = 4، و 2^4 = 16.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-17",
      prompt_ar:
        "في مساحة مربعة متداخلة ظهرت (4^2)^2. ما الشكل المبسط؟",
      choices_ar: ["4^3", "4^4", "4^8", "4^2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع شيء ناقص إلى الأسّ.",
        2: "رُفع 2 إلى 2 فصار 4 ثم ضُرب خطأ ليُظن الناتج 4^8.",
        3: "أُبقي الأسّ الداخلي فقط.",
      },
      solve_ar:
        "أس فوق أس: 2 × 2 = 4، فالناتج 4^4.",
      trick_ref: "exponents",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-18",
      prompt_ar:
        "بدأ عداد من 9^0 ثم ضُرب في 9^3. ما ناتج 9^0 × 9^3 مبسّطاً؟",
      choices_ar: ["0", "1", "9^3", "9^4"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اعتُبر 9^0 صفراً فصار الناتج صفراً.",
        1: "وُقف عند 9^0 = 1 دون إكمال الضرب.",
        3: "جُمع الأسّان مع نسيان أن أحدهما صفر فيتبادر 9^3 فقط أو أُضيف واحد خطأ.",
      },
      solve_ar:
        "9^0 = 1، و 1 × 9^3 = 9^3. أو بجمع الأسّين: 0 + 3 = 3.",
      trick_ref: "exponents",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "ex-f01",
      prompt_ar:
        "في محاكاة شبكة ضُربت السعات 2^4 × 2^5. ما الناتج مبسّطاً؟",
      choices_ar: ["2^9", "2^20", "4^9", "2^1"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب الأسّان.",
        2: "ضُربت القاعدتان.",
        3: "طُرح الأسّان.",
      },
      solve_ar:
        "نجمع الأسّين: 4 + 5 = 9، فالناتج 2^9.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f02",
      prompt_ar:
        "خُفّض مؤشر من 7^8 بالقسمة على 7^5. ما ناتج 7^8 ÷ 7^5 مبسّطاً؟",
      choices_ar: ["7^3", "7^13", "7^40", "1"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع الأسّان.",
        2: "ضُرب الأسّان.",
        3: "اعتُبر الناتج واحداً.",
      },
      solve_ar:
        "نطرح الأسّين: 8 − 5 = 3، فالناتج 7^3.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f03",
      prompt_ar:
        "في نموذج تضاعف كُتب (5^3)^2. ما الشكل المبسط؟",
      choices_ar: ["5^5", "5^6", "5^9", "15^2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الأسّان.",
        2: "ضُرب 3 في 3 خطأ.",
        3: "جُمعت القاعدة مع الأسّ ثم رُفعت.",
      },
      solve_ar:
        "أس فوق أس: 3 × 2 = 6، فالناتج 5^6.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f04",
      prompt_ar:
        "ما قيمة 2^(−2) في تبسيط خفيف؟",
      choices_ar: ["−4", "−2", "1/4", "4"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "وُضعت إشارة سالبة على 2^2.",
        1: "أُبقي الأسّ بإشارة فقط.",
        3: "حُسبت 2^2 دون المقلوب.",
      },
      solve_ar:
        "2^(−2) = 1 / 2^2 = 1/4.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f05",
      prompt_ar:
        "ما قيمة 3^5؟",
      choices_ar: ["81", "125", "243", "729"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 3^4.",
        1: "حُسبت 5^3.",
        3: "حُسبت 3^6.",
      },
      solve_ar:
        "3^5 = 3 × 3 × 3 × 3 × 3 = 243.",
      trick_ref: "exponents",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f06",
      prompt_ar:
        "قُسمت سعة 4^6 على 4^3 في نظام تخزين. ما الناتج مبسّطاً؟",
      choices_ar: ["4^2", "4^3", "4^9", "4^18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح عدد أكبر من اللازم.",
        2: "جُمع الأسّان.",
        3: "ضُرب الأسّان.",
      },
      solve_ar:
        "نطرح الأسّين: 6 − 3 = 3، فالناتج 4^3.",
      trick_ref: "exponents",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ex-f07",
      prompt_ar:
        "ظهر في تقرير القياس الرمز 10^0. ما قيمته؟",
      choices_ar: ["0", "1", "10", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبر الأس الصفري صفراً.",
        2: "أُبقيت القاعدة.",
        3: "حُسبت 10^2 خطأ.",
      },
      solve_ar: "أي عدد غير صفر أسّه صفر يساوي 1. إذن 10^0 = 1.",
      trick_ref: "exponents",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
