import type { Skill } from "@/lib/types";

export const fractions: Skill = {
  id: "fractions",
  title_ar: "الكسور في المسائل",
  domain: "arithmetic",
  hook_ar: "اقسم على المقام، ثم اضرب في البسط",
  estimated_minutes: 6,
  icon: "½",
  visual: { kind: "custom", component: "fractions-lab" },
  intuition_ar: [
    "الكسر بسط/مقام من كمية يعني: نقسم الكمية على المقام، ثم نضرب الناتج في البسط.",
    "لإيجاد الباقي: نحسب الجزء المأخوذ، ثم نطرحه من الكمية كلها.",
    "في سلسلة الكسور، يُحسب الكسر الثاني من الباقي بعد الخطوة الأولى.",
  ],
  trick_ar: {
    statement: "المقام يقسم، والبسط يضرب؛ وفي السلسلة اكتب الباقي بعد كل خطوة.",
    steps: [
      "احسب الكسر: الكمية تقسيم المقام، ثم ضرب البسط.",
      "إن كان المطلوب الباقي، اطرح الجزء من الكمية.",
      "إن وُجد كسر ثانٍ، طبّقه على الباقي لا على الكمية الأصلية.",
    ],
    time_target_sec: 20,
    example_ar:
      "أُخذ 1/3 من 120 ثم 1/4 من الباقي: المأخوذ أولاً 40، والباقي 80، ثم المأخوذ ثانياً 20، فيبقى 60.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 42,
    slow_sec: 56,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "fr-01",
      prompt_ar: "في رف 80 كتاباً، استُعير 3/4 منها. كم كتاباً استُعير؟",
      choices_ar: ["20", "40", "60", "75"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا ربع الكتب، لا ثلاثة أرباعها.",
        1: "هذا نصف الكتب فقط.",
        3: "طُرح عدد من غير تطبيق الكسر.",
      },
      solve_ar:
        "نقسم 80 على المقام 4 فنحصل على 20. ثم نضرب 20 في البسط 3 فنحصل على 60 كتاباً.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-02",
      prompt_ar: "خزان فيه 150 لتراً، استُهلك 2/5 مائه. كم لتراً بقي؟",
      choices_ar: ["60", "90", "100", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا المقدار المستهلك، والمطلوب الباقي.",
        2: "حُسب الثلث تقريباً بدل خمسي الكمية.",
        3: "طُرح خُمس واحد فقط.",
      },
      solve_ar:
        "خُمس 150 = 150 تقسيم 5 = 30. المستهلك = 30 ضرب 2 = 60. الباقي = 150 ناقص 60 = 90 لتراً.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-03",
      prompt_ar:
        "مع سارة 120 بطاقة. أعطت 1/3 منها، ثم أعطت 1/4 من الباقي. كم بطاقة بقيت؟",
      choices_ar: ["50", "60", "70", "80"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح جزء زائد لا ينتج من الخطوتين.",
        2: "حُسب الجزء الثاني من كمية غير صحيحة.",
        3: "هذا الباقي بعد الخطوة الأولى فقط.",
      },
      solve_ar:
        "أولاً: 1/3 من 120 = 40، فيبقى 80. ثانياً: 1/4 من الباقي 80 = 20. إذن الباقي النهائي = 80 ناقص 20 = 60 بطاقة.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-04",
      prompt_ar:
        "في معرض 120 لوحة. خُصص 1/4 منها للمدخل و1/3 منها للقاعة، وكل الكسرين من مجموع اللوحات. كم لوحة خُصصت للمكانين؟",
      choices_ar: ["60", "70", "80", "90"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب نصف المجموع فقط.",
        2: "جُمع ربع وثلث بطريقة غير صحيحة.",
        3: "أُخذت ثلاثة أرباع المجموع.",
      },
      solve_ar:
        "1/4 من 120 = 30، و1/3 من 120 = 40. الكسران من المجموع نفسه، لذا المخصص = 30 زائد 40 = 70 لوحة.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-05",
      prompt_ar: "قطع عدّاء 2/3 مسار طوله 90 متراً. كم متراً قطع؟",
      choices_ar: ["30", "45", "60", "75"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا ثلث المسار فقط.",
        1: "هذا نصف المسار.",
        3: "أُخذ جزء أكبر من الثلثين.",
      },
      solve_ar:
        "نقسم 90 على 3 فنحصل على 30. ثم نضرب 30 في 2 فنحصل على 60 متراً.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-06",
      prompt_ar: "مخزن فيه 160 صندوقاً. شُحن 3/8 منها. كم صندوقاً بقي؟",
      choices_ar: ["60", "80", "100", "120"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا عدد الصناديق المشحونة، لا الباقية.",
        1: "طُرح نصف المخزون.",
        3: "طُرح ربع المخزون فقط.",
      },
      solve_ar:
        "ثُمن 160 = 160 تقسيم 8 = 20. المشحون = 20 ضرب 3 = 60. الباقي = 160 ناقص 60 = 100 صندوق.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-07",
      prompt_ar:
        "في مستودع 180 كيساً. نُقل 1/2 الأكياس، ثم نُقل 1/3 من الباقي. كم كيساً بقي؟",
      choices_ar: ["30", "60", "90", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا المنقول في الخطوة الثانية، لا الباقي النهائي.",
        2: "هذا الباقي بعد الخطوة الأولى فقط.",
        3: "جُمعت نتائج لا تمثل الباقي.",
      },
      solve_ar:
        "نصف 180 = 90، فيبقى 90. ثلث الباقي 90 = 30، فيبقى 90 ناقص 30 = 60 كيساً.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-08",
      prompt_ar:
        "في مزرعة 200 شجرة. 2/5 الأشجار ليمون و1/4 الأشجار برتقال. كم شجرة من النوعين معاً؟",
      choices_ar: ["100", "120", "130", "150"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا نصف الأشجار فقط.",
        1: "حُسب جزء من أحد الكسرين بصورة ناقصة.",
        3: "جُمع الكسران كأنهما ثلاثة أرباع.",
      },
      solve_ar:
        "2/5 من 200 = 200 تقسيم 5 ضرب 2 = 80. و1/4 من 200 = 50. المجموع = 80 زائد 50 = 130 شجرة.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-09",
      prompt_ar: "أنجز فريق 5/6 من 72 مهمة. كم مهمة أنجز؟",
      choices_ar: ["12", "48", "60", "66"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا سدس المهام فقط.",
        1: "هذا ثلثا المهام.",
        3: "طُرح المقام من العدد بدلاً من تطبيق الكسر.",
      },
      solve_ar:
        "نقسم 72 على 6 فنحصل على 12. ثم نضرب 12 في 5 فنحصل على 60 مهمة.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-10",
      prompt_ar: "قطيع فيه 210 رؤوس. خرج 1/7 القطيع من الحظيرة. كم رأساً بقي؟",
      choices_ar: ["30", "150", "180", "200"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا الخارج من الحظيرة، لا الباقي.",
        1: "طُرح سُبعان بدلاً من سُبع واحد.",
        3: "طُرح 10 من غير حساب الكسر.",
      },
      solve_ar:
        "سُبع 210 = 210 تقسيم 7 = 30. الباقي = 210 ناقص 30 = 180 رأساً.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-11",
      prompt_ar:
        "لدى مصنع 144 قطعة. فُحص 1/4 منها صباحاً، ثم فُحص 2/3 من الباقي مساءً. كم قطعة بقيت بلا فحص؟",
      choices_ar: ["24", "36", "48", "72"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب جزء أصغر من الباقي النهائي.",
        2: "حُسب ثلث الكمية الأصلية لا ثلث الباقي.",
        3: "لم تُطبق الخطوة الثانية على الباقي.",
      },
      solve_ar:
        "ربع 144 = 36، فيبقى 108. ثلثا الباقي 108 = 72، فيبقى 108 ناقص 72 = 36 قطعة.",
      trick_ref: "fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-12",
      prompt_ar:
        "من 250 مقعداً، حُجز 3/10 للضيوف و1/5 للمنظمين، وكلاهما من مجموع المقاعد. كم مقعداً حُجز؟",
      choices_ar: ["100", "125", "150", "175"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ خُمسا المجموع بدلاً من نصفه.",
        2: "جُمع الكسران بصورة أكبر من الصحيح.",
        3: "أُخذت سبعة أعشار المجموع.",
      },
      solve_ar:
        "3/10 من 250 = 75، و1/5 من 250 = 50. المجموع المحجوز = 75 زائد 50 = 125 مقعداً.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-13",
      prompt_ar: "قرأت طالبة 7/8 كتاب من 96 صفحة. كم صفحة قرأت؟",
      choices_ar: ["72", "80", "84", "88"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا ثلاثة أرباع الكتاب.",
        1: "حُذف 16 صفحة بدلاً من 12.",
        3: "طُرح المقام 8 من عدد الصفحات.",
      },
      solve_ar:
        "نقسم 96 على 8 فنحصل على 12. ثم نضرب 12 في 7 فنحصل على 84 صفحة.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-14",
      prompt_ar: "ساحة فيها 180 مقعداً، امتلأ 5/9 منها. كم مقعداً بقي فارغاً؟",
      choices_ar: ["60", "80", "90", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا ثلث المقاعد فقط.",
        2: "هذا نصف المقاعد.",
        3: "هذا عدد المقاعد الممتلئة، لا الفارغة.",
      },
      solve_ar:
        "تُسع 180 = 20، والممتلئ = 20 ضرب 5 = 100. الفارغ = 180 ناقص 100 = 80 مقعداً.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-15",
      prompt_ar:
        "مع متجر 150 جهازاً. باع 2/5 منها صباحاً، ثم باع 1/3 من الباقي مساءً. كم جهازاً بقي؟",
      choices_ar: ["30", "50", "60", "90"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا المباع مساءً، لا الباقي.",
        1: "حُسب ثلث الكمية الأصلية ثم طُرح.",
        3: "هذا الباقي بعد البيع الصباحي فقط.",
      },
      solve_ar:
        "2/5 من 150 = 60، فيبقى 90. ثلث الباقي 90 = 30، فيبقى 90 ناقص 30 = 60 جهازاً.",
      trick_ref: "fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-16",
      prompt_ar:
        "في مدرسة 84 طالباً في نشاطين: 1/2 الطلاب في الروبوت و1/6 الطلاب في الخط. كم طالباً في النشاطين؟",
      choices_ar: ["42", "49", "56", "70"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسب النصف فقط ونُسي السدس.",
        1: "جُمع جزء غير صحيح إلى النصف.",
        3: "اعتُبر المجموع خمسة أسداس.",
      },
      solve_ar:
        "نصف 84 = 42، وسُدس 84 = 14. العدد في النشاطين = 42 زائد 14 = 56 طالباً.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-17",
      prompt_ar: "شُحن 3/5 من 240 طرداً. كم طرداً شُحن؟",
      choices_ar: ["96", "120", "144", "160"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا خُمسا الطرود، لا ثلاثة أخماسها.",
        1: "هذا نصف الطرود.",
        3: "حُسب ثلثا الطرود.",
      },
      solve_ar:
        "نقسم 240 على 5 فنحصل على 48. ثم نضرب 48 في 3 فنحصل على 144 طرداً.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-18",
      prompt_ar:
        "في حديقة 216 شتلة. زُرع 1/3 منها صباحاً، ثم زُرع 1/4 من الباقي ظهراً. كم شتلة زُرعت ظهراً؟",
      choices_ar: ["36", "48", "54", "72"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب جزء من كمية لا تساوي الباقي.",
        2: "أُخذ ربع الكمية الأصلية.",
        3: "هذا المزروع صباحاً، لا ظهراً.",
      },
      solve_ar:
        "ثلث 216 = 72، فيبقى 144. المزروع ظهراً = ربع الباقي 144 = 144 تقسيم 4 = 36 شتلة.",
      trick_ref: "fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "fr-f01",
      prompt_ar: "وعاء فيه 200 كرة. أُخرج 3/4 منها. كم كرة بقيت؟",
      choices_ar: ["25", "50", "100", "150"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا ثُمن الكمية، لا الباقي.",
        2: "طُرح نصف الكرات فقط.",
        3: "هذا العدد المأخوذ، لا الباقي.",
      },
      solve_ar:
        "3/4 من 200 = 200 تقسيم 4 ضرب 3 = 150. الباقي = 200 ناقص 150 = 50 كرة.",
      trick_ref: "fractions",
      difficulty: "easy",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f02",
      prompt_ar:
        "لدى مركز 240 ملفاً. أُرشف 1/3 منها، ثم أُرشف 1/2 الباقي. كم ملفاً بقي؟",
      choices_ar: ["40", "80", "120", "160"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح جزء أكبر من المطلوب.",
        2: "حُسب نصف الكمية الأصلية كباقٍ.",
        3: "هذا الباقي بعد الخطوة الأولى فقط.",
      },
      solve_ar:
        "ثلث 240 = 80، فيبقى 160. نصف الباقي 160 = 80، فيبقى 160 ناقص 80 = 80 ملفاً.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f03",
      prompt_ar:
        "من 140 تذكرة، خُصص 2/7 للطلاب و3/7 للعائلات. كم تذكرة خُصصت للفئتين؟",
      choices_ar: ["60", "80", "100", "120"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا ثلاثة أسباع المجموع فقط.",
        1: "هذا أربعة أسباع المجموع.",
        3: "جُمع جزء زائد إلى الكسرين.",
      },
      solve_ar:
        "سُبع 140 = 20. للطلاب 20 ضرب 2 = 40، وللعائلات 20 ضرب 3 = 60. المجموع = 40 زائد 60 = 100 تذكرة.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f04",
      prompt_ar: "استخدم فني 4/9 من 225 متراً من الأسلاك. كم متراً استخدم؟",
      choices_ar: ["75", "90", "100", "125"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا ثلث الكمية.",
        1: "حُسب جزء أقل من أربعة أتساع.",
        3: "هذا خمسة أتساع الكمية.",
      },
      solve_ar:
        "نقسم 225 على 9 فنحصل على 25. ثم نضرب 25 في 4 فنحصل على 100 متر.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f05",
      prompt_ar: "في مخزن 320 عبوة. وُزع 7/10 منها. كم عبوة بقيت؟",
      choices_ar: ["64", "96", "224", "240"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا خُمس الكمية فقط.",
        2: "هذا العدد الموزع، لا الباقي.",
        3: "طُرح ربع الكمية فقط.",
      },
      solve_ar:
        "عُشر 320 = 32، والموزع = 32 ضرب 7 = 224. الباقي = 320 ناقص 224 = 96 عبوة.",
      trick_ref: "fractions",
      difficulty: "mid",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f06",
      prompt_ar:
        "في ورشة 200 لوح. استُخدم 1/5 منها أولاً، ثم استُخدم 3/8 من الباقي. كم لوحاً بقي؟",
      choices_ar: ["60", "80", "100", "120"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا المستخدم في الخطوة الثانية، لا الباقي.",
        1: "حُسب الجزء الثاني من الأصل ثم طُرح.",
        3: "لم تُطرح الكمية الثانية كاملة.",
      },
      solve_ar:
        "خُمس 200 = 40، فيبقى 160. ثلاثة أثمان 160 = 160 تقسيم 8 ضرب 3 = 60. الباقي النهائي = 160 ناقص 60 = 100 لوح.",
      trick_ref: "fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "fr-f07",
      prompt_ar:
        "من 160 مشاركاً، اختار 3/8 مسار العلوم واختار 1/4 مسار التقنية. كم مشاركاً في المسارين؟",
      choices_ar: ["80", "90", "100", "120"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا نصف المشاركين فقط.",
        1: "جُمع جزء ناقص إلى الناتج.",
        3: "اعتُبر الكسران ثلاثة أرباع.",
      },
      solve_ar:
        "3/8 من 160 = 160 تقسيم 8 ضرب 3 = 60. و1/4 من 160 = 40. المجموع = 60 زائد 40 = 100 مشارك.",
      trick_ref: "fractions",
      difficulty: "hard",
      sub_pattern: "fraction",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
