import type { Skill } from "@/lib/types";

export const gcdLcm: Skill = {
  id: "gcd-lcm",
  title_ar: "القواسم والمضاعفات",
  domain: "arithmetic",
  hook_ar: "ميّز: أكبر قاسم للتقسيم المتساوي، وأصغر مضاعف للالتقاء معاً",
  estimated_minutes: 7,
  icon: "⋮",
  visual: { kind: "custom", component: "gcd-lcm-lab" },
  intuition_ar: [
    "أكبر قاسم مشترك: أكبر عدد يقسم العددين معاً بلا باقٍ.",
    "أصغر مضاعف مشترك: أصغر عدد موجب يقبل القسمة على العددين معاً.",
    "للتقسيم إلى مجموعات متساوية أو قطع متساوية استخدم أكبر قاسم مشترك.",
    "لأوقات الالتقاء أو الدورات المتكررة استخدم أصغر مضاعف مشترك.",
  ],
  trick_ar: {
    statement: "حدّد أولاً: تقسيم متساوٍ → قاسم، التقاء معاً → مضاعف.",
    steps: [
      "للقاسم: اقسم الأكبر على الأصغر وكرّر بالباقي حتى يصير الباقي صفراً",
      "للمضاعف: اضرب العددين ثم اقسم على أكبر قاسم مشترك",
      "تذكّر: حاصل العددين = القاسم × المضاعف",
    ],
    time_target_sec: 22,
    example_ar:
      "١٢ و ١٨: أكبر قاسم مشترك = ٦، وأصغر مضاعف مشترك = ٣٦ لأن ١٢×١٨ = ٦×٣٦.",
  },
  timing: {
    excellent_sec: 22,
    good_sec: 32,
    ok_sec: 43,
    slow_sec: 57,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "gl-01",
      prompt_ar:
        "شريط طوله 12 متراً وآخر طوله 18 متراً. ما أطول قطعة متساوية يمكن قطع الشريطين إليها بلا بقايا؟",
      choices_ar: ["3", "6", "9", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر من الأكبر.",
        2: "لا يقسم 12 بلا باقٍ.",
        3: "لا يقسم 18 بلا باقٍ.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 12 و 18. 18 = 12×1 + 6، ثم 12 = 6×2 + 0. إذن أكبر قاسم مشترك = 6 أمتار.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-02",
      prompt_ar:
        "حافلة تصل كل 4 دقائق وأخرى كل 6 دقائق، وتلتقيان الآن عند المحطة. بعد كم دقيقة تلتقيان مجدداً؟",
      choices_ar: ["8", "10", "12", "24"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب أحدهما فقط.",
        1: "جُمع العددان خطأً.",
        3: "حُسب حاصل العددين بدل أصغر مضاعف.",
      },
      solve_ar:
        "المطلوب أصغر مضاعف مشترك لـ 4 و 6. أكبر قاسم مشترك = 2، إذن أصغر مضاعف = (4×6) تقسيم 2 = 12 دقيقة.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-03",
      prompt_ar:
        "علبة فيها 24 قلماً وأخرى فيها 36 قلماً. ما أكبر عدد علب متساوية يمكن توزيع الأقلام فيها بلا بقايا؟",
      choices_ar: ["6", "8", "12", "18"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "لا يقسم 36.",
        3: "لا يقسم 24.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 24 و 36. 36 = 24×1 + 12، ثم 24 = 12×2 + 0. إذن أكبر قاسم = 12 علبة.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-04",
      prompt_ar:
        "جرس يرن كل 3 دقائق وآخر كل 5 دقائق، وقد رنّا معاً الآن. متى يرنّان معاً مرة أخرى؟",
      choices_ar: ["8", "10", "15", "30"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع العددان.",
        1: "ضُرب أحدهما وأُضيف خطأ.",
        3: "حُسب حاصل العددين بدل أصغر مضاعف أوليّين.",
      },
      solve_ar:
        "3 و 5 أوليّان نسبياً، فأكبر قاسم مشترك = 1. أصغر مضاعف مشترك = 3×5 = 15 دقيقة.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-05",
      prompt_ar:
        "في صف 20 طالباً وفي آخر 30 طالباً. ما أكبر عدد مجموعات متساوية يمكن تكوينها من كل صف بلا بقايا؟",
      choices_ar: ["5", "10", "15", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        2: "لا يقسم 20.",
        3: "لا يقسم 30.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 20 و 30. 30 = 20×1 + 10، ثم 20 = 10×2 + 0. إذن أكبر قاسم = 10 مجموعات.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-06",
      prompt_ar:
        "آلة تطبع ملصقاً كل 8 ثوانٍ وأخرى كل 12 ثانية، وتبدآن معاً. بعد كم ثانية تطبعان ملصقاً في اللحظة نفسها مجدداً؟",
      choices_ar: ["16", "20", "24", "96"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "جُمع العددان خطأً.",
        3: "حُسب حاصل العددين بدل أصغر مضاعف.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 8 و 12 = 4. أصغر مضاعف مشترك = (8×12) تقسيم 4 = 24 ثانية.",
      trick_ref: "gcd-lcm",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-07",
      prompt_ar:
        "لفافة قماش طولها 15 متراً وأخرى 25 متراً. ما أطول شريط متساوٍ يمكن قصّ اللفافتين إليه بلا بقايا؟",
      choices_ar: ["3", "5", "10", "15"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        2: "لا يقسم 15.",
        3: "لا يقسم 25.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 15 و 25. 25 = 15×1 + 10، و 15 = 10×1 + 5، و 10 = 5×2 + 0. إذن أكبر قاسم = 5 أمتار.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-08",
      prompt_ar:
        "طالب يراجع كل 6 أيام وآخر كل 9 أيام، وقد راجعا معاً اليوم. بعد كم يوماً يراجعان معاً مجدداً؟",
      choices_ar: ["12", "15", "18", "54"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف أحدهما فقط.",
        1: "جُمع العددان.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 6 و 9 = 3. أصغر مضاعف مشترك = (6×9) تقسيم 3 = 18 يوماً.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-09",
      prompt_ar:
        "صندوق فيه 16 كأساً وآخر فيه 24 كأساً. ما أكبر عدد صفوف متساوية يمكن ترتيب الكؤوس فيها من كل صندوق بلا بقايا؟",
      choices_ar: ["4", "6", "8", "12"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "لا يقسم 16.",
        3: "لا يقسم 16.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 16 و 24. 24 = 16×1 + 8، ثم 16 = 8×2 + 0. إذن أكبر قاسم = 8 صفوف.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-10",
      prompt_ar:
        "مصباح يومض كل 10 ثوانٍ وآخر كل 15 ثانية، وقد ومضا معاً. بعد كم ثانية يومضان معاً مرة أخرى؟",
      choices_ar: ["20", "25", "30", "150"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "جُمع العددان.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 10 و 15 = 5. أصغر مضاعف مشترك = (10×15) تقسيم 5 = 30 ثانية.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-11",
      prompt_ar:
        "كيس فيه 48 حبة وآخر فيه 36 حبة. ما أكبر عدد أكياس صغيرة متساوية يمكن تعبئتها من الكيسين بلا بقايا؟",
      choices_ar: ["6", "9", "12", "18"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "لا يقسم 48.",
        3: "لا يقسم 48.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 48 و 36. 48 = 36×1 + 12، ثم 36 = 12×3 + 0. إذن أكبر قاسم = 12 كيساً.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-12",
      prompt_ar:
        "فريق يتدرب كل 7 أيام وآخر كل 5 أيام، وقد تدربا معاً اليوم. بعد كم يوماً يتدربان معاً مجدداً؟",
      choices_ar: ["12", "24", "35", "70"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع العددان.",
        1: "ضُرب أحدهما خطأ.",
        3: "حُسب حاصل مضاعف أكبر من الأصغر.",
      },
      solve_ar:
        "7 و 5 أوليّان نسبياً، فأكبر قاسم مشترك = 1. أصغر مضاعف مشترك = 7×5 = 35 يوماً.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-13",
      prompt_ar:
        "شريط طوله 45 سم وآخر 60 سم. ما أطول قطعة متساوية يمكن قطع الشريطين إليها بلا بقايا؟",
      choices_ar: ["5", "10", "15", "30"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "قاسم مشترك أصغر.",
        3: "لا يقسم 45.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 45 و 60. 60 = 45×1 + 15، ثم 45 = 15×3 + 0. إذن أكبر قاسم = 15 سم.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-14",
      prompt_ar:
        "رافعة ترفع حملاً كل 9 دقائق وأخرى كل 12 دقيقة، وقد عملتا معاً الآن. بعد كم دقيقة تعملان معاً مجدداً؟",
      choices_ar: ["18", "24", "36", "108"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "ضُعف العدد الأكبر فقط.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 9 و 12 = 3. أصغر مضاعف مشترك = (9×12) تقسيم 3 = 36 دقيقة.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-15",
      prompt_ar:
        "فصل فيه 28 طالباً وآخر فيه 42 طالباً. ما أكبر عدد مجموعات متساوية يمكن تكوينها من كل فصل بلا بقايا؟",
      choices_ar: ["7", "14", "21", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        2: "لا يقسم 28.",
        3: "لا يقسم 42.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 28 و 42. 42 = 28×1 + 14، ثم 28 = 14×2 + 0. إذن أكبر قاسم = 14 مجموعة.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-16",
      prompt_ar:
        "مضخة تعمل كل 8 ساعات وأخرى كل 10 ساعات، وقد اشتغلتا معاً. بعد كم ساعة تشتغلان معاً مجدداً؟",
      choices_ar: ["18", "20", "40", "80"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع العددان.",
        1: "ضُعف العدد الأصغر فقط.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 8 و 10 = 2. أصغر مضاعف مشترك = (8×10) تقسيم 2 = 40 ساعة.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-17",
      prompt_ar:
        "لفافة شريط طولها 54 متراً وأخرى 72 متراً. ما أطول قطعة متساوية يمكن قصّ اللفافتين إليها بلا بقايا؟",
      choices_ar: ["6", "9", "18", "27"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "قاسم مشترك أصغر.",
        3: "لا يقسم 72.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 54 و 72. 72 = 54×1 + 18، ثم 54 = 18×3 + 0. إذن أكبر قاسم = 18 متراً.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-18",
      prompt_ar:
        "شاحنة تصل كل 12 ساعة وأخرى كل 18 ساعة، وقد وصلتا معاً. بعد كم ساعة تصلان معاً مرة أخرى؟",
      choices_ar: ["24", "30", "36", "216"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "جُمع العددان.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 12 و 18 = 6. أصغر مضاعف مشترك = (12×18) تقسيم 6 = 36 ساعة.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "gl-f01",
      prompt_ar:
        "صندوق فيه 35 كتيباً وآخر فيه 49 كتيباً. ما أكبر عدد حزم متساوية يمكن تكوينها من الصندوقين بلا بقايا؟",
      choices_ar: ["5", "7", "14", "35"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        2: "لا يقسم 35.",
        3: "لا يقسم 49.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 35 و 49. 49 = 35×1 + 14، و 35 = 14×2 + 7، و 14 = 7×2 + 0. إذن أكبر قاسم = 7 حزم.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f02",
      prompt_ar:
        "إشارة مرور تتبدل كل 4 دقائق وأخرى كل 10 دقائق، وقد تبدّلتا معاً. بعد كم دقيقة تتبدّلان معاً مجدداً؟",
      choices_ar: ["14", "16", "20", "40"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع العددان.",
        1: "ضُعف العدد الأصغر مرتين.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 4 و 10 = 2. أصغر مضاعف مشترك = (4×10) تقسيم 2 = 20 دقيقة.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f03",
      prompt_ar:
        "علبة فيها 40 قطعة حلوى وأخرى فيها 56 قطعة. ما أكبر عدد أكياس متساوية يمكن تعبئتها من العلبتين بلا بقايا؟",
      choices_ar: ["4", "8", "16", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        2: "لا يقسم 40.",
        3: "لا يقسم 56.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 40 و 56. 56 = 40×1 + 16، و 40 = 16×2 + 8، و 16 = 8×2 + 0. إذن أكبر قاسم = 8 أكياس.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f04",
      prompt_ar:
        "طابعة تنهي مهمة كل 6 دقائق وأخرى كل 8 دقائق، وقد أنهتا معاً. بعد كم دقيقة تنهيان معاً مجدداً؟",
      choices_ar: ["12", "16", "24", "48"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "ضُعف العدد الأكبر فقط.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 6 و 8 = 2. أصغر مضاعف مشترك = (6×8) تقسيم 2 = 24 دقيقة.",
      trick_ref: "gcd-lcm",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f05",
      prompt_ar:
        "شريط طوله 63 سم وآخر 84 سم. ما أطول قطعة متساوية يمكن قطع الشريطين إليها بلا بقايا؟",
      choices_ar: ["7", "14", "21", "42"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "قاسم مشترك أصغر.",
        3: "لا يقسم 63.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 63 و 84. 84 = 63×1 + 21، ثم 63 = 21×3 + 0. إذن أكبر قاسم = 21 سم.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f06",
      prompt_ar:
        "دورية حراسة كل 14 يوماً ودورية أخرى كل 21 يوماً، وقد اجتمعتا اليوم. بعد كم يوماً تجتمعان مجدداً؟",
      choices_ar: ["28", "35", "42", "294"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف العدد الأصغر فقط.",
        1: "جُمع العددان أو ضُرب خطأ.",
        3: "حُسب حاصل العددين.",
      },
      solve_ar:
        "أكبر قاسم مشترك لـ 14 و 21 = 7. أصغر مضاعف مشترك = (14×21) تقسيم 7 = 42 يوماً.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "gl-f07",
      prompt_ar:
        "صندوق فيه 32 كرة وآخر فيه 48 كرة. ما أكبر عدد مجموعات متساوية يمكن تكوينها من الصندوقين بلا بقايا؟",
      choices_ar: ["8", "12", "16", "24"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قاسم مشترك أصغر.",
        1: "لا يقسم 32.",
        3: "لا يقسم 32.",
      },
      solve_ar:
        "المطلوب أكبر قاسم مشترك لـ 32 و 48. 48 = 32×1 + 16، ثم 32 = 16×2 + 0. إذن أكبر قاسم = 16 مجموعة.",
      trick_ref: "gcd-lcm",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
