import type { Skill } from "@/lib/types";

export const numberSense: Skill = {
  id: "number-sense",
  title_ar: "الحس العددي",
  domain: "arithmetic",
  hook_ar: "قارن وقدّر دون ضرب كامل — وفّر الوقت في الاختبار",
  estimated_minutes: 6,
  icon: "≈",
  visual: { kind: "custom", component: "number-sense-lab" },
  intuition_ar: [
    "عند مقارنة ضربين متقاربين: اقترب من مربع عدد لطيف، ثم صحّح الفرق.",
    "صيغة مفيدة: (ن−1)(ن+1) = ن² − 1، فالمربع أكبر بمقدار واحد.",
    "للتقدير: قرّب للأعداد السهلة، ثم اضبط الاتجاه. راقب ترتيب العمليات: الضرب قبل الجمع.",
  ],
  trick_ar: {
    statement: "قارن بالقرب من مربع لطيف، وقدّر بالتقريب ثم التصحيح.",
    steps: [
      "للمقارنة: حوّل إلى شكل (ن−أ)(ن+أ) أو إلى قرب ن²",
      "للتقدير: قرّب ثم زد أو انقص حسب الاتجاه",
      "للعمليات: نفّذ × و÷ قبل + و−، والأقواس أولاً",
    ],
    time_target_sec: 20,
    example_ar:
      "19×21 مقابل 20×20: 19×21 = 400 − 1 = 399، و20×20 = 400. إذن المربع أكبر بواحد.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ns-01",
      prompt_ar:
        "في بطاقة أسعار: أيّهما أكبر قيمة، 19×21 أم 20×20؟",
      choices_ar: ["19×21", "20×20", "متساويان", "لا يمكن الحسم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الزوج أكبر لأنه يبدو أعرض انتشاراً.",
        2: "نُسي أن الفرق بينهما واحد.",
        3: "المقارنة ممكنة بلا ضرب كامل.",
      },
      solve_ar:
        "19×21 = (20−1)(20+1) = 20² − 1 = 399. و20×20 = 400. إذن 20×20 أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-02",
      prompt_ar:
        "قدّر ناتج 48×52 لأقرب مئة في جرد مستودع.",
      choices_ar: ["2300", "2400", "2500", "2600"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُرّب بأقل من اللازم.",
        1: "نُقصت مئة بعد التقريب.",
        3: "زِيد الناتج فوق المربع.",
      },
      solve_ar:
        "48×52 = (50−2)(50+2) = 50² − 4 = 2500 − 4 = 2496. أقرب مئة هي 2500.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-03",
      prompt_ar:
        "حاسبة عرض أسعار حسبت 8 + 4 × 3. ما الناتج الصحيح؟",
      choices_ar: ["20", "24", "36", "14"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع ثم ضُرب بترتيب خاطئ جزئياً.",
        2: "نُفّذ الجمع قبل الضرب: (8+4)×3.",
        3: "طُرح بدل الجمع بعد الضرب.",
      },
      solve_ar:
        "الضرب قبل الجمع: 4 × 3 = 12، ثم 8 + 12 = 20.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-04",
      prompt_ar:
        "مقارنة مقاعد: أيّهما أكبر، 99×101 أم 100×100؟",
      choices_ar: ["99×101", "100×100", "متساويان", "الفرق أكثر من 10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ أن انتشار العاملين يزيد الناتج.",
        2: "نُسي طرح الواحد من المربع.",
        3: "الفرق فعلياً واحد فقط.",
      },
      solve_ar:
        "99×101 = 100² − 1 = 9999. و100×100 = 10000. فالمربع أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-05",
      prompt_ar:
        "أي مجموع أكبر في عدّ نقاط مباراتين: 198 + 203 أم 200 + 200؟",
      choices_ar: ["198 + 203", "200 + 200", "متساويان", "لا يمكن المقارنة"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ أن التقريب للمائتين يزيد المجموع.",
        2: "نُسي أن الزيادة 3 أكبر من النقص 2.",
        3: "المقارنة مباشرة بالحساب الذهني.",
      },
      solve_ar:
        "198 + 203 = 401، و200 + 200 = 400. الزيادة عن 200 هي +3 والنقص −2، فالصافي +1. إذن 198 + 203 أكبر.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-06",
      prompt_ar:
        "قدّر 39×41 لأقرب عشرة في حساب تكلفة طباعة.",
      choices_ar: ["1580", "1600", "1620", "1560"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص أكثر من الفرق الحقيقي.",
        2: "زِيد فوق المربع بدل طرح الواحد.",
        3: "قُرّب لأقل من الناتج.",
      },
      solve_ar:
        "39×41 = 40² − 1 = 1600 − 1 = 1599. أقرب عشرة هي 1600.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-07",
      prompt_ar:
        "أيّهما أكبر بلاكة شحن: 25×24 أم 26×23؟",
      choices_ar: ["25×24", "26×23", "متساويان", "الفرق 10 فأكثر"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ أن 26 الأكبر عاملاً يعطي ناتجاً أكبر.",
        2: "الناتجان مختلفان.",
        3: "الفرق صغير (2) وليس 10.",
      },
      solve_ar:
        "25×24 = 600. و26×23 = 26×20 + 26×3 = 520 + 78 = 598. إذن 25×24 أكبر بـ 2.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-08",
      prompt_ar:
        "ما قيمة 12 ÷ 3 × 2 حسب ترتيب العمليات؟",
      choices_ar: ["2", "8", "18", "1"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُفّذت القسمة على الناتج كله: 12÷(3×2).",
        2: "جُمع بدل الضرب بعد القسمة.",
        3: "عُكست كل العمليات.",
      },
      solve_ar:
        "القسمة والضرب من اليسار إلى اليمين: 12 ÷ 3 = 4، ثم 4 × 2 = 8.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-09",
      prompt_ar:
        "أي تعبير أقرب إلى 2000: 49×41 أم 51×39؟",
      choices_ar: ["49×41", "51×39", "متساويان في البعد", "كلاهما أبعد من 20"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ أن 51×39 أقرب لأنه تحت 2000.",
        2: "البعدان مختلفان: 9 مقابل 11.",
        3: "البعدان أقل من 20.",
      },
      solve_ar:
        "49×41 = 2009 (أبعد بـ 9). و51×39 = 1989 (أبعد بـ 11). إذن 49×41 أقرب إلى 2000.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-10",
      prompt_ar:
        "مقارنة مربعات مقاعد: أيّهما أكبر، 15×17 أم 16×16؟",
      choices_ar: ["15×17", "16×16", "متساويان", "الفرق أكثر من 5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ الزوج أكبر.",
        2: "الفرق واحد وليس صفراً.",
        3: "الفرق واحد فقط.",
      },
      solve_ar:
        "15×17 = 16² − 1 = 256 − 1 = 255. و16×16 = 256. فالمربع أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-11",
      prompt_ar:
        "قدّر مجموع 297 + 304 لأقرب مئة في عدّ زوار معرض.",
      choices_ar: ["500", "600", "700", "550"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرّب بأقل بكثير.",
        2: "زِيد فوق المجموع الحقيقي.",
        3: "قُرّب إلى منتصف المئات بلا حاجة.",
      },
      solve_ar:
        "297 + 304 = 601. أقرب مئة هي 600.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-12",
      prompt_ar:
        "أيّهما أكبر في صف علب: 9×11 أم 8×12؟",
      choices_ar: ["9×11", "8×12", "متساويان", "الفرق 10"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ أن 12 الأكبر عاملاً يكفي.",
        2: "الناتجان 99 و96 مختلفان.",
        3: "الفرق 3 وليس 10.",
      },
      solve_ar:
        "9×11 = 99. و8×12 = 96. إذن 9×11 أكبر بـ 3.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-13",
      prompt_ar:
        "ما ناتج 6 × (2 + 3)؟",
      choices_ar: ["15", "18", "30", "12"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُفّذ 6×2 ثم أُضيف 3 بلا أقواس.",
        1: "حُسب 6×3 فقط.",
        3: "ضُرب 6 في 2 فقط.",
      },
      solve_ar:
        "الأقواس أولاً: 2 + 3 = 5، ثم 6 × 5 = 30.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-14",
      prompt_ar:
        "أيّهما أكبر لعدد التذاكر: 45×55 أم 50×50؟",
      choices_ar: ["45×55", "50×50", "متساويان", "الفرق أقل من 10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ انتشار العاملين يزيد الناتج.",
        2: "الفرق 25 وليس صفراً.",
        3: "الفرق 25 وهو أكبر من 10.",
      },
      solve_ar:
        "45×55 = (50−5)(50+5) = 50² − 25 = 2475. و50×50 = 2500. فالمربع أكبر بـ 25.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-15",
      prompt_ar:
        "قدّر 78×22 لأقرب مئة في شحنة طرود.",
      choices_ar: ["1600", "1700", "1800", "1500"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اقتُصر على 80×20 = 1600 دون تصحيح.",
        2: "زِيد التقريب فوق الناتج.",
        3: "قُرّب بأقل من اللازم.",
      },
      solve_ar:
        "78×22 = 78×20 + 78×2 = 1560 + 156 = 1716. أقرب مئة هي 1700.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-16",
      prompt_ar:
        "أيّهما أكبر: 199×201 أم 200×200؟",
      choices_ar: ["199×201", "200×200", "متساويان", "الفرق أكثر من 5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ الزوج أكبر.",
        2: "الفرق واحد.",
        3: "الفرق واحد فقط.",
      },
      solve_ar:
        "199×201 = 200² − 1 = 39999. و200×200 = 40000. فالمربع أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-17",
      prompt_ar:
        "أي مجموع أكبر: 495 + 508 أم 500 + 500؟",
      choices_ar: ["495 + 508", "500 + 500", "متساويان", "الفرق 10 فأكثر"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ التقريب يزيد المجموع.",
        2: "الصافي +3 وليس صفراً.",
        3: "الفرق 3 فقط.",
      },
      solve_ar:
        "عن 500: النقص 5 والزيادة 8، فالصافي +3. إذن 495 + 508 = 1003 أكبر من 1000.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-18",
      prompt_ar:
        "ما قيمة 3 + 5 × 4 − 2؟",
      choices_ar: ["30", "21", "18", "24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُفّذ الجمع والطرح قبل الضرب من اليسار.",
        2: "نُسي إضافة 3 بعد 5×4−2.",
        3: "حُسب (3+5)×4−2 جزئياً.",
      },
      solve_ar:
        "الضرب أولاً: 5 × 4 = 20. ثم 3 + 20 − 2 = 21.",
      trick_ref: "number-sense",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "ns-f01",
      prompt_ar:
        "أيّهما أكبر في تقدير مساحة: 29×31 أم 30×30؟",
      choices_ar: ["29×31", "30×30", "متساويان", "الفرق أكثر من 5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ الزوج أكبر.",
        2: "الفرق واحد.",
        3: "الفرق واحد فقط.",
      },
      solve_ar:
        "29×31 = 30² − 1 = 899. و30×30 = 900. فالمربع أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f02",
      prompt_ar:
        "قدّر 61×39 لأقرب مئة في ميزانية حملة.",
      choices_ar: ["2300", "2400", "2500", "2200"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرّب بأقل من الناتج.",
        2: "زِيد فوق الناتج الحقيقي.",
        3: "قُرّب لأقل بكثير.",
      },
      solve_ar:
        "61×39 = 61×40 − 61 = 2440 − 61 = 2379. أقرب مئة هي 2400.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f03",
      prompt_ar:
        "أيّهما أكبر: 18×22 أم 19×21؟",
      choices_ar: ["18×22", "19×21", "متساويان", "الفرق أكثر من 10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ أن انتشار العاملين الأكبر يعطي ناتجاً أكبر.",
        2: "الناتجان مختلفان بثلاثة.",
        3: "الفرق 3 وليس أكثر من 10.",
      },
      solve_ar:
        "18×22 = 20² − 4 = 396. و19×21 = 20² − 1 = 399. إذن 19×21 أكبر بـ 3.",
      trick_ref: "number-sense",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f04",
      prompt_ar:
        "ما ناتج 20 − 4 × 3 + 2؟",
      choices_ar: ["14", "10", "50", "6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُفّذ الطرح قبل الضرب: (20−4)×3 ثم تعديل.",
        2: "جُمع كل الأعداد ثم ضُرب.",
        3: "طُرح الناتج كله من 20.",
      },
      solve_ar:
        "الضرب أولاً: 4 × 3 = 12. ثم 20 − 12 + 2 = 10.",
      trick_ref: "number-sense",
      difficulty: "mid",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f05",
      prompt_ar:
        "أي مجموع أكبر: 1499 + 1504 أم 1500 + 1500؟",
      choices_ar: ["1499 + 1504", "1500 + 1500", "متساويان", "الفرق 10 فأكثر"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ العددين المستديرين أكبرين.",
        2: "الصافي +3.",
        3: "الفرق 3 فقط.",
      },
      solve_ar:
        "عن 1500: النقص 1 والزيادة 4، فالصافي +3. المجموع 3003 أكبر من 3000.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f06",
      prompt_ar:
        "قدّر 95×105 لأقرب مئة.",
      choices_ar: ["9900", "10000", "10100", "9800"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص إلى 9900 مع أن البعد عنها أكبر.",
        2: "زِيد فوق المربع.",
        3: "نُقص أكثر من اللازم.",
      },
      solve_ar:
        "95×105 = 100² − 5² = 10000 − 25 = 9975. أقرب مئة هي 10000 (البعد 25).",
      trick_ref: "number-sense",
      difficulty: "hard",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "ns-f07",
      prompt_ar:
        "أيّهما أكبر: 14×16 أم 15×15؟",
      choices_ar: ["14×16", "15×15", "متساويان", "الفرق أكثر من 5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ الزوج أكبر.",
        2: "الفرق واحد.",
        3: "الفرق واحد فقط.",
      },
      solve_ar:
        "14×16 = 15² − 1 = 224. و15×15 = 225. فالمربع أكبر بواحد.",
      trick_ref: "number-sense",
      difficulty: "easy",
      sub_pattern: "number_sense",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
