import type { Skill } from "@/lib/types";

export const percentOf: Skill = {
  id: "percent-of",
  title_ar: "النسبة من العدد",
  domain: "arithmetic",
  hook_ar: "حوّل النسبة إلى جزء سهل، ثم خذ هذا الجزء من العدد",
  estimated_minutes: 6,
  icon: "%",
  visual: { kind: "custom", component: "percent-of-lab" },
  intuition_ar: [
    "النسبة المئوية تحدد جزءاً من كل مكوّن من 100 جزء.",
    "لإيجاد س٪ من عدد: حوّل س٪ إلى كسر أو عدد عشري، ثم اضرب.",
    "لمعرفة ما النسبة التي يمثلها جزء من كل: اقسم الجزء على الكل، ثم اضرب في 100.",
  ],
  trick_ar: {
    statement: "ابدأ بالنسب السهلة، ثم ركّب النسبة المطلوبة.",
    steps: [
      "10٪ من العدد = اقسمه على 10",
      "5٪ = نصف 10٪، و25٪ = ربع العدد",
      "للسؤال العكسي: الجزء تقسيم الكل، ثم ضرب 100",
    ],
    time_target_sec: 16,
    example_ar:
      "25٪ من 240 = ربع 240 = 60. وعكسياً: 60 تقسيم 240 = 0.25 أي 25٪.",
  },
  timing: {
    excellent_sec: 16,
    good_sec: 25,
    ok_sec: 35,
    slow_sec: 48,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "po-01",
      prompt_ar: "خصصت مكتبة 25٪ من 240 كتاباً لرف العلوم. كم كتاباً خُصص للرف؟",
      choices_ar: ["50", "60", "80", "96"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبرت 25٪ كأنها خمس العدد.",
        2: "قُسم العدد على 3 بدلاً من 4.",
        3: "حُسبت 40٪ من العدد.",
      },
      solve_ar:
        "25٪ تعني ربع العدد. 240 تقسيم 4 = 60. إذن خُصص 60 كتاباً.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-02",
      prompt_ar: "أُرسل 15٪ من 320 طرداً بالشحن السريع. كم طرداً أُرسل بهذه الطريقة؟",
      choices_ar: ["32", "40", "48", "64"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 10٪ فقط.",
        1: "حُسبت 12.5٪ من العدد.",
        3: "حُسبت 20٪ من العدد.",
      },
      solve_ar:
        "10٪ من 320 = 32، و5٪ = 16. نجمعهما: 32 + 16 = 48 طرداً.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-03",
      prompt_ar: "أصاب لاعب 18 رمية من أصل 72 رمية. ما النسبة المئوية للرميات المصابة؟",
      choices_ar: ["20٪", "25٪", "30٪", "40٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرّبت النسبة إلى خمس الكل دون قسمة صحيحة.",
        2: "اعتُبر الجزء أكبر من ربعه.",
        3: "عُكست العلاقة بين الجزء والكل.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 18 تقسيم 72 = 0.25. نضرب في 100، فتكون النسبة 25٪.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-04",
      prompt_ar: "تبلغ رسوم التأمين على شحنة 12٪ من قيمتها البالغة 450 ريالاً. كم تبلغ الرسوم؟",
      choices_ar: ["45", "50", "54", "62"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 10٪ فقط.",
        1: "قُرّبت النسبة دون حساب دقيق.",
        3: "جُمع 12 إلى جزء من القيمة.",
      },
      solve_ar:
        "12٪ من 450 = 0.12 ضرب 450 = 54. إذن الرسوم 54 ريالاً.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-05",
      prompt_ar: "أكمل عدّاء 35٪ من مسار طوله 200 متر. كم متراً أكمل؟",
      choices_ar: ["60", "65", "70", "75"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 30٪ فقط.",
        1: "أضيفت 5 إلى ناتج 30٪ بدلاً من حساب 5٪.",
        3: "حُسبت نسبة أكبر من 35٪.",
      },
      solve_ar:
        "30٪ من 200 = 60، و5٪ من 200 = 10. المجموع 60 + 10 = 70 متراً.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-06",
      prompt_ar: "مثّل الموظفون الجدد 45 موظفاً من أصل 300 موظف. ما نسبتهم المئوية؟",
      choices_ar: ["12٪", "15٪", "18٪", "20٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من الجزء الحقيقي.",
        2: "اعتُبر 45 جزءاً من 250 بدلاً من 300.",
        3: "عُدّ الخمس بدلاً من 45 من 300.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 45 تقسيم 300 = 0.15. نضرب في 100، فتكون النسبة 15٪.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-07",
      prompt_ar: "خُصص 7.5٪ من 800 مقعد في مهرجان للضيوف. كم مقعداً خُصص لهم؟",
      choices_ar: ["50", "60", "75", "80"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت نسبة 6.25٪.",
        2: "حُذفت العلامة العشرية فعوملت النسبة بصورة خاطئة.",
        3: "حُسبت 10٪ كاملة.",
      },
      solve_ar:
        "5٪ من 800 = 40، و2.5٪ = 20. نجمعهما: 40 + 20 = 60 مقعداً.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-08",
      prompt_ar: "شاهد 40٪ من 350 مشتركاً البث المباشر. كم مشتركاً شاهده؟",
      choices_ar: ["120", "130", "140", "150"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من 40٪.",
        1: "نُقصت عشرة من الناتج الصحيح بلا سبب.",
        3: "قُرّب الناتج إلى عدد أكبر.",
      },
      solve_ar:
        "40٪ تعني 0.4. نحسب 0.4 ضرب 350 = 140 مشتركاً.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-09",
      prompt_ar: "وصلت 84 رسالة في الساعة الأولى من أصل 420 رسالة. ما النسبة المئوية التي وصلت؟",
      choices_ar: ["18٪", "20٪", "22٪", "25٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من الجزء الحقيقي.",
        2: "قُرّبت القسمة إلى نسبة أعلى.",
        3: "اعتُبر الجزء ربع الكل، لكنه يساوي خمسه.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 84 تقسيم 420 = 0.2. نضرب في 100، فتكون النسبة 20٪.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-10",
      prompt_ar: "استهلك جهاز 62.5٪ من بطارية سعتها 160 وحدة طاقة. كم وحدة استهلك؟",
      choices_ar: ["90", "100", "110", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من 62.5٪.",
        2: "أضيفت عشرة إلى الناتج الصحيح.",
        3: "حُسبت 75٪ من السعة.",
      },
      solve_ar:
        "62.5٪ = 50٪ + 12.5٪. نصف 160 = 80، وثمن 160 = 20. المجموع 80 + 20 = 100 وحدة.",
      trick_ref: "percent-of",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-11",
      prompt_ar: "يعادل بدل النقل 18٪ من راتب أساسي مقداره 250 ريالاً في مثال تدريبي. كم قيمة البدل؟",
      choices_ar: ["40", "45", "50", "55"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت 16٪ من الراتب.",
        2: "حُسبت 20٪ بدلاً من 18٪.",
        3: "زِيد الناتج عشرة بلا أساس.",
      },
      solve_ar:
        "18٪ من 250 = 0.18 ضرب 250 = 45. إذن قيمة البدل 45 ريالاً.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-12",
      prompt_ar: "كانت 96 صورة من أصل 320 صورة ملتقطة ليلاً. ما نسبتها المئوية؟",
      choices_ar: ["25٪", "30٪", "32٪", "35٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبر الجزء ربع الكل فقط.",
        2: "خُلط عدد المئات في الكل بالنسبة.",
        3: "قُرّبت النسبة إلى قيمة أعلى.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 96 تقسيم 320 = 0.3. نضرب في 100، فتكون النسبة 30٪.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-13",
      prompt_ar: "تغطي الأشجار 22٪ من حديقة مساحتها 450 متراً مربعاً. ما المساحة التي تغطيها؟",
      choices_ar: ["90", "95", "99", "110"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 20٪ فقط.",
        1: "أضيفت خمسة إلى 20٪ بدلاً من حساب 2٪.",
        3: "عوملت 22٪ كأنها 22 من كل 90.",
      },
      solve_ar:
        "20٪ من 450 = 90، و2٪ من 450 = 9. المجموع 90 + 9 = 99 متراً مربعاً.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-14",
      prompt_ar: "اختير 5٪ من 760 طلباً للمراجعة اليدوية. كم طلباً اختير؟",
      choices_ar: ["35", "38", "40", "45"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرّب نصف 10٪ إلى قيمة أقل.",
        2: "حُسبت 5٪ من 800 بدلاً من 760.",
        3: "حُسبت نسبة أكبر من 5٪.",
      },
      solve_ar:
        "10٪ من 760 = 76، و5٪ هي نصفها. 76 تقسيم 2 = 38 طلباً.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-15",
      prompt_ar: "حجز جمهور فريق 135 مقعداً من أصل 450 مقعداً. ما النسبة المئوية للمقاعد المحجوزة؟",
      choices_ar: ["25٪", "30٪", "35٪", "40٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبر الجزء ربع المقاعد.",
        2: "قُرّبت النسبة إلى قيمة أعلى.",
        3: "عُدّ الجزء أكبر مما هو عليه.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 135 تقسيم 450 = 0.3. نضرب في 100، فتكون النسبة 30٪.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-16",
      prompt_ar: "يمثل قسم المقدمة 12.5٪ من فيلم مدته 480 ثانية. كم ثانية يستغرق؟",
      choices_ar: ["48", "60", "72", "80"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت 10٪ فقط.",
        2: "حُسبت 15٪ من المدة.",
        3: "حُسب سدس المدة تقريباً.",
      },
      solve_ar:
        "12.5٪ تعني ثمن العدد. 480 تقسيم 8 = 60 ثانية.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-17",
      prompt_ar: "كانت 27 عينة من أصل 120 عينة زرقاء. ما نسبتها المئوية؟",
      choices_ar: ["20٪", "22.5٪", "25٪", "27٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اعتُبر الجزء خمس الكل فقط.",
        2: "قُرّبت النسبة إلى الربع.",
        3: "عُدّ عدد العينات نفسه نسبة مئوية.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 27 تقسيم 120 = 0.225. نضرب في 100، فتكون النسبة 22.5٪.",
      trick_ref: "percent-of",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-18",
      prompt_ar: "خُصص 32٪ من 625 ميجابايت لملف تعليمي. ما حجم الجزء المخصص؟",
      choices_ar: ["180", "190", "200", "220"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من 32٪.",
        1: "نُقصت عشرة من الناتج الصحيح.",
        3: "حُسبت نسبة أكبر من المطلوب.",
      },
      solve_ar:
        "32٪ من 625 = 0.32 ضرب 625. وبما أن 625 ضرب 32 = 20000، نقسم على 100 فنحصل على 200 ميجابايت.",
      trick_ref: "percent-of",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "po-f01",
      prompt_ar: "شغلت النباتات 45٪ من 360 حوضاً في معرض زراعي. كم حوضاً شغلته؟",
      choices_ar: ["144", "152", "162", "180"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 40٪ فقط.",
        1: "جُمعت قيمة غير صحيحة إلى 40٪.",
        3: "حُسبت 50٪ من الأحواض.",
      },
      solve_ar:
        "40٪ من 360 = 144، و5٪ = 18. المجموع 144 + 18 = 162 حوضاً.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f02",
      prompt_ar: "أُنجزت 72 مهمة من أصل 480 مهمة في مشروع. ما النسبة المئوية المنجزة؟",
      choices_ar: ["12٪", "15٪", "18٪", "20٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من الجزء الحقيقي.",
        2: "قُرّبت القسمة إلى نسبة أعلى.",
        3: "اعتُبر الجزء خمس الكل.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 72 تقسيم 480 = 0.15. نضرب في 100، فتكون النسبة 15٪.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f03",
      prompt_ar: "تمثل عينات الجودة 6٪ من إنتاج بلغ 1250 قطعة. كم عينة فُحصت؟",
      choices_ar: ["60", "70", "75", "80"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من 6٪.",
        1: "قُرّب الناتج إلى عشرة غير صحيحة.",
        3: "حُسبت نسبة أكبر من المطلوب.",
      },
      solve_ar:
        "6٪ من 1250 = 0.06 ضرب 1250 = 75. إذن فُحصت 75 عينة.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f04",
      prompt_ar: "حملت الحافلات 110 طلاب من أصل 440 طالباً. ما نسبتهم المئوية؟",
      choices_ar: ["20٪", "22٪", "25٪", "30٪"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اعتُبر الجزء خمس الكل.",
        1: "قُرّبت النسبة إلى قيمة أقل.",
        3: "اعتُبر الجزء أكبر من ربعه.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 110 تقسيم 440 = 0.25. نضرب في 100، فتكون النسبة 25٪.",
      trick_ref: "percent-of",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f05",
      prompt_ar: "خصص مصمم 17.5٪ من لوحة عرض عرضها 400 بكسل للشعار. كم بكسلاً خُصص للشعار؟",
      choices_ar: ["60", "65", "70", "75"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت 15٪ فقط.",
        1: "أضيفت خمسة إلى ناتج 15٪ بدلاً من حساب 2.5٪.",
        3: "قُرّب الناتج إلى قيمة أعلى.",
      },
      solve_ar:
        "15٪ من 400 = 60، و2.5٪ من 400 = 10. المجموع 60 + 10 = 70 بكسلاً.",
      trick_ref: "percent-of",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f06",
      prompt_ar: "كانت 84 دقيقة من أصل 240 دقيقة مخصصة للتجارب. ما نسبتها المئوية؟",
      choices_ar: ["30٪", "32٪", "35٪", "40٪"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اعتُبر الجزء ثلاثة أعشار الكل.",
        1: "قُرّبت النسبة إلى قيمة أقل.",
        3: "اعتُبر الجزء خمسي الكل.",
      },
      solve_ar:
        "نقسم الجزء على الكل: 84 تقسيم 240 = 0.35. نضرب في 100، فتكون النسبة 35٪.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "po-f07",
      prompt_ar: "استُخدم 28٪ من 750 لتراً لري ملعب. كم لتراً استُخدم؟",
      choices_ar: ["190", "200", "210", "220"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "حُسبت نسبة أقل من 28٪.",
        1: "قُرّب الناتج إلى مئتين دون حساب دقيق.",
        3: "حُسبت نسبة أكبر من المطلوب.",
      },
      solve_ar:
        "28٪ من 750 = 0.28 ضرب 750 = 210. إذن استُخدم 210 لترات.",
      trick_ref: "percent-of",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
