import type { Skill } from "@/lib/types";

export const percentChange: Skill = {
  id: "percent-change",
  title_ar: "التغيّر المئوي",
  domain: "arithmetic",
  hook_ar: "اقسم دائماً على الأصل — لا على الرقم الجديد",
  estimated_minutes: 6,
  icon: "%",
  visual: { kind: "custom", component: "percent-change-lab" },
  intuition_ar: [
    "التغيّر = الرقم الجديد ناقص الأصل.",
    "نسبة التغيّر = التغيّر تقسيم الأصل، ثم نحوّلها إلى نسبة مئوية.",
    "القسمة على الرقم الجديد غلط شائع في القدرات.",
  ],
  trick_ar: {
    statement: "حوّل النسبة إلى ضرب سريع على الأصل.",
    steps: [
      "زيادة 25٪ = اضرب الأصل في 1.25",
      "نقص 20٪ = اضرب الأصل في 0.80",
      "لحساب النسبة: (الجديد ناقص الأصل) تقسيم الأصل",
    ],
    time_target_sec: 18,
    example_ar:
      "من 80 إلى 100: الفرق 20. عشرون تقسيم ثمانين = 0.25 أي 25٪ (ليس 20٪).",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "pc-01",
      prompt_ar: "ارتفع سعر تذكرة مباراة من 40 ريالاً إلى 50. كم نسبة الزيادة؟",
      choices_ar: ["20٪", "25٪", "10٪", "30٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق 10 على السعر الجديد 50.",
        2: "حُسب الفرق فقط دون تحويله لنسبة من الأصل.",
        3: "نسبة أكبر من الناتج الصحيح.",
      },
      solve_ar:
        "الفرق = 50 ناقص 40 = 10. نقسم الفرق على الأصل: 10 تقسيم 40 = 0.25. إذن الزيادة 25٪. (لا تقسم على 50).",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-02",
      prompt_ar: "رصيد شحن جوال 80 ريالاً وزيد بنسبة 25٪. كم صار الرصيد؟",
      choices_ar: ["100", "105", "95", "120"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُضيفت زيادة أكبر من 25٪.",
        2: "أُضيفت زيادة أقل من 25٪.",
        3: "هذه زيادة 50٪ لا 25٪.",
      },
      solve_ar:
        "زيادة 25٪ تعني نضرب الأصل في 1.25. 80 ضرب 1.25 = 100. أو: 25٪ من 80 = 20، ثم 80 زائد 20 = 100.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-03",
      prompt_ar:
        "انخفض سعر سماعة بنسبة 20٪ فصار 360 ريالاً. كم كان السعر قبل الانخفاض؟",
      choices_ar: ["432", "450", "400", "480"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب 360 في 1.2 بدل القسمة على 0.8.",
        2: "أُضيف تقدير تقريبي دون عوامل.",
        3: "حُسب كأن الانخفاض 25٪.",
      },
      solve_ar:
        "بعد انخفاض 20٪ يبقى 80٪ من السعر الأصلي. إذن الأصل = 360 تقسيم 0.8. 360 تقسيم 0.8 = 450 ريالاً.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-04",
      prompt_ar: "خزان ماء كان فيه 160 لتراً فأصبح 120. كم نسبة النقص؟",
      choices_ar: ["25٪", "33٪", "40٪", "20٪"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم النقص 40 على الكمية الجديدة 120.",
        2: "اُعتبر الفرق نسبة من مئة تقريباً.",
        3: "تقريب أقل من الصحيح.",
      },
      solve_ar:
        "النقص = 160 ناقص 120 = 40. نقسم على الأصل: 40 تقسيم 160 = 0.25. إذن النقص 25٪. (القسمة على 120 تعطي خطأ شائعاً نحو 33٪).",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-05",
      prompt_ar:
        "انخفض عدد مشاهدات فيديو من 480 إلى 408. كم نسبة النقص؟",
      choices_ar: ["12٪", "15٪", "18٪", "20٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق على العدد الجديد تقريباً.",
        2: "حُسب فرق أكبر من الواقع.",
        3: "قُسم الفرق على 360 أو اعتُبر النقص 20٪.",
      },
      solve_ar:
        "النقص = 480 ناقص 408 = 72. نقسم على الأصل: 72 تقسيم 480 = 0.15. إذن النقص 15٪. (لا تقسم على 408).",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-06",
      prompt_ar:
        "انخفضت قراءة عدّاد من 200 إلى 170. أي وصف صحيح؟",
      choices_ar: [
        "نقص بنسبة 15٪",
        "نقص بنسبة 18٪",
        "نقص بمقدار 15 فقط يعني 15٪",
        "نقص بنسبة 30٪",
      ],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم الفرق على القراءة الجديدة 170.",
        2: "خُلط المقدار المطلق بالنسبة المئوية.",
        3: "ضُوعف النسبة الصحيحة.",
      },
      solve_ar:
        "الفرق = 200 ناقص 170 = 30. نقسم على الأصل: 30 تقسيم 200 = 0.15. إذن النقص 15٪. لا نقسم على 170، ولا نعتبر أن «30» تعني 30٪ من مئة.",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-07",
      prompt_ar:
        "نقاط لاعب في لعبة إلكترونية ارتفعت من 60 إلى 75. كم نسبة الزيادة؟",
      choices_ar: ["15٪", "25٪", "20٪", "12.5٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الفرق 15 وعدّ نسبة مئوية مباشرة.",
        2: "قُسم الفرق على الرقم الجديد 75.",
        3: "حُسب نصف النسبة الصحيحة.",
      },
      solve_ar:
        "الفرق = 75 ناقص 60 = 15. نقسم على الأصل: 15 تقسيم 60 = 0.25. إذن الزيادة 25٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-08",
      prompt_ar:
        "رصيد بطاقة شحن كان 200 ريال ونقص بنسبة 15٪. كم بقي الرصيد؟",
      choices_ar: ["170", "185", "165", "150"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُقص أقل من 15٪.",
        2: "نُقص أكثر قليلاً من 15٪.",
        3: "هذا نقص 25٪ لا 15٪.",
      },
      solve_ar:
        "بعد نقص 15٪ يبقى 85٪ من الرصيد. نضرب: 200 ضرب 0.85 = 170. أو: 15٪ من 200 = 30، ثم 200 ناقص 30 = 170.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-09",
      prompt_ar:
        "اشتراك تطبيق تعليم زاد بنسبة 25٪ فصار 500 ريال سنوياً. كم كان الاشتراك قبل الزيادة؟",
      choices_ar: ["375", "400", "425", "450"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 25٪ من 500 بدل القسمة على 1.25.",
        2: "تقريب بلا عوامل.",
        3: "خُصم 10٪ من 500 فقط.",
      },
      solve_ar:
        "بعد الزيادة يصبح السعر 125٪ من الأصل، أي الأصل ضرب 1.25 = 500. الأصل = 500 تقسيم 1.25 = 400 ريالاً.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-10",
      prompt_ar:
        "هدف خطوات يومية لطالب كان 8000 خطوة فوصل إلى 9600. كم نسبة الزيادة؟",
      choices_ar: ["16٪", "20٪", "12٪", "25٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق على الرقم الجديد تقريباً.",
        2: "حُسب جزء من الفرق فقط.",
        3: "نسبة أكبر من الصحيح.",
      },
      solve_ar:
        "الفرق = 9600 ناقص 8000 = 1600. نقسم على الأصل: 1600 تقسيم 8000 = 0.2. إذن الزيادة 20٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-11",
      prompt_ar:
        "رصيد بطاقة مواصلات 250 ريالاً ونقص بنسبة 12٪ بعد رحلات الأسبوع. كم بقي الرصيد؟",
      choices_ar: ["220", "238", "210", "200"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "خُصم أقل من 12٪.",
        2: "خُصم أكثر من 12٪.",
        3: "خُصم 20٪ بدل 12٪.",
      },
      solve_ar:
        "بعد نقص 12٪ يبقى 88٪. نضرب: 250 ضرب 0.88 = 220. أو: 12٪ من 250 = 30، ثم 250 ناقص 30 = 220.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-12",
      prompt_ar:
        "ارتفع عدد مشتركي قناة من 250 إلى 300. كم نسبة الزيادة؟",
      choices_ar: ["16٪", "20٪", "25٪", "50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق تقريباً على العدد الجديد.",
        2: "قُسم الفرق على 200 أو حُسب زيادة 25٪.",
        3: "اُعتبر الفرق نفسه نسبة من مئة.",
      },
      solve_ar:
        "الفرق = 300 ناقص 250 = 50. نقسم على الأصل: 50 تقسيم 250 = 0.2. إذن الزيادة 20٪.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-13",
      prompt_ar:
        "انخفض عدد مشاهدات بث بنسبة 20٪ فصار 480 ألفاً. كم كان العدد قبل الانخفاض؟",
      choices_ar: ["576", "600", "560", "640"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب 480 في 1.2 بدل القسمة على 0.8.",
        2: "تقريب بلا عوامل صحيحة.",
        3: "حُسب كأن الانخفاض 25٪.",
      },
      solve_ar:
        "بعد انخفاض 20٪ يبقى 80٪ من الأصل. الأصل = 480 تقسيم 0.8 = 600 ألفاً.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-14",
      prompt_ar:
        "عدد متابعي نادٍ مدرسي انخفض من 5000 إلى 4500. كم نسبة النقص؟",
      choices_ar: ["10٪", "11٪", "5٪", "15٪"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم النقص على العدد الجديد 4500.",
        2: "حُسب نصف النسبة الصحيحة.",
        3: "نسبة أكبر من الصحيح.",
      },
      solve_ar:
        "النقص = 5000 ناقص 4500 = 500. نقسم على الأصل: 500 تقسيم 5000 = 0.1. إذن النقص 10٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-15",
      prompt_ar:
        "سعر لعبة إلكترونية زاد بنسبة 40٪ فصار 280 ريالاً. كم كان السعر قبل الزيادة؟",
      choices_ar: ["168", "200", "240", "196"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 40٪ من 280 بدل القسمة على 1.4.",
        2: "خُصم 40 ريالاً فقط تقريباً.",
        3: "حُسب 70٪ من 280.",
      },
      solve_ar:
        "بعد الزيادة السعر = الأصل ضرب 1.4 = 280. الأصل = 280 تقسيم 1.4 = 200 ريالاً.",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-16",
      prompt_ar:
        "سعر وجبة في كافتيريا المدرسة ارتفع من 90 ريالاً إلى 108. كم نسبة الزيادة؟",
      choices_ar: ["18٪", "20٪", "16٪", "12٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الفرق 18 وعدّ نسبة مباشرة.",
        2: "قُسم الفرق على السعر الجديد تقريباً.",
        3: "حُسب فرق أقل من الصحيح كنسبة.",
      },
      solve_ar:
        "الفرق = 108 ناقص 90 = 18. نقسم على الأصل: 18 تقسيم 90 = 0.2. إذن الزيادة 20٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-17",
      prompt_ar:
        "انخفض رصيد بطاقة من 625 ريالاً إلى 500. كم نسبة النقص؟",
      choices_ar: ["16٪", "20٪", "25٪", "125٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق على العدد الجديد تقريباً.",
        2: "قُسم الفرق على 500 (القسمة على الجديد).",
        3: "حُسب الناتج كنسبة معكوسة أو مطلقة بلا أساس.",
      },
      solve_ar:
        "النقص = 625 ناقص 500 = 125. نقسم على الأصل: 125 تقسيم 625 = 0.2. إذن النقص 20٪. (القسمة على 500 تعطي 25٪ خطأ شائع).",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-18",
      prompt_ar:
        "مخزون علب عصير في مقصف كان 400 علبة ونقص بنسبة 35٪. كم بقي؟",
      choices_ar: ["260", "280", "240", "365"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "خُصم 30٪ بدل 35٪.",
        2: "خُصم 40٪ بدل 35٪.",
        3: "طُرح 35 من 400 دون نسبة.",
      },
      solve_ar:
        "بعد نقص 35٪ يبقى 65٪. نضرب: 400 ضرب 0.65 = 260. أو: 35٪ من 400 = 140، ثم 400 ناقص 140 = 260.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "pc-f01",
      prompt_ar:
        "باقة إنترنت منزلية كانت 80 جيجا شهرياً ثم خُفّضت إلى 60. كم نسبة النقص؟",
      choices_ar: ["20٪", "25٪", "33٪", "15٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الفرق 20 وعدّ نسبة مباشرة.",
        2: "قُسم النقص على الكمية الجديدة 60.",
        3: "نسبة أقل من الصحيح.",
      },
      solve_ar:
        "النقص = 80 ناقص 60 = 20. نقسم على الأصل: 20 تقسيم 80 = 0.25. إذن النقص 25٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f02",
      prompt_ar:
        "اشتراك نادي رياضي شهري 160 ريالاً وزيد بنسبة 12.5٪. كم صار الاشتراك؟",
      choices_ar: ["180", "172", "200", "185"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُضيفت زيادة أقل من 12.5٪.",
        2: "هذه زيادة 25٪.",
        3: "تقريب أعلى بلا حساب دقيق.",
      },
      solve_ar:
        "زيادة 12.5٪ تعني نضرب في 1.125. 160 ضرب 1.125 = 180. أو: 12.5٪ من 160 = 20، ثم 160 زائد 20 = 180.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f03",
      prompt_ar:
        "سعر حجز ملعب بعد زيادة 10٪ أصبح 550 ريالاً. كم كان السعر قبل الزيادة؟",
      choices_ar: ["495", "500", "540", "450"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 10٪ من 550 بدل القسمة على 1.1.",
        2: "طُرح 10 ريالات فقط.",
        3: "حُسب كأن الزيادة 20٪.",
      },
      solve_ar:
        "بعد الزيادة السعر = الأصل ضرب 1.1 = 550. الأصل = 550 تقسيم 1.1 = 500 ريالاً.",
      trick_ref: "percent-change",
      difficulty: "mid",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f04",
      prompt_ar:
        "رصيد بطاقة ألعاب انخفض من 240 ريالاً إلى 180. كم نسبة النقص؟",
      choices_ar: ["25٪", "33٪", "60٪", "20٪"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم النقص على الرصيد الجديد 180.",
        2: "خُلط الفرق بالنسبة من مئة.",
        3: "نسبة أقل من الصحيح.",
      },
      solve_ar:
        "النقص = 240 ناقص 180 = 60. نقسم على الأصل: 60 تقسيم 240 = 0.25. إذن النقص 25٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f05",
      prompt_ar:
        "ارتفع سعر تذكرة قطار من 120 ريالاً إلى 150. كم نسبة الزيادة؟",
      choices_ar: ["20٪", "25٪", "30٪", "12.5٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق على السعر الجديد 150.",
        2: "حُسب فرق أكبر أو نسبة من رقم آخر.",
        3: "قُسم الفرق على ضعف الأصل تقريباً.",
      },
      solve_ar:
        "الفرق = 150 ناقص 120 = 30. نقسم على الأصل: 30 تقسيم 120 = 0.25. إذن الزيادة 25٪. (لا تقسم على 150 فتعطي 20٪).",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f06",
      prompt_ar:
        "سعر ساعة ذكية زاد بنسبة 40٪ فصار 420 ريالاً. كم كان السعر قبل الزيادة؟",
      choices_ar: ["252", "300", "380", "280"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 40٪ من 420 بدل القسمة على 1.4.",
        2: "طُرح 40 من 420.",
        3: "تقريب بلا عوامل.",
      },
      solve_ar:
        "بعد الزيادة السعر = الأصل ضرب 1.4 = 420. الأصل = 420 تقسيم 1.4 = 300 ريالاً.",
      trick_ref: "percent-change",
      difficulty: "hard",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "pc-f07",
      prompt_ar:
        "درجة طالب في اختبار تجريبي ارتفعت من 250 إلى 275. كم نسبة الزيادة؟",
      choices_ar: ["25٪", "10٪", "9٪", "15٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الفرق 25 وعدّ نسبة مباشرة.",
        2: "قُسم الفرق على الدرجة الجديدة تقريباً.",
        3: "نسبة أكبر من الصحيح.",
      },
      solve_ar:
        "الفرق = 275 ناقص 250 = 25. نقسم على الأصل: 25 تقسيم 250 = 0.1. إذن الزيادة 10٪.",
      trick_ref: "percent-change",
      difficulty: "easy",
      sub_pattern: "percent",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
