import type { Skill } from "@/lib/types";

export const ratios: Skill = {
  id: "ratios",
  title_ar: "النسب والتناسب",
  domain: "arithmetic",
  hook_ar: "اجمع الأجزاء، ثم اقسم الكمية، ثم اضرب في عدد أجزاء كل جزء",
  estimated_minutes: 5,
  icon: ":",
  visual: { kind: "custom", component: "ratio-lab" },
  intuition_ar: [
    "النسبة تعني تقسيم كمية واحدة إلى أجزاء.",
    "اجمع أعداد الأجزاء أولاً، ثم اقسم الكمية على المجموع.",
    "في التناسب: إذا تساوت النسبتان، فالضرب بالعكس يعطي نفس الناتج.",
  ],
  trick_ar: {
    statement: "لا تقسم الكمية على عدد الأشخاص فقط — اقسم على مجموع الأجزاء.",
    steps: [
      "نسبة 2:3 من 50 → الأجزاء = 2 + 3 = 5",
      "قيمة الجزء الواحد = 50 تقسيم 5 = 10",
      "الأول = 2 ضرب 10 = 20، والثاني = 3 ضرب 10 = 30",
    ],
    time_target_sec: 22,
    example_ar:
      "120 بنسبة 2:3 → الأجزاء 5 → 120 تقسيم 5 = 24 → 48 و 72.",
  },
  timing: {
    excellent_sec: 22,
    good_sec: 32,
    ok_sec: 44,
    slow_sec: 58,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "rt-01",
      prompt_ar:
        "ثلاثة أصدقاء يقتسمون 90 ريالاً بنسبة 1:2:3. كم نصيب صاحب الجزأين؟",
      choices_ar: ["15", "30", "45", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا نصيب الأصغر (جزء واحد من 6).",
        2: "هذا نصيب الأكبر (3 أجزاء).",
        3: "قُسمت الكمية على عدد الأشخاص فقط.",
      },
      solve_ar:
        "الأجزاء = 1 + 2 + 3 = 6. قيمة الجزء = 90 تقسيم 6 = 15. صاحب الجزأين يأخذ 2 ضرب 15 = 30 ريالاً.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-02",
      prompt_ar:
        "خلطة عصير: برتقال إلى ماء بنسبة 2:5. إذا كان الماء 35 كوباً، كم كوب برتقال؟",
      choices_ar: ["10", "14", "20", "7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُزء واحد حُسب خطأ.",
        2: "عُكست النسبة أو ضُوعف الناتج.",
        3: "أُخذ جزء واحد بدل جزءين.",
      },
      solve_ar:
        "الماء يمثل 5 أجزاء = 35، إذن الجزء الواحد = 35 تقسيم 5 = 7. البرتقال جزءان: 2 ضرب 7 = 14 كوباً.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-03",
      prompt_ar:
        "مدرب يقسّم 120 دقيقة تدريب على إحماء وتمارين ومباراة بنسبة 3:4:5. كم دقيقة للتمارين؟",
      choices_ar: ["30", "40", "50", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نصيب الإحماء (3 أجزاء).",
        2: "نصيب المباراة (5 أجزاء).",
        3: "قُسمت الدقائق نصفين بلا نسبة.",
      },
      solve_ar:
        "الأجزاء = 3 + 4 + 5 = 12. قيمة الجزء = 120 تقسيم 12 = 10. التمارين لها 4 أجزاء: 4 ضرب 10 = 40 دقيقة.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-04",
      prompt_ar:
        "في فصل دراسي نسبة البنين إلى البنات 5:3 والمجموع 40 طالباً. كم عدد البنات؟",
      choices_ar: ["15", "25", "20", "10"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا عدد البنين (5 أجزاء).",
        2: "نصف الصف بلا نسبة.",
        3: "حساب أجزاء ناقص.",
      },
      solve_ar:
        "الأجزاء = 5 + 3 = 8. قيمة الجزء = 40 تقسيم 8 = 5. البنات = 3 أجزاء: 3 ضرب 5 = 15 طالبة.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-05",
      prompt_ar:
        "نسبة أساسيين إلى احتياط في فريق 2:3. أُضيف 4 أساسيين فصارت النسبة 1:1. كم كان عدد الأساسيين قبل الإضافة؟",
      choices_ar: ["4", "6", "8", "12"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذ فرق الأجزاء فقط.",
        1: "حُسب الجزء دون الضرب في 2.",
        3: "ضُوعف الجواب أو خُلط بالاحتياط.",
      },
      solve_ar:
        "لنرمز: الأساسيون = 2 أجزاء، الاحتياط = 3 أجزاء. بعد إضافة 4 يصبح الأساسيون مساوين للاحتياط: 2ك + 4 = 3ك. إذن ك = 4. الأساسيون قبل الإضافة = 2 ضرب 4 = 8.",
      trick_ref: "ratios",
      difficulty: "hard",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-06",
      prompt_ar:
        "خريطة مقياسها 1:20000. مسافة على الخريطة 5 سم. كم المسافة الحقيقية بالكيلومتر؟",
      choices_ar: ["0.1", "1", "10", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "خطأ في تحويل السنتيمتر إلى كيلومتر.",
        2: "أصفار التحويل زادت عشراً.",
        3: "خُلط المتر بالكيلومتر.",
      },
      solve_ar:
        "المسافة الحقيقية = 5 ضرب 20000 = 100000 سم. نحول: 100000 سم = 1000 متر = 1 كيلومتر.",
      trick_ref: "ratios",
      difficulty: "hard",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-07",
      prompt_ar:
        "قُسّم مبلغ 150 ريالاً على ثلاثة أشخاص بنسبة 2:3:5. كم نصيب صاحب الخمسة أجزاء؟",
      choices_ar: ["30", "45", "75", "50"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نصيب الأصغر (جزءان).",
        1: "نصيب الأوسط (3 أجزاء).",
        3: "قُسم على عدد الأشخاص فقط.",
      },
      solve_ar:
        "الأجزاء = 2 + 3 + 5 = 10. قيمة الجزء = 150 تقسيم 10 = 15. صاحب الخمسة = 5 ضرب 15 = 75 ريالاً.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-08",
      prompt_ar:
        "خلط طحين وسكر بنسبة 4:1. إذا استُخدم 20 كيس طحين، كم كيساً من السكر؟",
      choices_ar: ["4", "5", "8", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ جزء واحد بدل الحساب التناسبي الصحيح.",
        2: "عُكست النسبة جزئياً.",
        3: "نُصف عدد الطحين بلا نسبة.",
      },
      solve_ar:
        "الطحين 4 أجزاء = 20، فالجزء = 20 تقسيم 4 = 5. السكر جزء واحد = 5 أكياس.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-09",
      prompt_ar:
        "نسبة نجاح إلى رسوب في مادة 7:3. إذا نجح 56 طالباً، كم عدد الراسبين؟",
      choices_ar: ["18", "24", "21", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حساب جزء خاطئ.",
        2: "قُسم 56 على نحو 2.7 تقريباً.",
        3: "نُصف عدد الناجحين.",
      },
      solve_ar:
        "النجاح 7 أجزاء = 56، فالجزء = 56 تقسيم 7 = 8. الرسوب 3 أجزاء = 3 ضرب 8 = 24.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-10",
      prompt_ar:
        "قُسّم 84 دقيقة دراسة على مراجعة وحل أسئلة بنسبة 3:4. كم دقيقة لحل الأسئلة؟",
      choices_ar: ["36", "48", "42", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نصيب المراجعة (3 أجزاء).",
        2: "نصف الزمن بلا نسبة.",
        3: "حساب أجزاء ناقص.",
      },
      solve_ar:
        "الأجزاء = 3 + 4 = 7. قيمة الجزء = 84 تقسيم 7 = 12. حل الأسئلة = 4 ضرب 12 = 48 دقيقة.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-11",
      prompt_ar:
        "نسبة أ:ب = 5:2 و ب = 18. كم قيمة أ؟",
      choices_ar: ["36", "45", "40", "50"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُوعف ب فقط.",
        2: "تقريب بلا تناسب دقيق.",
        3: "ضرب خاطئ في النسبة.",
      },
      solve_ar:
        "ب يمثل جزءين = 18، فالجزء = 18 تقسيم 2 = 9. أ = 5 أجزاء = 5 ضرب 9 = 45.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-12",
      prompt_ar:
        "ثلاثة إخوة يقتسمون 200 ريال بنسبة 1:4:5. كم نصيب الأوسط؟",
      choices_ar: ["20", "80", "100", "40"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نصيب الأصغر.",
        2: "نصيب الأكبر.",
        3: "ضعف الأصغر بلا نسبة كاملة.",
      },
      solve_ar:
        "الأجزاء = 1 + 4 + 5 = 10. قيمة الجزء = 200 تقسيم 10 = 20. الأوسط = 4 ضرب 20 = 80 ريالاً.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-13",
      prompt_ar:
        "نسبة بنين إلى بنات 3:2 والمجموع 45. كم عدد البنين؟",
      choices_ar: ["18", "27", "30", "15"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عدد البنات (جزءان).",
        2: "حساب أجزاء زائد.",
        3: "ثلث المجموع بلا نسبة.",
      },
      solve_ar:
        "الأجزاء = 3 + 2 = 5. قيمة الجزء = 45 تقسيم 5 = 9. البنين = 3 ضرب 9 = 27.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-14",
      prompt_ar:
        "مقياس رسم 1:100. طول غرفة على المخطط 8 سم. كم طولها الحقيقي بالمتر؟",
      choices_ar: ["0.8", "8", "80", "0.08"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي تحويل صحيح للوحدات.",
        2: "أصفار زائدة.",
        3: "خطأ عشري كبير.",
      },
      solve_ar:
        "الطول الحقيقي = 8 ضرب 100 = 800 سم = 8 أمتار.",
      trick_ref: "ratios",
      difficulty: "hard",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-15",
      prompt_ar:
        "نسبة س:ص كانت 2:5. زيدت س بمقدار 6 فصارت النسبة 4:5. كم كانت س قبل الزيادة؟",
      choices_ar: ["4", "6", "8", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ فرق الأجزاء فقط.",
        2: "حُسب الجزء ثم ضُرب خطأ.",
        3: "خلط مع قيمة ص.",
      },
      solve_ar:
        "قبل الزيادة: س = 2ك و ص = 5ك. بعد زيادة 6: 2ك + 6 على 5ك = 4 على 5. إذن 2ك + 6 = 4ك، فـ ك = 3. س قبل الزيادة = 2 ضرب 3 = 6. تحقق: ص = 15، وبعدها 12:15 = 4:5.",
      trick_ref: "ratios",
      difficulty: "hard",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-16",
      prompt_ar:
        "قُسّم 360 ريالاً بنسبة 1:2:3:6. كم نصيب صاحب الستة أجزاء؟",
      choices_ar: ["30", "60", "90", "180"],
      correct_index: 3,
      trap_explanations_ar: {
        0: "جزء واحد.",
        1: "جزءان.",
        2: "ثلاثة أجزاء.",
      },
      solve_ar:
        "الأجزاء = 1 + 2 + 3 + 6 = 12. قيمة الجزء = 360 تقسيم 12 = 30. نصيب الستة = 6 ضرب 30 = 180.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-17",
      prompt_ar:
        "إذا كان 3:8 = س:40، فما قيمة س؟",
      choices_ar: ["12", "15", "18", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في 4 بدل 5.",
        2: "تقريب أعلى.",
        3: "ضرب ناقص.",
      },
      solve_ar:
        "من 8 إلى 40 نضرب في 5. إذن س = 3 ضرب 5 = 15. أو: س = 3 ضرب 40 تقسيم 8 = 15.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-18",
      prompt_ar:
        "مزيج قهوة وحليب بنسبة 5:3 حجمه 64 مل. كم مل من القهوة؟",
      choices_ar: ["24", "40", "32", "48"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نصيب الحليب.",
        2: "نصف المزيج.",
        3: "أجزاء زائدة.",
      },
      solve_ar:
        "الأجزاء = 5 + 3 = 8. قيمة الجزء = 64 تقسيم 8 = 8. القهوة = 5 ضرب 8 = 40 مل.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "rt-f01",
      prompt_ar:
        "قُسّم 45 ريالاً بنسبة 2:7. كم نصيب الأكبر؟",
      choices_ar: ["10", "35", "30", "25"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نصيب الأصغر.",
        2: "تقريب بلا أجزاء صحيحة.",
        3: "حساب ناقص.",
      },
      solve_ar:
        "الأجزاء = 2 + 7 = 9. الجزء = 45 تقسيم 9 = 5. الأكبر = 7 ضرب 5 = 35.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f02",
      prompt_ar:
        "نسبة لاعبين أساسيين إلى بدلاء 5:3. إذا كان البدلاء 12، كم الأساسيون؟",
      choices_ar: ["15", "20", "18", "24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جزء ناقص.",
        2: "تقريب.",
        3: "ضُوعف البدلاء.",
      },
      solve_ar:
        "البدلاء 3 أجزاء = 12، فالجزء = 4. الأساسيون = 5 ضرب 4 = 20.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f03",
      prompt_ar:
        "قُسّم 96 بنسبة 1:2:5. كم نصيب الأوسط؟",
      choices_ar: ["12", "24", "60", "32"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "الأصغر.",
        2: "الأكبر.",
        3: "ثلث تقريبي.",
      },
      solve_ar:
        "الأجزاء = 8. الجزء = 12. الأوسط = 2 ضرب 12 = 24.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f04",
      prompt_ar:
        "خريطة 1:25000 ومسافة عليها 2 سم. المسافة الحقيقية بالكم؟",
      choices_ar: ["0.5", "5", "0.05", "50"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أصفار التحويل زادت.",
        2: "خطأ عشري.",
        3: "خلط كبير بالوحدات.",
      },
      solve_ar:
        "2 ضرب 25000 = 50000 سم = 500 م = 0.5 كم.",
      trick_ref: "ratios",
      difficulty: "hard",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f05",
      prompt_ar:
        "نسبة 4:9 ومجموعهما 65. كم الأصغر؟",
      choices_ar: ["20", "45", "25", "16"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "الأكبر.",
        2: "تقريب.",
        3: "أجزاء خاطئة.",
      },
      solve_ar:
        "الأجزاء = 13. الجزء = 5. الأصغر = 4 ضرب 5 = 20.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f06",
      prompt_ar:
        "إذا كان 5/8 = س/32، فما س؟",
      choices_ar: ["16", "20", "24", "18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في 3.2 تقريباً خطأ.",
        2: "ضُوعف البسط خطأ.",
        3: "تقريب.",
      },
      solve_ar:
        "من 8 إلى 32 نضرب في 4. س = 5 ضرب 4 = 20.",
      trick_ref: "ratios",
      difficulty: "easy",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "rt-f07",
      prompt_ar:
        "نسبة ماء إلى عصير 3:1 في مشروب حجمه 48 مل. كم مل عصير؟",
      choices_ar: ["12", "16", "36", "24"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ثلث الحجم تقريباً بلا أجزاء.",
        2: "نصيب الماء.",
        3: "نصف المشروب.",
      },
      solve_ar:
        "الأجزاء = 4. الجزء = 12. العصير جزء واحد = 12 مل.",
      trick_ref: "ratios",
      difficulty: "mid",
      sub_pattern: "ratio",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
