import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const roots: Skill = {
  id: "roots",
  title_ar: "الجذور والتقدير",
  domain: "arithmetic",
  hook_ar: "اربط الجذر بالمربعات الكاملة، ثم قدّر أو قارن دون آلة",
  estimated_minutes: 7,
  icon: "√",
  visual: { kind: "custom", component: "roots-lab" },
  intuition_ar: [
    "المربع الكامل عدد ينتج من ضرب عدد صحيح في نفسه، مثل 49 = 7×7.",
    "إن لم يكن العدد مربعاً كاملاً، فجذره يقع بين جذرين صحيحين متتاليين.",
    "لمقارنة جذرين موجبين: قارن ما تحت الجذر. ولمقارنة جذر بعدد صحيح: ربّع العدد الصحيح.",
  ],
  trick_ar: {
    statement: "ارجع دائماً إلى أقرب مربعات كاملة قبل الحساب.",
    steps: [
      "احفظ المربعات: 1، 4، 9، 16، 25، 36، 49، 64، 81، 100…",
      "للتقدير: جد مربعين يحصران العدد، فالجذر بين جذريهما",
      "للتبسيط الخفيف: √(أ² × ب) = أ√ب، وللمقارنة: ربّع الطرف الصحيح أو قارن ما تحت الجذر",
    ],
    time_target_sec: 22,
    example_ar:
      "√50 بين 7 و 8 لأن 7² = 49 و 8² = 64. و√(36×2) = 6√2.",
  },
  timing: {
    excellent_sec: 22,
    good_sec: 32,
    ok_sec: 42,
    slow_sec: 55,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ro-01",
      prompt_ar:
        "رُسم مربع أرض مساحته 81 متراً مربعاً. كم طول ضلعه بالمتر؟",
      choices_ar: ["7", "8", "9", "10"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اُستخدم 7² = 49 بدلاً من 81.",
        1: "اُستخدم 8² = 64 بدلاً من 81.",
        3: "اُستخدم 10² = 100 وهو أكبر من المساحة.",
      },
      solve_ar: "المطلوب √81. وبما أن 9×9 = 81، فطول الضلع 9 أمتار.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-02",
      prompt_ar:
        "يحتاج ملصق مربّع إلى 144 مربعاً صغيراً لملء مساحته. كم مربعاً على طول ضلع واحد؟",
      choices_ar: ["10", "11", "12", "14"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اُستخدم 10² = 100.",
        1: "اُستخدم 11² = 121.",
        3: "اُستخدم 14² = 196 وهو أكبر.",
      },
      solve_ar: "المطلوب √144. وبما أن 12×12 = 144، فالجانب يضم 12 مربعاً.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-03",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √50؟",
      choices_ar: ["6 و 7", "7 و 8", "8 و 9", "9 و 10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "6² = 36 أصغر بكثير من 50.",
        2: "8² = 64 أكبر من 50، فالجذر أصغر من 8 وليس بين 8 و 9.",
        3: "9² = 81 بعيد عن 50.",
      },
      solve_ar:
        "7² = 49 و 8² = 64. وبما أن 49 < 50 < 64، فإن √50 بين 7 و 8.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-04",
      prompt_ar: "أي القيمتين أكبر: √40 أم √36؟",
      choices_ar: ["√36", "√40", "متساويتان", "لا يمكن المقارنة"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "√36 = 6، لكن √40 أكبر لأن 40 > 36.",
        2: "الجذران مختلفان لأن ما تحتهما مختلف.",
        3: "المقارنة ممكنة بمقارنة ما تحت الجذر.",
      },
      solve_ar:
        "الجذران موجبان. بما أن 40 > 36 فإن √40 > √36. ويمكن التحقق: √36 = 6 و 6² = 36 < 40.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-05",
      prompt_ar: "بسّط √(9×5) بأبسط صورة.",
      choices_ar: ["9√5", "3√5", "√40", "5√3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخرج 9 نفسها بدل جذرها.",
        2: "قُرّب الناتج دون إخراج المربع الكامل 9.",
        3: "عُكست العوامل تحت الجذر.",
      },
      solve_ar:
        "√(9×5) = √(3²×5) = 3√5. هذا تبسيط خفيف بإخراج المربع الكامل.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-06",
      prompt_ar:
        "لوحة مربعة مساحتها 121 وحدة مربعة. ما طول ضلعها؟",
      choices_ar: ["9", "10", "11", "12"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "9² = 81 وليس 121.",
        1: "10² = 100 وليس 121.",
        3: "12² = 144 أكبر من 121.",
      },
      solve_ar: "المطلوب √121. وبما أن 11×11 = 121، فطول الضلع 11.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-07",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √30؟",
      choices_ar: ["4 و 5", "5 و 6", "6 و 7", "7 و 8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "4² = 16 أصغر من 30، لكن 5² = 25 أيضاً أصغر، فالجذر أكبر من 5.",
        2: "6² = 36 أكبر من 30، فالجذر أصغر من 6 وليس بين 6 و 7.",
        3: "7² = 49 بعيد عن 30.",
      },
      solve_ar:
        "5² = 25 و 6² = 36. وبما أن 25 < 30 < 36، فإن √30 بين 5 و 6.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-08",
      prompt_ar: "أي العبارتين صحيحة؟",
      choices_ar: [
        "√8 > 3",
        "√8 = 3",
        "√8 < 3",
        "√8 = 4",
      ],
      correct_index: 2,
      trap_explanations_ar: {
        0: "3² = 9 أكبر من 8، فالجذر أصغر من 3.",
        1: "√8 لا يساوي 3 لأن 3² = 9 ≠ 8.",
        3: "4² = 16 أكبر بكثير من 8.",
      },
      solve_ar:
        "نربّع العدد الصحيح: 3² = 9. وبما أن 8 < 9 فإن √8 < 3.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-09",
      prompt_ar: "بسّط √(16×3).",
      choices_ar: ["16√3", "4√3", "√36", "8√3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخرج 16 بدل جذرها.",
        2: "تُرك الجذر بلا تبسيط.",
        3: "اُستخدم نصف 16 خطأً.",
      },
      solve_ar: "√(16×3) = √(4²×3) = 4√3.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-10",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √200؟",
      choices_ar: ["13 و 14", "14 و 15", "15 و 16", "12 و 13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "13² = 169 أصغر من 200، لكن 14² = 196 أيضاً أصغر، فالجذر أكبر من 14.",
        2: "15² = 225 أكبر من 200، فالجذر أصغر من 15 وليس بين 15 و 16.",
        3: "12² = 144 بعيد نسبياً عن 200.",
      },
      solve_ar:
        "14² = 196 و 15² = 225. وبما أن 196 < 200 < 225، فإن √200 بين 14 و 15.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-11",
      prompt_ar: "أي القيمتين أصغر: √20 أم √24؟",
      choices_ar: ["√20", "√24", "متساويتان", "لا يمكن الجزم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "√24 أكبر لأن 24 > 20.",
        2: "ما تحت الجذر مختلف، فالقيمتان مختلفتان.",
        3: "المقارنة مباشرة بمقارنة 20 و 24.",
      },
      solve_ar:
        "بما أن 20 < 24 وكلا الجذرين موجبان، فإن √20 < √24. إذن الأصغر هو √20.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-12",
      prompt_ar:
        "صندوق مربّع القاعدة مساحته 64 سم². كم طول ضلع القاعدة؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "6² = 36.",
        1: "7² = 49.",
        3: "9² = 81.",
      },
      solve_ar: "المطلوب √64. وبما أن 8×8 = 64، فطول الضلع 8 سم.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-13",
      prompt_ar: "بسّط √72 بأبسط صورة.",
      choices_ar: ["6√2", "8√2", "36√2", "9√8"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "اُستخدم عامل مربع غير أكبر، أو قُسّم خطأً.",
        2: "أُخرج 36 بدل جذرها.",
        3: "تُرك عامل غير مبسّط تحت الجذر.",
      },
      solve_ar:
        "72 = 36×2 و 36 مربع كامل. إذن √72 = √(36×2) = 6√2.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-14",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √75؟",
      choices_ar: ["7 و 8", "8 و 9", "9 و 10", "6 و 7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "7² = 49 أصغر، و 8² = 64 أيضاً أصغر من 75، فالجذر أكبر من 8.",
        2: "9² = 81 أكبر من 75، فالجذر أصغر من 9.",
        3: "6² = 36 بعيد عن 75.",
      },
      solve_ar:
        "8² = 64 و 9² = 81. وبما أن 64 < 75 < 81، فإن √75 بين 8 و 9.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-15",
      prompt_ar: "أي أكبر: √45 أم √50؟",
      choices_ar: ["√45", "√50", "متساويتان", "√45 = 50"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "√45 أصغر لأن 45 < 50.",
        2: "العددان مختلفان تحت الجذر.",
        3: "لا معنى لجعل الجذر يساوي العدد الآخر هكذا.",
      },
      solve_ar: "بما أن 50 > 45 فإن √50 > √45.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-16",
      prompt_ar: "بسّط √(25×7).",
      choices_ar: ["25√7", "5√7", "√70", "7√5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخرج 25 بدل جذرها.",
        2: "ضُرب دون إخراج المربع الكامل.",
        3: "عُكست العوامل.",
      },
      solve_ar: "√(25×7) = √(5²×7) = 5√7.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-17",
      prompt_ar:
        "قارن √90 و 10 دون آلة حاسبة. أي عبارة صحيحة؟",
      choices_ar: [
        "√90 > 10",
        "√90 = 10",
        "√90 < 10",
        "√90 = 9",
      ],
      correct_index: 2,
      trap_explanations_ar: {
        0: "10² = 100 أكبر من 90، فالجذر أصغر من 10.",
        1: "√100 = 10 وليس √90.",
        3: "9² = 81، و √90 أكبر من 9 لكنه أصغر من 10.",
      },
      solve_ar:
        "نربّع 10: 10² = 100. وبما أن 90 < 100 فإن √90 < 10. وهو أيضاً أكبر من 9 لأن 81 < 90.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-18",
      prompt_ar:
        "أي القيم التالية يساوي √(49×2) بعد التبسيط؟",
      choices_ar: ["49√2", "7√2", "√50", "14√2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخرج 49 بدل جذرها.",
        2: "تُرك الناتج بلا تبسيط.",
        3: "ضُرب الجذر في 2 خطأً.",
      },
      solve_ar: "√(49×2) = √(7²×2) = 7√2.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ro-f01",
      prompt_ar:
        "حديقة مربعة مساحتها 169 متراً مربعاً. كم طول ضلعها؟",
      choices_ar: ["11", "12", "13", "14"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "11² = 121.",
        1: "12² = 144.",
        3: "14² = 196.",
      },
      solve_ar: "المطلوب √169. وبما أن 13×13 = 169، فطول الضلع 13 متراً.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f02",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √110؟",
      choices_ar: ["9 و 10", "10 و 11", "11 و 12", "8 و 9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "9² = 81 أصغر، و 10² = 100 أيضاً أصغر من 110.",
        2: "11² = 121 أكبر من 110، فالجذر أصغر من 11.",
        3: "8² = 64 بعيد عن 110.",
      },
      solve_ar:
        "10² = 100 و 11² = 121. وبما أن 100 < 110 < 121، فإن √110 بين 10 و 11.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f03",
      prompt_ar: "بسّط √(36×5).",
      choices_ar: ["36√5", "6√5", "√90", "18√5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخرج 36 بدل جذرها.",
        2: "قُرّب دون إخراج المربع الكامل 36.",
        3: "اُستخدم نصف 36 خطأً.",
      },
      solve_ar: "√(36×5) = √(6²×5) = 6√5.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f04",
      prompt_ar: "أي أكبر: √60 أم 8؟",
      choices_ar: ["√60", "8", "متساويتان", "لا يمكن المقارنة"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "8² = 64 أكبر من 60، فـ √60 أصغر من 8.",
        2: "√64 = 8 وليس √60.",
        3: "المقارنة ممكنة بتربيع 8.",
      },
      solve_ar: "8² = 64. وبما أن 60 < 64 فإن √60 < 8. إذن الأكبر هو 8.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f05",
      prompt_ar: "بسّط √48 بأبسط صورة.",
      choices_ar: ["4√3", "16√3", "2√3", "8√3"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخرج 16 بدل جذرها.",
        2: "أُخرج √4 فقط دون إكمال التبسيط إلى 4√3.",
        3: "اُستخدم عاملاً مربعاً أكبر مما في 48.",
      },
      solve_ar:
        "48 = 16×3 و 16 مربع كامل. إذن √48 = √(16×3) = 4√3.",
      trick_ref: "roots",
      difficulty: "mid",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f06",
      prompt_ar:
        "أي القيمتين أكبر: √18 أم √12؟",
      choices_ar: ["√12", "√18", "متساويتان", "√12 = 18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "√12 أصغر لأن 12 < 18.",
        2: "ما تحت الجذر مختلف.",
        3: "لا معنى لهذه المساواة.",
      },
      solve_ar: "بما أن 18 > 12 فإن √18 > √12.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
    {
      id: "ro-f07",
      prompt_ar:
        "بين أي عددين صحيحين متتاليين يقع √2؟",
      choices_ar: ["0 و 1", "1 و 2", "2 و 3", "3 و 4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "1² = 1 أصغر من 2، فالجذر أكبر من 1.",
        2: "2² = 4 أكبر من 2، فالجذر أصغر من 2.",
        3: "3² = 9 بعيد عن 2.",
      },
      solve_ar:
        "1² = 1 و 2² = 4. وبما أن 1 < 2 < 4، فإن √2 بين 1 و 2.",
      trick_ref: "roots",
      difficulty: "easy",
      sub_pattern: "number_sense",
      ...review,
    },
  ],
};
