import type { Skill } from "@/lib/types";

export const successivePercent: Skill = {
  id: "successive-percent",
  title_ar: "النسب المتتالية",
  domain: "arithmetic",
  hook_ar: "زيادة ثم نقص بنفس النسبة لا يلغيان — اضرب العوامل واحداً واحداً",
  estimated_minutes: 5,
  icon: "⇄",
  visual: { kind: "custom", component: "successive-lab" },
  intuition_ar: [
    "كل نسبة تُطبَّق على الناتج السابق، لا على الرقم الأصلي دائماً.",
    "الطريقة الصحيحة: اضرب عوامل التغيّر (1 + النسبة) أو (1 − النسبة).",
    "حتى لو تساوت الزيادة والنقص، الناتج لا يرجع للأصل.",
  ],
  trick_ar: {
    statement: "لا تجمع النسب المتتالية ولا تطرحها — اضرب عواملها.",
    steps: [
      "زيادة 20٪ ثم نقص 20٪ = ضرب 1.2 ثم ضرب 0.8",
      "1.2 ضرب 0.8 = 0.96 أي نقص 4٪ عن الأصل",
    ],
    time_target_sec: 26,
    example_ar:
      "100 → زيادة 20٪ = 120 → نقص 20٪ = 96. الصافي نقص 4٪.",
  },
  timing: {
    excellent_sec: 26,
    good_sec: 36,
    ok_sec: 48,
    slow_sec: 63,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "sp-01",
      prompt_ar:
        "عدد متابعي حساب زاد 20٪ ثم زاد 20٪ مرة أخرى. كم الزيادة الصافية عن البداية؟",
      choices_ar: ["40٪", "44٪", "36٪", "42٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت النسب 20 + 20 — المصيدة الأشهر.",
        2: "ظُنّ وجود نقص مركّب.",
        3: "تقريب قريب من الصحيح بلا ضرب العوامل.",
      },
      solve_ar:
        "الزيادة الأولى عاملها 1.2، والثانية 1.2. نضرب: 1.2 ضرب 1.2 = 1.44. يعني العدد صار 144٪ من أصله، فالزيادة الصافية 44٪ (وليست 40٪).",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-02",
      prompt_ar:
        "سعر جوال زاد 25٪ في عرض، ثم نزل 20٪ في تخفيض. ماذا حصل للسعر مقارنة بالأصل؟",
      choices_ar: ["زاد 5٪", "بقي كما هو", "نقص 5٪", "زاد 25٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرحت النسب 25 − 20.",
        2: "خُلط الترتيب أو إشارة الصافي.",
        3: "نُظر للزيادة الأولى فقط.",
      },
      solve_ar:
        "عامل الزيادة 1.25، وعامل النقص 0.8. نضرب: 1.25 ضرب 0.8 = 1. الناتج = الأصل تماماً، أي بقي السعر كما هو. (لا تجمع ولا تطرح النسب).",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-03",
      prompt_ar:
        "راتب موظف نقص 10٪ بسبب غياب، ثم زاد 10٪ بعد تعويض. بالنسبة للأصل صار الراتب؟",
      choices_ar: ["نفسه", "أقل بنسبة 1٪", "أكثر بنسبة 1٪", "أقل بنسبة 10٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "إلغاء وهمي لنسبتين متساويتين في الاتجاهين.",
        2: "اتجاه الصافي معكوس.",
        3: "حُسب النقص الأول فقط.",
      },
      solve_ar:
        "عامل النقص 0.9، ثم عامل الزيادة 1.1. نضرب: 0.9 ضرب 1.1 = 0.99. أي بقي 99٪ من الأصل، فهو أقل بنسبة 1٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-04",
      prompt_ar:
        "سعر تذكرة بعد زيادتين متتاليتين 10٪ ثم 20٪ أصبح 264 ريالاً. كم كان السعر الأصلي؟",
      choices_ar: ["200", "220", "210", "240"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على 1.2 فقط.",
        2: "تقريب بلا ضرب العاملين معاً.",
        3: "قُسم على 1.1 فقط.",
      },
      solve_ar:
        "الأصل ضرب 1.1 ضرب 1.2 = 264. أولاً 1.1 ضرب 1.2 = 1.32. ثم الأصل = 264 تقسيم 1.32 = 200 ريالاً.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-05",
      prompt_ar:
        "سلعة زيد سعرها 50٪ ثم خُصمت 40٪. التغيّر الصافي عن السعر الأول؟",
      choices_ar: ["زيادة 10٪", "نقص 10٪", "بدون تغيّر", "زيادة 20٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرحت النسب 50 − 40 — المصيدة الشائعة.",
        2: "إلغاء وهمي.",
        3: "طرح النسب مع تضخيم.",
      },
      solve_ar:
        "عامل الزيادة 1.5، وعامل الخصم 0.6 (لأن 100٪ − 40٪ = 60٪). نضرب: 1.5 ضرب 0.6 = 0.9. يعني بقي 90٪ من الأصل، فالصافي نقص 10٪.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-06",
      prompt_ar:
        "زيد سعر كتاب 25٪، ثم خُصم بنسبة ما فرجع لنفس السعر الأول. كم نسبة الخصم؟",
      choices_ar: ["25٪", "20٪", "22٪", "15٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ أن الخصم يساوي الزيادة دائماً.",
        2: "تقريب غير ناتج من القسمة على 1.25.",
        3: "تقدير أقل من المطلوب.",
      },
      solve_ar:
        "بعد الزيادة العامل 1.25. نريد: 1.25 ضرب (1 ناقص نسبة الخصم) = 1. إذن 1 ناقص نسبة الخصم = 1 تقسيم 1.25 = 0.8. نسبة الخصم = 0.2 أي 20٪. (ليست 25٪).",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-07",
      prompt_ar:
        "سعر وجبة زاد 15٪ ثم زاد 15٪ مرة أخرى. الزيادة الصافية تقريباً؟",
      choices_ar: ["30٪", "32.25٪", "22.5٪", "15٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت النسب مباشرة.",
        2: "متوسط النسب تقريباً.",
        3: "نُظرت الزيادة الأولى فقط.",
      },
      solve_ar:
        "1.15 ضرب 1.15 = 1.3225. أي زيادة صافية نحو 32.25٪ وليس 30٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-08",
      prompt_ar:
        "عدد مشاهدات فيديو نقص 20٪ ثم زاد 25٪. التغيّر الصافي؟",
      choices_ar: ["زيادة 5٪", "بدون تغيّر", "نقص 5٪", "زيادة 45٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرحت النسب.",
        2: "اتجاه خاطئ.",
        3: "جُمعت القيم المطلقة.",
      },
      solve_ar:
        "0.8 ضرب 1.25 = 1. الناتج يساوي الأصل — بدون تغيّر.",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-09",
      prompt_ar:
        "رصيد محفظة زاد 30٪ ثم نقص 10٪. التغيّر الصافي؟",
      choices_ar: ["زيادة 20٪", "زيادة 17٪", "نقص 20٪", "زيادة 27٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرحت النسب 30 − 10.",
        2: "اتجاه معكوس.",
        3: "تقريب قريب من الضرب بلا دقة.",
      },
      solve_ar:
        "1.3 ضرب 0.9 = 1.17. أي زيادة صافية 17٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-10",
      prompt_ar:
        "سعر بعد خصمين 20٪ ثم 10٪ أصبح 720. كم السعر قبل الخصمين؟",
      choices_ar: ["900", "1000", "950", "880"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على 0.8 فقط.",
        2: "جُمع الخصمان 30٪.",
        3: "تقريب بلا عوامل.",
      },
      solve_ar:
        "العامل = 0.8 ضرب 0.9 = 0.72. الأصل = 720 تقسيم 0.72 = 1000.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-11",
      prompt_ar:
        "عدد زاد 5٪ ثم 5٪. الزيادة الصافية؟",
      choices_ar: ["10٪", "10.25٪", "9.75٪", "11٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جمع مباشر.",
        2: "اتجاه خاطئ.",
        3: "مبالغة.",
      },
      solve_ar:
        "1.05 ضرب 1.05 = 1.1025. زيادة صافية 10.25٪.",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-12",
      prompt_ar:
        "سلعة نقصت 25٪ ثم زيدت 20٪. التغيّر الصافي؟",
      choices_ar: ["نقص 5٪", "بدون تغيّر", "نقص 10٪", "زيادة 5٪"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "طرح مباشر 25 − 20.",
        1: "إلغاء وهمي.",
        3: "اتجاه معكوس.",
      },
      solve_ar:
        "0.75 ضرب 1.2 = 0.9. أي نقص 10٪ عن الأصل.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-13",
      prompt_ar:
        "بعد زيادة 20٪ ثم زيادة 25٪ صار العدد 150. ما الأصل؟",
      choices_ar: ["100", "110", "120", "90"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على عامل واحد تقريباً.",
        2: "قُسم على 1.25 فقط.",
        3: "تقريب أقل.",
      },
      solve_ar:
        "1.2 ضرب 1.25 = 1.5. الأصل = 150 تقسيم 1.5 = 100.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-14",
      prompt_ar:
        "أي ترتيب يعطي نفس الناتج: +10٪ ثم −20٪، أو −20٪ ثم +10٪؟",
      choices_ar: ["الأول أكبر", "الثاني أكبر", "متساويان", "يعتمد على العدد"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "الضرب تبديلي هنا.",
        1: "نفس الناتج.",
        3: "لا يعتمد على قيمة البداية.",
      },
      solve_ar:
        "1.1 ضرب 0.8 = 0.8 ضرب 1.1 = 0.88. الترتيبان متساويان.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-15",
      prompt_ar:
        "سعر زاد 40٪ ثم خُصم بنسبة ما ليرجع للأصل. نسبة الخصم؟",
      choices_ar: ["40٪", "28.6٪", "30٪", "35٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ تساوي الزيادة والخصم.",
        2: "تقريب خشن.",
        3: "تقريب آخر.",
      },
      solve_ar:
        "1.4 ضرب (1 − س) = 1. إذن 1 − س = 1 تقسيم 1.4 نحو 0.714. س نحو 28.6٪.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-16",
      prompt_ar:
        "راتب نقص 5٪ ثم نقص 5٪ أخرى. النقص الصافي تقريباً؟",
      choices_ar: ["10٪", "9.75٪", "10.25٪", "5٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جمع النقصين.",
        2: "خُلط مع زيادة مركّبة.",
        3: "نقص واحد فقط.",
      },
      solve_ar:
        "0.95 ضرب 0.95 = 0.9025. بقي نحو 90.25٪، فالنقص الصافي نحو 9.75٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-17",
      prompt_ar:
        "عدد من 200: زاد 10٪ ثم نقص 10٪. الناتج؟",
      choices_ar: ["200", "198", "202", "180"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "إلغاء وهمي.",
        2: "اتجاه معكوس.",
        3: "نُظر للنقص فقط تقريباً.",
      },
      solve_ar:
        "200 ضرب 1.1 = 220، ثم 220 ضرب 0.9 = 198. أو 200 ضرب 0.99 = 198.",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-18",
      prompt_ar:
        "زيادة 20٪ ثم زيادة 30٪. الزيادة الصافية؟",
      choices_ar: ["50٪", "56٪", "54٪", "60٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جمع مباشر.",
        2: "تقريب قريب.",
        3: "مبالغة.",
      },
      solve_ar:
        "1.2 ضرب 1.3 = 1.56. زيادة صافية 56٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "sp-f01",
      prompt_ar:
        "سعر زاد 10٪ ثم نقص 20٪. التغيّر الصافي؟",
      choices_ar: ["نقص 10٪", "نقص 12٪", "بدون تغيّر", "زيادة 10٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طرح مباشر.",
        2: "إلغاء وهمي.",
        3: "نُظرت الزيادة فقط.",
      },
      solve_ar:
        "1.1 ضرب 0.8 = 0.88. نقص 12٪.",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f02",
      prompt_ar:
        "عدد زاد 25٪ مرتين متتاليتين. الزيادة الصافية؟",
      choices_ar: ["50٪", "56.25٪", "62.5٪", "45٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جمع مباشر.",
        2: "حساب خاطئ للعوامل.",
        3: "تقريب أقل.",
      },
      solve_ar:
        "1.25 ضرب 1.25 = 1.5625. زيادة 56.25٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f03",
      prompt_ar:
        "بعد نقص 20٪ ثم زيادة 50٪ صار السعر 480. الأصل؟",
      choices_ar: ["400", "360", "420", "320"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على عامل واحد.",
        2: "تقريب.",
        3: "قُسم على 1.5 فقط.",
      },
      solve_ar:
        "0.8 ضرب 1.5 = 1.2. الأصل = 480 تقسيم 1.2 = 400.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f04",
      prompt_ar:
        "زيادة 8٪ ثم نقص 8٪. التغيّر الصافي؟",
      choices_ar: ["بدون تغيّر", "نقص 0.64٪", "زيادة 0.64٪", "نقص 8٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "إلغاء وهمي.",
        2: "اتجاه معكوس.",
        3: "النقص الأول فقط.",
      },
      solve_ar:
        "1.08 ضرب 0.92 = 0.9936. نقص نحو 0.64٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f05",
      prompt_ar:
        "سلعة زيدت 60٪ ثم خُصمت لتعود للأصل. نسبة الخصم؟",
      choices_ar: ["60٪", "37.5٪", "40٪", "50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "تساوي وهمي.",
        2: "تقريب.",
        3: "نصف تقريباً بلا قسمة.",
      },
      solve_ar:
        "1.6 ضرب (1 − س) = 1. 1 − س = 1 تقسيم 1.6 = 0.625. س = 0.375 أي 37.5٪.",
      trick_ref: "successive-percent",
      difficulty: "hard",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f06",
      prompt_ar:
        "من 100: زيادة 50٪ ثم نقص 50٪. الناتج؟",
      choices_ar: ["100", "75", "50", "125"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "إلغاء وهمي.",
        2: "نُظر للنقص على الأصل فقط.",
        3: "الزيادة فقط.",
      },
      solve_ar:
        "100 ضرب 1.5 = 150، ثم 150 ضرب 0.5 = 75.",
      trick_ref: "successive-percent",
      difficulty: "easy",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "sp-f07",
      prompt_ar:
        "زيادة 12٪ ثم زيادة 12٪. الزيادة الصافية تقريباً؟",
      choices_ar: ["24٪", "25.44٪", "22٪", "26٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جمع مباشر.",
        2: "تقريب أقل.",
        3: "تقريب أعلى.",
      },
      solve_ar:
        "1.12 ضرب 1.12 = 1.2544. زيادة نحو 25.44٪.",
      trick_ref: "successive-percent",
      difficulty: "mid",
      sub_pattern: "successive",
      source: "style-modeled-practice-2024",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
