import type { Skill } from "@/lib/types";

export const workRate: Skill = {
  id: "work-rate",
  title_ar: "العمل والإنجاز",
  domain: "arithmetic",
  hook_ar: "ثبّت يوم-عامل: زيادة العمال تقلّل الأيام",
  estimated_minutes: 7,
  icon: "⚒",
  visual: { kind: "custom", component: "work-rate-lab" },
  intuition_ar: [
    "العمل الكامل ثابت، لذلك عدد العمال ضرب عدد الأيام يبقى ثابتاً.",
    "إذا زاد العمال الذين يعملون بالمعدل نفسه، قلّت الأيام اللازمة.",
    "في العمل المشترك نجمع الجزء الذي ينجزه كل شخص في يوم واحد.",
  ],
  trick_ar: {
    statement: "احسب يوم-عامل أولاً، ثم اقسمه على عدد العمال الجديد.",
    steps: [
      "العمل الكامل = عدد العمال ضرب عدد الأيام",
      "الأيام الجديدة = العمل الكامل تقسيم عدد العمال الجديد",
      "لشخصين: اجمع ما ينجزه كل واحد في يوم واحد",
    ],
    time_target_sec: 23,
    example_ar:
      "6 عمال ينجزون عملاً في 8 أيام: العمل = 6 ضرب 8 = 48 يوم-عامل. مع 12 عاملاً: 48 تقسيم 12 = 4 أيام.",
  },
  timing: {
    excellent_sec: 23,
    good_sec: 33,
    ok_sec: 45,
    slow_sec: 60,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "wr-01",
      prompt_ar: "ينجز 4 عمال طلاء سور في 6 أيام. كم يوماً يحتاج 8 عمال بالمعدل نفسه؟",
      choices_ar: ["2", "3", "8", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت الأيام على عدد غير صحيح.",
        2: "عُدّ عدد العمال أياماً.",
        3: "زِيدت الأيام مع زيادة العمال.",
      },
      solve_ar:
        "العمل = 4 عمال ضرب 6 أيام = 24 يوم-عامل. الأيام مع 8 عمال = 24 تقسيم 8 = 3 أيام.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-02",
      prompt_ar: "يعبّئ 6 عمال طلبية في 10 أيام. إذا عمل 12 عاملاً بالمعدل نفسه، فكم يوماً يحتاجون؟",
      choices_ar: ["4", "5", "10", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نقص يوم من الناتج الصحيح.",
        2: "لم تُراعَ مضاعفة عدد العمال.",
        3: "ضُوعفت الأيام بدلاً من تنصيفها.",
      },
      solve_ar:
        "العمل = 6 ضرب 10 = 60 يوم-عامل. الأيام الجديدة = 60 تقسيم 12 = 5 أيام.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-03",
      prompt_ar: "يرتّب 9 عمال مستودعاً في 8 أيام. كم يوماً يحتاج 6 عمال للعمل نفسه؟",
      choices_ar: ["6", "10", "12", "14"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُقصت الأيام مع نقص العمال.",
        1: "حُسب الفرق بين عددي العمال فقط.",
        3: "زِيدت الأيام دون تثبيت العمل.",
      },
      solve_ar:
        "العمل = 9 ضرب 8 = 72 يوم-عامل. الأيام مع 6 عمال = 72 تقسيم 6 = 12 يوماً.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-04",
      prompt_ar: "يحتاج مشروع إلى 60 يوم-عامل. أنجز 5 عمال منه 4 أيام، ثم أكمله 10 عمال. كم يوماً إضافياً احتاج العشرة؟",
      choices_ar: ["3", "4", "5", "6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح جزء أكبر من العمل.",
        2: "قُسم العمل الكامل على العمال الجدد.",
        3: "لم يُحسب ما أنجزه العمال أولاً.",
      },
      solve_ar:
        "ما أُنجز = 5 ضرب 4 = 20 يوم-عامل. الباقي = 60 ناقص 20 = 40 يوم-عامل. الزمن = 40 تقسيم 10 = 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-05",
      prompt_ar: "عمل 7 عمّال في تجهيز قاعة مدة 9 أيام. كم يوم-عامل يمثّل هذا العمل؟",
      choices_ar: ["16", "56", "63", "72"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع العمال والأيام بدلاً من ضربهما.",
        1: "استُخدمت ثمانية أيام فقط.",
        3: "استُخدم ثمانية عمال.",
      },
      solve_ar:
        "يوم-عامل = عدد العمال ضرب عدد الأيام. إذن 7 ضرب 9 = 63 يوم-عامل.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-06",
      prompt_ar: "ينجز 8 عمال عملاً في 15 يوماً. كم عاملاً يلزم لإنجازه في 10 أيام بالمعدل نفسه؟",
      choices_ar: ["10", "12", "15", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُضيف فرق الأيام إلى عدد العمال.",
        2: "عُدّ عدد الأيام عدداً للعمال.",
        3: "زِيد عدد العمال أكثر من اللازم.",
      },
      solve_ar:
        "العمل = 8 ضرب 15 = 120 يوم-عامل. عدد العمال = 120 تقسيم 10 = 12 عاملاً.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-07",
      prompt_ar: "بدأ 12 عاملاً عملاً يمكنهم إنهاؤه في 6 أيام. إذا أصبح عددهم 9 قبل البدء، فكم يوماً يحتاجون؟",
      choices_ar: ["4", "6", "8", "9"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُقصت الأيام مع نقص العمال.",
        1: "أُبقي الزمن كما هو.",
        3: "سُوّي عدد الأيام بعدد العمال.",
      },
      solve_ar:
        "العمل = 12 ضرب 6 = 72 يوم-عامل. الزمن مع 9 عمال = 72 تقسيم 9 = 8 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-08",
      prompt_ar: "ينهي أحمد عملاً وحده في 12 يوماً، وينهيه بدر وحده في 6 أيام. في كم يوم ينهيانه معاً؟",
      choices_ar: ["3", "4", "6", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف زمن الأسرع بلا جمع المعدلين.",
        2: "استُخدم زمن بدر وحده.",
        3: "أُخذ متوسط الزمنين.",
      },
      solve_ar:
        "في يوم واحد ينجز أحمد 1 تقسيم 12، وينجز بدر 1 تقسيم 6 = 2 تقسيم 12. معاً ينجزان 3 تقسيم 12 = 1 تقسيم 4 من العمل يومياً؛ إذن يحتاجان 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-09",
      prompt_ar: "تنجز سارة مهمة وحدها في 10 أيام، وتنجزها نورة وحدها في 15 يوماً. كم يوماً تحتاجان معاً؟",
      choices_ar: ["5", "6", "8", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف زمن سارة فقط.",
        2: "جُمعت معدلات العمل بصورة غير صحيحة.",
        3: "استُخدم متوسط الزمنين تقريباً.",
      },
      solve_ar:
        "معدل سارة في اليوم = 1 تقسيم 10 = 3 تقسيم 30. معدل نورة = 1 تقسيم 15 = 2 تقسيم 30. المجموع = 5 تقسيم 30 = 1 تقسيم 6؛ إذن 6 أيام.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-10",
      prompt_ar: "يكتب خالد تقريراً في 8 أيام، ويكتبه فهد في 24 يوماً. إذا عملا معاً بالمعدل نفسه، ففي كم يوم يتمّانه؟",
      choices_ar: ["4", "6", "8", "16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُصّف زمن الأسرع مباشرة.",
        2: "استُخدم زمن خالد وحده.",
        3: "أُخذ متوسط الزمنين.",
      },
      solve_ar:
        "معدل خالد = 1 تقسيم 8 = 3 تقسيم 24 من العمل يومياً. معدل فهد = 1 تقسيم 24. معاً = 4 تقسيم 24 = 1 تقسيم 6؛ إذن 6 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-11",
      prompt_ar: "ينجز عامل أول قطعة كبيرة في 20 يوماً، وينجزها عامل ثانٍ في 30 يوماً. كم يوماً يحتاجان معاً؟",
      choices_ar: ["10", "12", "15", "25"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف زمن العامل الأول.",
        2: "اختير زمن بين الزمنين مع أن العمل المشترك أسرع.",
        3: "أُخذ متوسط الزمنين.",
      },
      solve_ar:
        "معدل الأول = 1 تقسيم 20 = 3 تقسيم 60. معدل الثاني = 1 تقسيم 30 = 2 تقسيم 60. المجموع = 5 تقسيم 60 = 1 تقسيم 12؛ إذن 12 يوماً.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-12",
      prompt_ar: "ينهي عامل مهمة في 6 أيام، وينهيها عامل آخر في 3 أيام. كم يوماً يحتاجان إذا عملا معاً؟",
      choices_ar: ["1", "2", "3", "4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت السرعتان كأنهما تنهيان العمل كله يومياً.",
        2: "استُخدم زمن العامل الأسرع وحده.",
        3: "أُخذ متوسط تقريبي للزمنين.",
      },
      solve_ar:
        "معدل الأول = 1 تقسيم 6، ومعدل الثاني = 1 تقسيم 3 = 2 تقسيم 6. المجموع = 3 تقسيم 6 = نصف العمل يومياً؛ إذن يتم العمل في يومين.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-13",
      prompt_ar: "ينظّف 4 عمال ساحة في 9 أيام. إذا أصبحوا 6 عمال بالمعدل نفسه، فكم يوماً يحتاجون؟",
      choices_ar: ["5", "6", "8", "11"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نقص يوم من القسمة الصحيحة.",
        2: "طُرح فرق العمال من الأيام.",
        3: "زِيدت الأيام مع زيادة العمال.",
      },
      solve_ar:
        "العمل = 4 ضرب 9 = 36 يوم-عامل. الأيام مع 6 عمال = 36 تقسيم 6 = 6 أيام.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-14",
      prompt_ar: "يحزم 15 عاملاً شحنة في 4 أيام. إذا حضر 5 عمال فقط، فكم يوماً يحتاجون؟",
      choices_ar: ["8", "10", "12", "15"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُوعفت الأيام فقط مع أن العمال صاروا الثلث.",
        1: "زِيدت الأيام بستة دون تثبيت العمل.",
        3: "عُدّ عدد العمال أياماً.",
      },
      solve_ar:
        "العمل = 15 ضرب 4 = 60 يوم-عامل. الأيام مع 5 عمال = 60 تقسيم 5 = 12 يوماً.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-15",
      prompt_ar: "يحتاج عمل إلى 56 يوم-عامل. عمل فيه 8 عمال يومين، ثم أصبح عددهم 10. كم يوماً إضافياً يحتاج العشرة؟",
      choices_ar: ["3", "4", "5", "6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من الباقي عشرة أيام-عامل إضافية.",
        2: "أُهمل جزء من العمل المنجز.",
        3: "قُسم العمل الكامل تقريباً على العشرة.",
      },
      solve_ar:
        "أنجز الثمانية 8 ضرب 2 = 16 يوم-عامل. الباقي = 56 ناقص 16 = 40 يوم-عامل. الزمن الإضافي = 40 تقسيم 10 = 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-16",
      prompt_ar: "بدأ 12 عاملاً مشروعاً مقداره 120 يوم-عامل. بعد 5 أيام انضم إليهم 3 عمال. كم يوماً إضافياً يحتاج العمال الخمسة عشر؟",
      choices_ar: ["3", "4", "5", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الباقي على عشرين بدلاً من خمسة عشر.",
        2: "أُبقي عدد الأيام القديم.",
        3: "قُسم العمل الكامل على العمال الجدد.",
      },
      solve_ar:
        "أنجز 12 عاملاً في 5 أيام مقدار 12 ضرب 5 = 60 يوم-عامل. الباقي = 120 ناقص 60 = 60. الزمن = 60 تقسيم 15 = 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-17",
      prompt_ar: "شارك 14 عاملاً في إعداد معرض مدة 3 أيام. ما مقدار العمل بوحدة يوم-عامل؟",
      choices_ar: ["17", "28", "42", "56"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع عدد العمال والأيام.",
        1: "استُخدم يومان فقط.",
        3: "استُخدمت أربعة أيام.",
      },
      solve_ar:
        "مقدار العمل = عدد العمال ضرب عدد الأيام = 14 ضرب 3 = 42 يوم-عامل.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-18",
      prompt_ar: "يتطلب تجهيز مسرح 96 يوم-عامل. إذا عمل 12 عاملاً بالمعدل نفسه، فكم يوماً يحتاجون؟",
      choices_ar: ["6", "8", "10", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم مقدار العمل على ستة عشر.",
        2: "زِيد يومان على الناتج.",
        3: "عُدّ عدد العمال أياماً.",
      },
      solve_ar:
        "الأيام = مقدار العمل تقسيم عدد العمال = 96 تقسيم 12 = 8 أيام.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
  final_extra: [
    {
      id: "wr-f01",
      prompt_ar: "ينجز 18 عاملاً عملاً في 5 أيام. إذا نفّذه 10 عمال بالمعدل نفسه، فكم يوماً يحتاجون؟",
      choices_ar: ["7", "8", "9", "10"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "طُرح فرق غير صحيح من مقدار العمل.",
        1: "حُسبت القسمة على نحو ناقص.",
        3: "عُدّ عدد العمال أياماً.",
      },
      solve_ar:
        "العمل = 18 ضرب 5 = 90 يوم-عامل. الأيام مع 10 عمال = 90 تقسيم 10 = 9 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f02",
      prompt_ar: "مقدار عمل 96 يوم-عامل. عمل فيه 16 عاملاً 3 أيام، ثم أكمله 12 عاملاً. كم يوماً إضافياً احتاج الاثنا عشر؟",
      choices_ar: ["3", "4", "5", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح يوم إضافي من الزمن الصحيح.",
        2: "حُسب الباقي على عدد عمال غير صحيح.",
        3: "قُسم العمل الكامل على 12.",
      },
      solve_ar:
        "المنجز = 16 ضرب 3 = 48 يوم-عامل. الباقي = 96 ناقص 48 = 48. الزمن الإضافي = 48 تقسيم 12 = 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f03",
      prompt_ar: "ينجز شخص عملاً في 9 أيام، وينجزه آخر في 18 يوماً. كم يوماً يحتاجان معاً؟",
      choices_ar: ["4", "6", "9", "13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُصّف زمن الأسرع تقريباً.",
        2: "استُخدم زمن الشخص الأسرع وحده.",
        3: "أُخذ متوسط الزمنين تقريباً.",
      },
      solve_ar:
        "معدل الأول = 1 تقسيم 9 = 2 تقسيم 18، ومعدل الثاني = 1 تقسيم 18. معاً = 3 تقسيم 18 = 1 تقسيم 6؛ إذن 6 أيام.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f04",
      prompt_ar: "يتمّ عامل مهمة في 8 أيام، ويتمّها عامل آخر في 8 أيام. كم يوماً يحتاجان معاً؟",
      choices_ar: ["2", "4", "8", "16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الزمن على أربعة بدلاً من اثنين.",
        2: "استُخدم زمن عامل واحد.",
        3: "جُمع الزمنان.",
      },
      solve_ar:
        "كل عامل ينجز 1 تقسيم 8 من المهمة يومياً. معاً ينجزان 2 تقسيم 8 = 1 تقسيم 4 يومياً؛ إذن يحتاجان 4 أيام.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f05",
      prompt_ar: "ينجز 6 عمال ترميم غرفة في 14 يوماً. كم عاملاً يلزم لإنجازها في 7 أيام؟",
      choices_ar: ["7", "10", "12", "14"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عُدّ عدد الأيام عدداً للعمال.",
        1: "أُضيف أربعة إلى العمال دون تثبيت العمل.",
        3: "استُخدم عدد الأيام الأصلي.",
      },
      solve_ar:
        "العمل = 6 ضرب 14 = 84 يوم-عامل. عدد العمال = 84 تقسيم 7 = 12 عاملاً.",
      trick_ref: "work-rate",
      difficulty: "mid",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f06",
      prompt_ar: "يحتاج مشروع إلى 132 يوم-عامل. إذا شارك فيه 11 عاملاً، فكم يوماً يحتاجون؟",
      choices_ar: ["10", "11", "12", "13"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم مقدار العمل على عدد أكبر من العمال.",
        1: "عُدّ عدد العمال أياماً.",
        3: "زِيد يوم على القسمة الصحيحة.",
      },
      solve_ar:
        "الأيام = مقدار العمل تقسيم عدد العمال = 132 تقسيم 11 = 12 يوماً.",
      trick_ref: "work-rate",
      difficulty: "easy",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
    {
      id: "wr-f07",
      prompt_ar: "ينجز عامل عملاً في 15 يوماً، وينجزه عامل آخر في 10 أيام. كم يوماً يحتاجان معاً؟",
      choices_ar: ["5", "6", "8", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف زمن العامل الثاني.",
        2: "جُمعت المعدلات بصورة غير صحيحة.",
        3: "اختير زمن قريب من المتوسط.",
      },
      solve_ar:
        "معدل الأول = 1 تقسيم 15 = 2 تقسيم 30. معدل الثاني = 1 تقسيم 10 = 3 تقسيم 30. المجموع = 5 تقسيم 30 = 1 تقسيم 6؛ إذن 6 أيام.",
      trick_ref: "work-rate",
      difficulty: "hard",
      sub_pattern: "rate",
      source: "style-modeled-practice-2026",
      review_status: "approved",
      reviewed_by: "founder",
      reviewed_at: "2026-09-13T00:00:00.000Z",
    },
  ],
};
