import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const arithSeq: Skill = {
  id: "arith-seq",
  title_ar: "المتتالية الحسابية",
  domain: "algebra",
  hook_ar: "فرق ثابت بين كل حدّ والذي يليه — أوجد التالي أو الحدّ النوني البسيط",
  estimated_minutes: 7,
  icon: "⋯",
  visual: { kind: "custom", component: "arith-seq-lab" },
  intuition_ar: [
    "المتتالية الحسابية تزيد أو تنقص بمقدار ثابت يُسمّى الفرق.",
    "الحد التالي = الحد الحالي + الفرق.",
    "الحد النوني = الحد الأول + (ن − 1) × الفرق.",
  ],
  trick_ar: {
    statement: "احسب الفرق مرة واحدة، ثم أضف أو اطرح حسب المطلوب.",
    steps: [
      "الفرق = حد − الذي قبله",
      "للحد التالي: أضف الفرق",
      "للحد النوني: الأول + (ن − 1) × الفرق",
    ],
    time_target_sec: 18,
    example_ar:
      "3، 7، 11… الفرق = 4. الحد التالي 15. والحد الخامس = 3 + 4×4 = 19.",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "aseq-01",
      prompt_ar: "متتالية: 4، 7، 10، 13… ما الحد التالي؟",
      choices_ar: ["14", "15", "16", "17"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 1 فقط.",
        1: "أُضيف 2 بدل 3.",
        3: "أُضيف 4 بدل 3.",
      },
      solve_ar: "الفرق = 3. التالي = 13 + 3 = 16.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-02",
      prompt_ar: "متتالية: 20، 15، 10، 5… ما الحد التالي؟",
      choices_ar: ["0", "1", "−5", "2"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُضيف 1 خطأ.",
        2: "طُرح 10 بدل 5.",
        3: "أُضيف بدل الطرح.",
      },
      solve_ar: "الفرق = −5. التالي = 5 + (−5) = 0.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-03",
      prompt_ar: "ما الفرق المشترك في: 2، 8، 14، 20؟",
      choices_ar: ["4", "5", "6", "8"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر لأول رقمين خطأ.",
        1: "قُرب عشوائي.",
        3: "أُخذ الحد الأول أو خُلط بضرب.",
      },
      solve_ar: "8 − 2 = 6، وكذلك 14 − 8 = 6.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-04",
      prompt_ar: "متتالية حدّها الأول 5 وفرقها 4. ما الحد الثالث؟",
      choices_ar: ["9", "13", "17", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الحد الثاني فقط: 5+4.",
        2: "أُضيف الفرق ثلاث مرات من الأول خطأ للحد الثالث.",
        3: "خُلط بضرب.",
      },
      solve_ar: "الحد الثالث = 5 + 2×4 = 13.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-05",
      prompt_ar: "متتالية: 9، 12، 15، ؟، 21. ما الحد الناقص؟",
      choices_ar: ["16", "17", "18", "19"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 1.",
        1: "أُضيف 2.",
        3: "أُضيف 4.",
      },
      solve_ar: "الفرق = 3. الناقص = 15 + 3 = 18.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-06",
      prompt_ar: "متتالية: 30، 27، 24… ما الحد السادس؟",
      choices_ar: ["12", "15", "18", "21"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح مرة إضافية.",
        2: "حُسب الحد الخامس بدل السادس.",
        3: "حُسب الحد الرابع.",
      },
      solve_ar:
        "الفرق = −3. الحد السادس = 30 + 5×(−3) = 30 − 15 = 15.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-07",
      prompt_ar:
        "أسعار تذكرة تزيد كل أسبوع بمبلغ ثابت: 40، 45، 50… كم سعر الأسبوع الخامس؟",
      choices_ar: ["55", "60", "65", "70"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الأسبوع الرابع.",
        2: "أُضيف الفرق ست مرات من الأول تقريباً.",
        3: "خُلط بعدد الأسابيع×الفرق دون طرح 1.",
      },
      solve_ar: "الفرق = 5. الخامس = 40 + 4×5 = 60.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-08",
      prompt_ar: "حدّ أول 7 وفرق −2. ما الحد السابع؟",
      choices_ar: ["−5", "−3", "−1", "1"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب بـ 5 إضافات بدل 6.",
        2: "حُسب بـ 4 إضافات.",
        3: "أُضيف الفرق بدل طرحه.",
      },
      solve_ar: "7 + 6×(−2) = 7 − 12 = −5.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-09",
      prompt_ar: "متتالية: 1، 6، 11، 16… ما الحد العاشر؟",
      choices_ar: ["41", "46", "51", "56"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب التاسع: 1+8×5.",
        2: "حُسب الحادي عشر أو 1+10×5.",
        3: "أُضيف 5×11.",
      },
      solve_ar: "الفرق = 5. العاشر = 1 + 9×5 = 46.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-10",
      prompt_ar: "إذا كان الحد الثالث 14 والفرق 3، فما الحد الأول؟",
      choices_ar: ["5", "8", "11", "17"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح الفرق ثلاث مرات.",
        2: "طُرح مرة واحدة فقط (الحد الثاني).",
        3: "أُضيف الفرق بدل الطرح.",
      },
      solve_ar: "الأول = الثالث − 2×الفرق = 14 − 6 = 8.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-11",
      prompt_ar: "متتالية: −4، −1، 2، 5… ما الحد التالي؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 1.",
        1: "أُضيف 2.",
        3: "أُضيف 4.",
      },
      solve_ar: "الفرق = 3. التالي = 5 + 3 = 8.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-12",
      prompt_ar:
        "عدد مقاعد صف يبدأ بـ 18 ويزيد صفاً بصف بمقدار 2. كم مقعداً في الصف السادس؟",
      choices_ar: ["26", "28", "30", "32"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الخامس.",
        2: "أُضيف 2×6 دون طرح 1.",
        3: "أُضيف زيادة.",
      },
      solve_ar: "18 + 5×2 = 28.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-13",
      prompt_ar: "متتالية حدّاها الرابع 25 والخامس 31. ما الفرق؟",
      choices_ar: ["5", "6", "7", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح خطأ.",
        2: "زِيد على الفرق.",
        3: "خُلط بنصف المجموع.",
      },
      solve_ar: "الفرق = 31 − 25 = 6.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-14",
      prompt_ar: "حدّ أول 100 وفرق −7. ما الحد الرابع؟",
      choices_ar: ["79", "86", "93", "72"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب الثاني فقط مرتين تقريباً — الحد الثاني 93، الثالث 86.",
        2: "حُسب الحد الثاني.",
        3: "طُرح 7 أربع مرات من الأول.",
      },
      solve_ar: "100 + 3×(−7) = 100 − 21 = 79.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-15",
      prompt_ar: "متتالية: 3، 10، 17، 24… ما رتبة الحد الذي قيمته 52؟",
      choices_ar: ["7", "8", "9", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي إضافة 1 بعد القسمة.",
        2: "زِيد رتبة.",
        3: "قُسم (52−3) على 5 فقط دون ترتيب.",
      },
      solve_ar:
        "الفرق = 7. 3 + (ن−1)×7 = 52 → (ن−1)×7 = 49 → ن−1 = 7 → ن = 8.",
      trick_ref: "arith-seq",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-16",
      prompt_ar: "متتالية: 12، ؟، 28، 36. ما الحد الناقص؟",
      choices_ar: ["16", "18", "20", "22"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 4.",
        1: "أُضيف 6.",
        3: "أُضيف 10.",
      },
      solve_ar: "من 28 إلى 36 الفرق 8، فـ 12 + 8 = 20.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-17",
      prompt_ar: "حدّ أول −5 وفرق 4. ما الحد السادس؟",
      choices_ar: ["11", "15", "19", "23"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الخامس: −5+4×4.",
        2: "حُسب السابع.",
        3: "أُضيف 4×7.",
      },
      solve_ar: "−5 + 5×4 = −5 + 20 = 15.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-18",
      prompt_ar:
        "رصيد ادخار يبدأ بـ 50 ويزيد 15 كل شهر. ما الرصيد بعد 4 أشهر؟",
      choices_ar: ["95", "110", "125", "140"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُضيف 15×3 فقط.",
        2: "أُضيف 15×5.",
        3: "أُضيف 15×6.",
      },
      solve_ar: "50 + 4×15 = 110.",
      trick_ref: "arith-seq",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "aseq-f01",
      prompt_ar: "متتالية: 8، 13، 18… ما الحد التاسع؟",
      choices_ar: ["43", "48", "53", "58"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب الثامن.",
        2: "حُسب العاشر: 8+10×5.",
        3: "أُضيف 5×10.",
      },
      solve_ar: "الفرق = 5. التاسع = 8 + 8×5 = 48.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f02",
      prompt_ar: "إذا كان الحد الثاني 11 والحد الخامس 23، فما الفرق؟",
      choices_ar: ["3", "4", "5", "6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الفرق الكلي على 4 خطأً بـ 3.",
        2: "قُسم 12 على عدد الخطوات خطأ.",
        3: "أُخذ نصف الفرق بين الحدين.",
      },
      solve_ar:
        "بين الثاني والخامس ثلاث خطوات: 23 − 11 = 12، والفرق = 12÷3 = 4.",
      trick_ref: "arith-seq",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f03",
      prompt_ar: "متتالية: 40، 34، 28، 22… ما الحد السابع؟",
      choices_ar: ["4", "10", "16", "−2"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب السادس.",
        2: "حُسب الخامس.",
        3: "طُرح مرة إضافية.",
      },
      solve_ar: "الفرق = −6. السابع = 40 + 6×(−6) = 40 − 36 = 4.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f04",
      prompt_ar: "حدّ أول 2 وفرق 9. ما مجموع الحدّين الثالث والرابع؟",
      choices_ar: ["29", "49", "47", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الرابع فقط.",
        2: "جُمع خطأ بحدّين متجاورين غيرهما.",
        3: "أُخذ الثالث فقط.",
      },
      solve_ar:
        "الثالث = 2 + 2×9 = 20، الرابع = 2 + 3×9 = 29، والمجموع = 49.",
      trick_ref: "arith-seq",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f05",
      prompt_ar: "متتالية: 5، 5، 5، 5… ما الفرق المشترك؟",
      choices_ar: ["0", "1", "5", "−5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "افتُرض زيادة وهمية.",
        2: "أُخذ قيمة الحد بدل الفرق.",
        3: "افتُرض تناقص.",
      },
      solve_ar: "الحدود متساوية، فالفرق = 0.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f06",
      prompt_ar: "ما الحد الأوسط في: 4، 10، 16، 22، 28؟",
      choices_ar: ["10", "16", "22", "18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الثاني.",
        2: "أُخذ الرابع.",
        3: "حُسب متوسط الطرفين فقط دون ترتيب.",
      },
      solve_ar: "خمسة حدود؛ الأوسط هو الثالث = 16.",
      trick_ref: "arith-seq",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "aseq-f07",
      prompt_ar:
        "قطار يزيد سرعتة كل دقيقة بمقدار ثابت: 60، 66، 72… كم سرعته في الدقيقة السابعة؟",
      choices_ar: ["90", "96", "102", "108"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب السادسة.",
        2: "حُسب الثامنة: 60+7×6.",
        3: "أُضيف 6×8.",
      },
      solve_ar: "الفرق = 6. السابعة = 60 + 6×6 = 96.",
      trick_ref: "arith-seq",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
  ],
};
