import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const inequalities: Skill = {
  id: "inequalities",
  title_ar: "المتباينات",
  domain: "algebra",
  hook_ar: "أكبر أو أصغر عدد صحيح يحقق الشرط — لا تخلطها بمعادلة تساوي",
  estimated_minutes: 8,
  icon: "<",
  visual: { kind: "custom", component: "inequalities-lab" },
  intuition_ar: [
    "المتباينة تقول إن طرفاً أصغر أو أكبر من طرف، وليست معادلة تساوٍ.",
    "على خط الأعداد: ظلّل الجهة الصحيحة، ثم اختر أكبر أو أصغر صحيح داخل التظليل.",
    "علامة < أو > لا تشمل الحد؛ أما ≤ أو ≥ فتشمله.",
  ],
  trick_ar: {
    statement: "حلّ كمعادلة ثم انتبه للاتجاه: أكبر صحيح داخل المنطقة أو أصغره.",
    steps: [
      "اعزل س كما في المعادلة",
      "إن عكست الطرفين عند ضرب/قسمة بعدد سالب فانعكس اتجاه العلامة",
      "لـ س < عدد صحيح: أكبر صحيح = العدد ناقص 1",
    ],
    time_target_sec: 20,
    example_ar:
      "2س < 15 → س < 7.5 → أكبر صحيح هو 7. أما س ≤ 7 فأكبر صحيح هو 7 نفسه.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ineq-01",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: س < 8؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص اثنان بدل واحد.",
        2: "شُمل الحد مع أن العلامة أصغر من فقط.",
        3: "أُخذ عدد أكبر من الحد.",
      },
      solve_ar: "س أصغر من 8 تماماً، فأكبر صحيح هو 7.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-02",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: س > 3؟",
      choices_ar: ["2", "3", "4", "5"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذ أصغر من الحد.",
        1: "شُمل 3 مع أن العلامة أكبر من فقط.",
        3: "قُفز رقم إضافي.",
      },
      solve_ar: "س أكبر من 3 تماماً، فأصغر صحيح هو 4.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-03",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: س ≤ 5؟",
      choices_ar: ["3", "4", "5", "6"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُقص أكثر من اللازم.",
        1: "نُسي أن ≤ يشمل الحد.",
        3: "تجاوز الحد.",
      },
      solve_ar: "≤ يشمل 5، فأكبر صحيح هو 5.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-04",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: س ≥ −2؟",
      choices_ar: ["−3", "−2", "−1", "0"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أصغر من الحد رغم ≥.",
        2: "نُسي شمول الحد.",
        3: "قُفز إلى الصفر بلا سبب.",
      },
      solve_ar: "≥ يشمل −2، فأصغر صحيح هو −2.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-05",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: 2س < 14؟",
      choices_ar: ["5", "6", "7", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص زيادة.",
        2: "شُمل 7 مع أن س < 7.",
        3: "قُسم خطأ أو شُمل الحد.",
      },
      solve_ar: "2س < 14 → س < 7 → أكبر صحيح هو 6.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-06",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: 3س > 20؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ 20÷3≈6.6 ثم نُزل بدل الرفع.",
        2: "قُفز رقم إضافي.",
        3: "قُرب بعيد.",
      },
      solve_ar: "س > 20÷3 ≈ 6.67 → أصغر صحيح هو 7.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-07",
      prompt_ar:
        "درجة حرارة غرفة يجب أن تبقى أصغر من 24. ما أكبر قراءة صحيحة مسموحة؟",
      choices_ar: ["22", "23", "24", "25"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص رقمين.",
        2: "شُملت 24 مع شرط أصغر من.",
        3: "تجاوز الحد.",
      },
      solve_ar: "س < 24 → أكبر صحيح 23.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-08",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: س − 4 < 9؟",
      choices_ar: ["11", "12", "13", "14"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص زيادة بعد العزل.",
        2: "شُمل الحد كأن العلامة ≤.",
        3: "جُمع 4 مع 9 دون انتباه للعلامة.",
      },
      solve_ar: "س < 13 → أكبر صحيح 12.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-09",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: س + 5 ≥ 12؟",
      choices_ar: ["6", "7", "8", "17"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي شمول المساواة.",
        2: "زِيد رقم بلا سبب.",
        3: "جُمع الطرفان بدل العزل.",
      },
      solve_ar: "س ≥ 7 → أصغر صحيح 7.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-10",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: 4س ≤ 30؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرب لأسفل زيادة.",
        2: "تجاوز 30÷4 = 7.5.",
        3: "أُخذ 36÷4.",
      },
      solve_ar:
        "س ≤ 7.5 → أكبر صحيح 7 لأن 4×7 = 28 ≤ 30 بينما 4×8 = 32 أكبر من 30.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-11",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: 5س ≥ 42؟",
      choices_ar: ["8", "9", "10", "42"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "5×8 = 40 أصغر من 42 فلا يحقق ≥.",
        2: "قُفز زيادة.",
        3: "أُخذ الطرف الأيمن كما هو.",
      },
      solve_ar: "س ≥ 8.4 → أصغر صحيح 9 لأن 5×9 = 45 ≥ 42.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-12",
      prompt_ar:
        "حدّ أقصى لعدد المقاعد في صف: 2س + 1 < 25. ما أكبر عدد صحيح للمقاعد س؟",
      choices_ar: ["10", "11", "12", "13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص زيادة.",
        2: "شُمل حدّ المساواة خطأً.",
        3: "نُسي طرح 1 قبل القسمة.",
      },
      solve_ar: "2س < 24 → س < 12 → أكبر صحيح 11.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-13",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: −س > −4؟",
      choices_ar: ["2", "3", "4", "5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص زيادة بعد عكس العلامة.",
        2: "نُسي عكس الاتجاه فشُمل 4.",
        3: "اتجاه خاطئ بعد العكس.",
      },
      solve_ar:
        "اضرب الطرفين في −1 فتنعكس العلامة: س < 4 → أكبر صحيح 3.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-14",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: −2س ≤ −10؟",
      choices_ar: ["4", "5", "6", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي عكس العلامة عند القسمة على سالب.",
        2: "قُفز رقم.",
        3: "أُخذ الطرف الأيمن.",
      },
      solve_ar:
        "اقسم على −2 فتنعكس العلامة: س ≥ 5 → أصغر صحيح 5.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-15",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: 3س − 2 < 16؟",
      choices_ar: ["5", "6", "7", "8"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "شُمل 6 مع أن س < 6.",
        2: "نُسي طرح 2 ثم قُسم خطأ.",
        3: "جُمع 2 بدل الطرح.",
      },
      solve_ar: "3س < 18 → س < 6 → أكبر صحيح 5.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-16",
      prompt_ar:
        "وزن شحنة بالكيلو س يحقق: س ÷ 2 > 9. ما أصغر عدد صحيح مسموح؟",
      choices_ar: ["17", "18", "19", "20"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُقص زيادة.",
        1: "شُمل المساواة مع أن العلامة أكبر من.",
        3: "قُفز رقم.",
      },
      solve_ar: "س > 18 → أصغر صحيح 19.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-17",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: 2(س + 3) ≤ 20؟",
      choices_ar: ["6", "7", "8", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي شمول المساواة أو طرح زائد.",
        2: "نُسي طرح 3 بعد القسمة.",
        3: "قُسم 20 على 2 دون فك القوس بالكامل.",
      },
      solve_ar: "س + 3 ≤ 10 → س ≤ 7 → أكبر صحيح 7.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-18",
      prompt_ar:
        "نقاط لاعب يجب ألا تقل عن 15، أي س ≥ 15. ما أصغر عدد صحيح يحقق الشرط؟",
      choices_ar: ["14", "15", "16", "0"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "خُلط بعلامة >.",
        2: "زِيد رقم بلا سبب.",
        3: "تجاهل الشرط.",
      },
      solve_ar: "≥ يشمل 15، فأصغر صحيح هو 15.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ineq-f01",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: 5س + 1 < 37؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص زيادة.",
        2: "شُمل حدّ المساواة خطأً.",
        3: "نُسي طرح 1.",
      },
      solve_ar: "5س < 36 → س < 7.2 → أكبر صحيح 7.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f02",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: 4س − 3 > 21؟",
      choices_ar: ["5", "6", "7", "8"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُزل بعد القسمة.",
        1: "شُمل المساواة مع علامة >.",
        3: "قُفز زيادة.",
      },
      solve_ar: "4س > 24 → س > 6 → أصغر صحيح 7.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f03",
      prompt_ar: "ما أكبر عدد صحيح س يحقق: −3س ≥ −18؟",
      choices_ar: ["5", "6", "7", "18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص بعد عكس العلامة.",
        2: "اتجاه معاكس بعد القسمة على سالب.",
        3: "أُخذ الطرف الأيمن.",
      },
      solve_ar:
        "اقسم على −3 فتنعكس العلامة: س ≤ 6 → أكبر صحيح 6.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f04",
      prompt_ar:
        "سعر تذكرة س بالريال يحقق: 3س ≤ 100. ما أكبر عدد صحيح ممكن للسعر؟",
      choices_ar: ["32", "33", "34", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرب لأسفل زيادة.",
        2: "3×34 = 102 أكبر من 100.",
        3: "أُخذ الطرف الأيمن.",
      },
      solve_ar: "س ≤ 100÷3 ≈ 33.33 → أكبر صحيح 33 لأن 3×33 = 99 ≤ 100.",
      trick_ref: "inequalities",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f05",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: س ÷ 3 ≥ 4؟",
      choices_ar: ["11", "12", "13", "7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي شمول المساواة.",
        2: "قُفز رقم.",
        3: "خُلط بجمع بدل ضرب.",
      },
      solve_ar: "س ≥ 12 → أصغر صحيح 12.",
      trick_ref: "inequalities",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f06",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: 2س + 5 < 3س − 1؟",
      choices_ar: ["4", "5", "6", "7"],
      correct_index: 3,
      trap_explanations_ar: {
        0: "نُقص بعد النقل.",
        1: "شُمل المساواة خطأً أو نُزل.",
        2: "نُسي أن س > 6 فلا يُقبل 6.",
      },
      solve_ar: "5 + 1 < 3س − 2س → 6 < س → س > 6 → أصغر صحيح 7.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "ineq-f07",
      prompt_ar: "ما أصغر عدد صحيح س يحقق: 7 − س < 2؟",
      choices_ar: ["4", "5", "6", "9"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُقص بعد عكس الاتجاه.",
        1: "شُمل المساواة مع <.",
        3: "جُمع الطرفان.",
      },
      solve_ar: "−س < −5 → اضرب في −1: س > 5 → أصغر صحيح 6.",
      trick_ref: "inequalities",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
  ],
};
