import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const squarePatterns: Skill = {
  id: "square-patterns",
  title_ar: "أنماط المربعات",
  domain: "algebra",
  hook_ar: "1، 4، 9، 16… كل حدّ هو مربّع رتبتِه — لا تخلطها بفرق ثابت",
  estimated_minutes: 7,
  icon: "▣",
  visual: { kind: "custom", component: "square-patterns-lab" },
  intuition_ar: [
    "الأعداد 1، 4، 9، 16، 25… هي مربّعات: 1²، 2²، 3²، 4²، 5².",
    "الفرق بين مربّعين متتاليين ليس ثابتاً؛ يزداد بفرديّات: 3 ثم 5 ثم 7…",
    "لإيجاد الناقص أو التالي: حدّد الرتبة ن ثم احسب ن².",
  ],
  trick_ar: {
    statement: "عيّن ن للحدّ المطلوب، الناتج = ن × ن.",
    steps: [
      "رتّب الحدود: الأول ن=1، الثاني ن=2…",
      "الحد النوني = ن²",
      "لا تفترض فرقاً ثابتاً كما في المتتالية الحسابية",
    ],
    time_target_sec: 16,
    example_ar: "1، 4، 9، 16، ؟ → الرتبة 5 → 5×5 = 25.",
  },
  timing: {
    excellent_sec: 16,
    good_sec: 26,
    ok_sec: 36,
    slow_sec: 50,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "sqp-01",
      prompt_ar: "متتالية: 1، 4، 9، 16… ما الحد التالي؟",
      choices_ar: ["20", "23", "25", "36"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف فرق ثابت 4 كأنها حسابية.",
        1: "أُضيف 7 (آخر فرق) فقط.",
        3: "قُفز إلى 6².",
      },
      solve_ar: "الحدود مربّعات: 1²، 2²، 3²، 4²، التالي 5² = 25.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-02",
      prompt_ar: "ما الحد الناقص: 1، 4، ؟، 16، 25؟",
      choices_ar: ["8", "9", "10", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُضيف فرق حسابي.",
        2: "قُرب عشوائي.",
        3: "خُلط بضعف أو متوسط.",
      },
      solve_ar: "الرتبة الثالثة → 3² = 9.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-03",
      prompt_ar: "كم يساوي 6²؟",
      choices_ar: ["12", "30", "36", "42"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف 6 بدل تربيعه.",
        1: "خُلط بـ 5×6.",
        3: "خُلط بـ 6×7.",
      },
      solve_ar: "6×6 = 36.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-04",
      prompt_ar: "متتالية: 4، 9، 16، 25… ما الحد التالي؟",
      choices_ar: ["30", "32", "36", "49"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 5 كفرق ثابت.",
        1: "أُضيف 7.",
        3: "قُفز إلى 7².",
      },
      solve_ar: "بدأت من 2²؛ التالي بعد 5² هو 6² = 36.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-05",
      prompt_ar: "أي عدد يكمل النمط: 1، 4، 9، 16، 25، ؟",
      choices_ar: ["30", "35", "36", "49"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 5.",
        1: "أُضيف 10.",
        3: "قُفز إلى 7².",
      },
      solve_ar: "السادس = 6² = 36.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-06",
      prompt_ar: "بلاطات مربّعة في صفوف: صف واحد 1، صفان 4، ثلاثة 9. كم لخمسة صفوف؟",
      choices_ar: ["20", "25", "30", "15"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب 5×4.",
        2: "خُلط بـ 5×6.",
        3: "جُمع الصفوف 1+2+3+4+5.",
      },
      solve_ar: "العدد = ن²؛ لـ ن=5 → 25.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-07",
      prompt_ar: "ما رتبة الحد 49 في متتالية المربّعات 1، 4، 9…؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب 36 كأنه 49.",
        2: "حُسب 64.",
        3: "قُرب بعيد.",
      },
      solve_ar: "7×7 = 49، فالرتبة 7.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-08",
      prompt_ar: "متتالية: 9، 16، 25، 36، ؟",
      choices_ar: ["42", "45", "49", "64"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 6.",
        1: "أُضيف 9.",
        3: "قُفز إلى 8².",
      },
      solve_ar: "بعد 6² يأتي 7² = 49.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-09",
      prompt_ar: "ما الحد الناقص: 1، ؟، 9، 16؟",
      choices_ar: ["2", "3", "4", "5"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "خُلط بمتتالية أخرى.",
        1: "أُخذ الجذر فقط دون تربيع.",
        3: "قُرب.",
      },
      solve_ar: "الثاني = 2² = 4.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-10",
      prompt_ar: "الحد الثامن في 1، 4، 9، 16… يساوي؟",
      choices_ar: ["56", "64", "72", "81"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب 7×8.",
        2: "ضُرب 8×9.",
        3: "حُسب 9².",
      },
      solve_ar: "8² = 64.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-11",
      prompt_ar:
        "لوحة نقاط مربّعة: ضلعها 10 نقاط. كم عدد النقاط الكلي؟",
      choices_ar: ["20", "90", "100", "110"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف الضلع.",
        1: "ضُرب 9×10.",
        3: "ضُرب 10×11.",
      },
      solve_ar: "10×10 = 100.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-12",
      prompt_ar: "أيّ الخيارات ليس من متتالية المربّعات؟",
      choices_ar: ["36", "48", "49", "64"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "36 = 6² مربّع.",
        2: "49 = 7² مربّع.",
        3: "64 = 8² مربّع.",
      },
      solve_ar: "48 ليس مربّع عدد صحيح، بينما 36 و 49 و 64 مربّعات.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-13",
      prompt_ar: "متتالية: 16، 25، 36، 49، ؟",
      choices_ar: ["56", "60", "64", "81"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 7.",
        1: "أُضيف 11 تقريباً.",
        3: "قُفز إلى 9².",
      },
      solve_ar: "بعد 7² يأتي 8² = 64.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-14",
      prompt_ar: "كم يزيد الحد عند الانتقال من 5² إلى 6²؟",
      choices_ar: ["5", "9", "11", "13"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذ ن فقط.",
        1: "أُخذ 3² أو فرق أقدم.",
        3: "أُخذ الفرق التالي (نحو 7²).",
      },
      solve_ar: "36 − 25 = 11، وهو أيضاً 5+6.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-15",
      prompt_ar: "ما الحد العاشر في متتالية المربّعات؟",
      choices_ar: ["90", "99", "100", "121"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب 9×10.",
        1: "قُرب ناقص.",
        3: "حُسب 11².",
      },
      solve_ar: "10² = 100.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-16",
      prompt_ar: "متتالية: 1، 4، 9، 16، 25، 36، 49، ؟",
      choices_ar: ["56", "60", "64", "72"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف فرق فردي ناقص.",
        1: "أُضيف 11.",
        3: "خُلط بضرب.",
      },
      solve_ar: "الثامن = 8² = 64.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-17",
      prompt_ar:
        "طالب حسب المتتالية بإضافة 5 كل مرة فكتب 4، 9، 14، 19. ما قيمة الحد الرابع الصحيح في متتالية المربّعات 1، 4، 9، …؟",
      choices_ar: ["16", "19", "20", "25"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نتيجة الفرق الثابت الخاطئ التي كتبها الطالب.",
        2: "أُضيف 4 إلى 16.",
        3: "قُفز إلى 5² بدل الحد الرابع 4².",
      },
      solve_ar:
        "متتالية المربّعات: 1²، 2²، 3²، 4² → الحد الرابع = 16، لا 19.",
      trick_ref: "square-patterns",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-18",
      prompt_ar: "أي عدد هو 12²؟",
      choices_ar: ["120", "132", "144", "156"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب 10×12.",
        1: "ضُرب 11×12.",
        3: "ضُرب 12×13.",
      },
      solve_ar: "12×12 = 144.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "sqp-f01",
      prompt_ar: "متتالية: 25، 36، 49، 64، ؟",
      choices_ar: ["72", "75", "81", "100"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 8.",
        1: "أُضيف 11.",
        3: "قُفز إلى 10².",
      },
      solve_ar: "بعد 8² يأتي 9² = 81.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f02",
      prompt_ar: "ما رتبة الحد 121؟",
      choices_ar: ["10", "11", "12", "13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب 100.",
        2: "حُسب 144.",
        3: "قُرب بعيد.",
      },
      solve_ar: "11×11 = 121.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f03",
      prompt_ar: "متتالية مربّعات لأعداد زوجية: 4، 16، ؟، 64. ما الناقص؟",
      choices_ar: ["24", "36", "48", "32"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "خُلط بمتتالية حسابية.",
        2: "ضُعف أو متوسط خطأ.",
        3: "ضُعف 16.",
      },
      solve_ar: "2²، 4²، 6²، 8² → الناقص 6² = 36.",
      trick_ref: "square-patterns",
      difficulty: "hard",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f04",
      prompt_ar: "كم عدد البلاطات في مربّع ضلعه 15؟",
      choices_ar: ["30", "210", "225", "240"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُعف الضلع.",
        1: "ضُرب 14×15.",
        3: "ضُرب 15×16.",
      },
      solve_ar: "15×15 = 225.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f05",
      prompt_ar: "متتالية: 1، 4، 9، س، 25. ما س؟",
      choices_ar: ["12", "15", "16", "20"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 3.",
        1: "أُضيف 6.",
        3: "أُضيف 11 من 9.",
      },
      solve_ar: "س = 4² = 16.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f06",
      prompt_ar: "الفرق بين 9² و 8² يساوي؟",
      choices_ar: ["1", "9", "17", "72"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "خُلط بفرق وحدات.",
        1: "أُخذ 9 فقط.",
        3: "ضُرب بدل الطرح.",
      },
      solve_ar: "81 − 64 = 17.",
      trick_ref: "square-patterns",
      difficulty: "mid",
      sub_pattern: "algebra",
      ...review,
    },
    {
      id: "sqp-f07",
      prompt_ar: "أي حدّ يلي 81 في متتالية المربّعات الكاملة من 1؟",
      choices_ar: ["90", "99", "100", "121"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 9.",
        1: "أُضيف 18.",
        3: "قُفز إلى 11².",
      },
      solve_ar: "81 = 9²، التالي 10² = 100.",
      trick_ref: "square-patterns",
      difficulty: "easy",
      sub_pattern: "algebra",
      ...review,
    },
  ],
};
