import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const perimeter: Skill = {
  id: "perimeter",
  title_ar: "محيط المربع والمستطيل",
  domain: "geometry",
  hook_ar: "المحيط مسار حول الشكل: مربع 4×ضلع، مستطيل 2×(طول+عرض)",
  estimated_minutes: 6,
  icon: "□",
  visual: { kind: "custom", component: "perimeter-lab" },
  intuition_ar: [
    "المحيط هو مجموع أطوال الأضلاع الخارجية حول الشكل.",
    "محيط المربع = 4 ضرب طول الضلع.",
    "محيط المستطيل = 2 ضرب (الطول + العرض).",
    "المحيط ليس المساحة — لا تضرب الطول في العرض عندما يُطلب المحيط.",
  ],
  trick_ar: {
    statement: "اجمع الأضلاع حول الشكل، أو استخدم الصيغة الجاهزة مباشرة.",
    steps: [
      "مربع؟ اضرب الضلع في 4",
      "مستطيل؟ اجمع الطول والعرض ثم اضرب في 2",
      "عكسياً: اقسم المحيط على 4 للمربع، أو نصف المحيط ثم اطرح الضلع المعلوم للمستطيل",
    ],
    time_target_sec: 18,
    example_ar:
      "مستطيل 8 سم × 3 سم: المحيط = 2 × (8 + 3) = 22 سم. ومربع ضلعه 5: المحيط = 4 × 5 = 20.",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "per-01",
      prompt_ar: "مربع ضلعه 7 سم. كم محيطه؟",
      choices_ar: ["14 سم", "21 سم", "28 سم", "49 سم"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب الضلع في 2 فقط.",
        1: "ضُرب الضلع في 3.",
        3: "حُسبت المساحة بدل المحيط.",
      },
      solve_ar: "محيط المربع = 4 × 7 = 28 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-02",
      prompt_ar: "مستطيل طوله 12 م وعرضه 5 م. كم محيطه؟",
      choices_ar: ["17 م", "34 م", "60 م", "24 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الطول والعرض دون ضرب في 2.",
        2: "حُسبت المساحة بدل المحيط.",
        3: "ضُرب الطول في 2 فقط.",
      },
      solve_ar: "المحيط = 2 × (12 + 5) = 2 × 17 = 34 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-03",
      prompt_ar: "إطار صورة مربع محيطه 36 سم. كم طول ضلعه؟",
      choices_ar: ["6 سم", "9 سم", "12 سم", "18 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم المحيط على 6.",
        2: "قُسم المحيط على 3.",
        3: "قُسم المحيط على 2.",
      },
      solve_ar: "ضلع المربع = المحيط تقسيم 4 = 36 تقسيم 4 = 9 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-04",
      prompt_ar:
        "ملعب مستطيل محيطه 80 م، وطوله 25 م. كم عرضه؟",
      choices_ar: ["10 م", "15 م", "30 م", "55 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح الطول من نصف محيط خاطئ.",
        2: "قُسم المحيط على الطول تقريباً.",
        3: "طُرح الطول من المحيط دون نصف المحيط.",
      },
      solve_ar:
        "نصف المحيط = 80 تقسيم 2 = 40. العرض = 40 ناقص 25 = 15 م.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-05",
      prompt_ar: "بلاطة مربعة ضلعها 4.5 م. كم محيطها؟",
      choices_ar: ["9 م", "13.5 م", "18 م", "20.25 م"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب الضلع في 2.",
        1: "ضُرب الضلع في 3.",
        3: "حُسبت المساحة بدل المحيط.",
      },
      solve_ar: "المحيط = 4 × 4.5 = 18 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-06",
      prompt_ar:
        "طاولة مستطيلة 9 سم × 6 سم. طالب حسب 9 × 6 = 54 وقال هذا المحيط. ما المحيط الصحيح؟",
      choices_ar: ["15 سم", "30 سم", "54 سم", "108 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الضلعان دون ضرب في 2.",
        2: "هذا ناتج المساحة — المصيدة المذكورة.",
        3: "ضُوعفت المساحة خطأ.",
      },
      solve_ar:
        "54 هي المساحة لا المحيط. المحيط = 2 × (9 + 6) = 2 × 15 = 30 سم.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-07",
      prompt_ar: "حديقة مربعة محيطها 64 م. كم طول الضلع؟",
      choices_ar: ["8 م", "16 م", "32 م", "256 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم المحيط على 8.",
        2: "قُسم المحيط على 2.",
        3: "ضُرب المحيط في نفسه خطأ.",
      },
      solve_ar: "الضلع = 64 تقسيم 4 = 16 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-08",
      prompt_ar:
        "مستطيل عرضه ثلث طوله، والطوال 15 سم. كم المحيط؟",
      choices_ar: ["20 سم", "40 سم", "45 سم", "60 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الطول والعرض فقط.",
        2: "ضُرب الطول في 3.",
        3: "حُسبت مساحة أو ضوعف خطأ.",
      },
      solve_ar:
        "العرض = 15 تقسيم 3 = 5. المحيط = 2 × (15 + 5) = 2 × 20 = 40 سم.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-09",
      prompt_ar:
        "سلك بطول 48 سم يُشكَّل مربعاً. كم طول ضلع المربع؟",
      choices_ar: ["8 سم", "12 سم", "16 سم", "24 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على 6.",
        2: "قُسم على 3.",
        3: "قُسم على 2.",
      },
      solve_ar: "طول السلك هو المحيط. الضلع = 48 تقسيم 4 = 12 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-10",
      prompt_ar:
        "مستطيل محيطه 54 م، وطوله يزيد عن عرضه بـ 7 م. كم طوله؟",
      choices_ar: ["10 م", "17 م", "27 م", "34 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب العرض بدل الطول.",
        2: "أُخذ نصف المحيط كطول.",
        3: "ضُوعف أحد الأبعاد خطأ.",
      },
      solve_ar:
        "نصف المحيط = 27 = طول + عرض. ليكن العرض س والطول س + 7. إذن 2س + 7 = 27، 2س = 20، س = 10. الطول = 17 م.",
      trick_ref: "perimeter",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-11",
      prompt_ar: "مستطيل 11 سم × 4 سم. كم محيطه؟",
      choices_ar: ["15 سم", "30 سم", "44 سم", "22 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان فقط.",
        2: "حُسبت المساحة.",
        3: "ضُرب الطول في 2 فقط.",
      },
      solve_ar: "المحيط = 2 × (11 + 4) = 2 × 15 = 30 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-12",
      prompt_ar:
        "مربع ومستطيل لهما نفس المحيط 40 سم. ضلع المربع 10 سم، وطول المستطيل 14 سم. كم عرض المستطيل؟",
      choices_ar: ["4 سم", "6 سم", "8 سم", "10 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من نصف محيط خاطئ.",
        2: "طُرح 14 من 22.",
        3: "أُخذ ضلع المربع.",
      },
      solve_ar:
        "نصف محيط المستطيل = 20. العرض = 20 ناقص 14 = 6 سم. (ضلع المربع يؤكد المحيط 4×10=40).",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-13",
      prompt_ar: "رصيف مربع طول ضلعه 2.5 م. كم محيطه؟",
      choices_ar: ["5 م", "7.5 م", "10 م", "6.25 م"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب في 2.",
        1: "ضُرب في 3.",
        3: "حُسبت المساحة.",
      },
      solve_ar: "المحيط = 4 × 2.5 = 10 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-14",
      prompt_ar:
        "لافتة مستطيلة محيطها 26 م وعرضها 4 م. كم طولها؟",
      choices_ar: ["5 م", "9 م", "11 م", "18 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من رقم خاطئ.",
        2: "طُرح العرض من المحيط دون التنصيف.",
        3: "طُرح من المحيط مباشرة: 26−4.",
      },
      solve_ar: "نصف المحيط = 13. الطول = 13 ناقص 4 = 9 م.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-15",
      prompt_ar:
        "حبل بطول 60 م يحيط بمستطيل عرضه 8 م. كم الطول؟",
      choices_ar: ["14 م", "22 م", "30 م", "44 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من نصف محيط خاطئ.",
        2: "أُخذ نصف الحبل كطول.",
        3: "ضُوعف ناتج خاطئ.",
      },
      solve_ar: "نصف المحيط = 30. الطول = 30 ناقص 8 = 22 م.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-16",
      prompt_ar:
        "مستطيل أبعاده 8 م و 3 م. حسب شخص 8 × 3 = 24 وظنّه المحيط. ما المحيط الصحيح؟",
      choices_ar: ["11 م", "22 م", "24 م", "48 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان فقط.",
        2: "هذا ناتج المساحة — المصيدة.",
        3: "ضُوعفت المساحة خطأ.",
      },
      solve_ar:
        "24 هي المساحة لا المحيط. المحيط = 2 × (8 + 3) = 22 م.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-17",
      prompt_ar:
        "مستطيل طوله ضعف عرضه، والعرض 7 سم. كم المحيط؟",
      choices_ar: ["21 سم", "28 سم", "42 سم", "98 سم"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع الطول والعرض فقط.",
        1: "ضُرب العرض في 4 كأنّه مربع.",
        3: "حُسبت المساحة.",
      },
      solve_ar:
        "الطول = 2 × 7 = 14. المحيط = 2 × (14 + 7) = 2 × 21 = 42 سم.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-18",
      prompt_ar: "إطار مستطيل 16 سم × 9 سم. كم طول الإطار كاملاً (المحيط)؟",
      choices_ar: ["25 سم", "50 سم", "144 سم", "32 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان فقط.",
        2: "حُسبت المساحة.",
        3: "ضُرب الطول في 2 فقط.",
      },
      solve_ar: "المحيط = 2 × (16 + 9) = 2 × 25 = 50 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "per-f01",
      prompt_ar:
        "مربع ضلعه يزيد 3 سم عن ضلع مربع آخر محيطه 20 سم. كم محيط المربع الأكبر؟",
      choices_ar: ["23 سم", "26 سم", "32 سم", "35 سم"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُضيف 3 إلى المحيط مباشرة.",
        1: "أُضيف 6 إلى المحيط.",
        3: "أُضيف 3×5 خطأ.",
      },
      solve_ar:
        "ضلع الصغير = 20 تقسيم 4 = 5. ضلع الكبير = 8. محيطه = 4 × 8 = 32 سم.",
      trick_ref: "perimeter",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f02",
      prompt_ar:
        "مستطيل محيطه 100 م وطوله 30 م. كم عرضه؟",
      choices_ar: ["20 م", "25 م", "40 م", "70 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم المحيط على 4.",
        2: "قُسم المحيط على الطول تقريباً.",
        3: "طُرح الطول من المحيط.",
      },
      solve_ar: "نصف المحيط = 50. العرض = 50 ناقص 30 = 20 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f03",
      prompt_ar:
        "شبك يحيط بقطعة أرض مربعة ضلعها 18 م. كم طول الشبك؟",
      choices_ar: ["36 م", "54 م", "72 م", "324 م"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب في 2.",
        1: "ضُرب في 3.",
        3: "حُسبت المساحة.",
      },
      solve_ar: "طول الشبك = المحيط = 4 × 18 = 72 م.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f04",
      prompt_ar: "مستطيل طوله 13 سم وعرضه 7 سم. كم محيطه؟",
      choices_ar: ["20 سم", "40 سم", "91 سم", "26 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان فقط.",
        2: "حُسبت المساحة بدل المحيط.",
        3: "ضُرب الطول في 2 فقط.",
      },
      solve_ar: "المحيط = 2 × (13 + 7) = 40 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f05",
      prompt_ar: "مربع محيطه يساوي محيط مستطيل 10×6. كم ضلع المربع؟",
      choices_ar: ["6", "8", "10", "16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ عرض المستطيل.",
        2: "أُخذ طول المستطيل.",
        3: "أُخذ محيط المستطيل دون قسمة على 4.",
      },
      solve_ar:
        "محيط المستطيل = 2 × (10 + 6) = 32. ضلع المربع = 32 تقسيم 4 = 8.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f06",
      prompt_ar:
        "مسار حول ملعب مستطيل يُقطع مرتين فيحصّل العدّاء 120 م. كم محيط الملعب مرة واحدة؟",
      choices_ar: ["30 م", "60 م", "90 م", "120 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على 4.",
        2: "قُسم على كسر خاطئ.",
        3: "أُخذت المسافة كاملة كأنها محيط واحد.",
      },
      solve_ar: "دورتان = 120، فالمحيط مرة واحدة = 120 تقسيم 2 = 60 م.",
      trick_ref: "perimeter",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "per-f07",
      prompt_ar: "مستطيل أبعاده 20 سم و 5 سم. كم محيطه؟",
      choices_ar: ["25 سم", "50 سم", "100 سم", "40 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان فقط.",
        2: "حُسبت المساحة.",
        3: "ضُرب الطول في 2 فقط.",
      },
      solve_ar: "المحيط = 2 × (20 + 5) = 50 سم.",
      trick_ref: "perimeter",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
