import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const rectArea: Skill = {
  id: "rect-area",
  title_ar: "مساحة المستطيل والمربع",
  domain: "geometry",
  hook_ar: "المساحة = الطول × العرض، وللمربع الضلع × الضلع",
  estimated_minutes: 7,
  icon: "▭",
  visual: { kind: "custom", component: "rect-area-lab" },
  intuition_ar: [
    "مساحة المستطيل = الطول ضرب العرض.",
    "مساحة المربع = الضلع ضرب نفسه.",
    "إذا عرفت المحيط وضرباً واحداً: نصف المحيط ناقص الضلع المعلوم يعطي الضلع الآخر، ثم اضرب للمساحة.",
    "المساحة ليست المحيط — لا تجمع الأضلاع عندما يُطلب الملء الداخلي.",
  ],
  trick_ar: {
    statement: "اضرب البعدين. إن نُقص بُعد فاستخرجه من المحيط أولاً.",
    steps: [
      "مستطيل معلوم البعدين: اضرب الطول في العرض",
      "مربع: اضرب الضلع في نفسه",
      "من المحيط + ضلع: العرض = نصف المحيط ناقص الطول، ثم اضرب",
    ],
    time_target_sec: 20,
    example_ar:
      "مستطيل 9 × 4 مساحته 36. وإن كان المحيط 28 والطول 10، فالعرض = 14 ناقص 10 = 4، والمساحة = 40.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ra-01",
      prompt_ar: "مستطيل طوله 8 م وعرضه 5 م. كم مساحته؟",
      choices_ar: ["13 م²", "26 م²", "40 م²", "80 م²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع البعدان (محيط/2).",
        1: "حُسب المحيط بدل المساحة.",
        3: "ضُوعفت المساحة الصحيحة.",
      },
      solve_ar: "المساحة = 8 × 5 = 40 م².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-02",
      prompt_ar: "مربع ضلعه 9 سم. كم مساحته؟",
      choices_ar: ["18 سم²", "36 سم²", "81 سم²", "27 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب الضلع في 2.",
        1: "حُسب المحيط بدل المساحة.",
        3: "ضُرب الضلع في 3.",
      },
      solve_ar: "مساحة المربع = 9 × 9 = 81 سم².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-03",
      prompt_ar: "بلاط مستطيل 12 سم × 3 سم. كم مساحته؟",
      choices_ar: ["15 سم²", "30 سم²", "36 سم²", "72 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        1: "حُسب المحيط.",
        3: "ضُوعفت المساحة.",
      },
      solve_ar: "المساحة = 12 × 3 = 36 سم².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-04",
      prompt_ar:
        "حديقة مستطيلة محيطها 40 م وطولها 12 م. كم مساحتها؟",
      choices_ar: ["48 م²", "96 م²", "120 م²", "160 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب العرض في طول خاطئ.",
        2: "ضُرب الطول في 10 بدل العرض الصحيح 8.",
        3: "ضُرب الطول في نصف المحيط.",
      },
      solve_ar:
        "نصف المحيط = 20. العرض = 20 ناقص 12 = 8. المساحة = 12 × 8 = 96 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-05",
      prompt_ar: "مربع مساحته 64 م². كم طول ضلعه؟",
      choices_ar: ["4 م", "8 م", "16 م", "32 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف الضلع الصحيح.",
        2: "قُسمت المساحة على 4 (محيط/ضلع).",
        3: "قُسمت المساحة على 2.",
      },
      solve_ar: "الضلع = √64 = 8 م.",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-06",
      prompt_ar:
        "طاولة مستطيلة مساحتها 48 سم² وعرضها 6 سم. كم طولها؟",
      choices_ar: ["6 سم", "8 سم", "14 سم", "42 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ العرض نفسه.",
        2: "جُمع أو طُرح بدل القسمة.",
        3: "طُرح العرض من المساحة.",
      },
      solve_ar: "الطول = المساحة تقسيم العرض = 48 تقسيم 6 = 8 سم.",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-07",
      prompt_ar:
        "لافتة مربعة ضلعها 5.5 م. كم مساحتها؟",
      choices_ar: ["11 م²", "22 م²", "30.25 م²", "27.5 م²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب الضلع في 2.",
        1: "حُسب المحيط.",
        3: "ضُرب الضلع في 5 بدل 5.5.",
      },
      solve_ar: "المساحة = 5.5 × 5.5 = 30.25 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-08",
      prompt_ar:
        "مستطيل محيطه 30 م وعرضه 4 م. كم مساحته؟",
      choices_ar: ["40 م²", "44 م²", "60 م²", "120 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "استُخدم طول خاطئ 10.",
        2: "ضُرب في 15 بدل الطول 11.",
        3: "خُلط بالمحيط × العرض.",
      },
      solve_ar:
        "نصف المحيط = 15. الطول = 15 ناقص 4 = 11. المساحة = 11 × 4 = 44 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-09",
      prompt_ar: "ملعب 15 م × 10 م. كم مساحته؟",
      choices_ar: ["25 م²", "50 م²", "150 م²", "300 م²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        1: "حُسب المحيط.",
        3: "ضُوعفت المساحة.",
      },
      solve_ar: "المساحة = 15 × 10 = 150 م².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-10",
      prompt_ar:
        "مربع ومستطيل متساويان في المساحة. ضلع المربع 6 سم، وعرض المستطيل 4 سم. كم طول المستطيل؟",
      choices_ar: ["6 سم", "9 سم", "10 سم", "12 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ ضلع المربع.",
        2: "قُسمت المساحة خطأ.",
        3: "ضُوعف العرض.",
      },
      solve_ar:
        "مساحة المربع = 36. طول المستطيل = 36 تقسيم 4 = 9 سم.",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-11",
      prompt_ar:
        "أرض مستطيلة طولها ضعف عرضها، والعرض 7 م. كم المساحة؟",
      choices_ar: ["49 م²", "98 م²", "28 م²", "14 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت مساحة مربع العرض فقط.",
        2: "حُسب المحيط أو جمع البعدين × شيء.",
        3: "جُمع البعدان فقط.",
      },
      solve_ar: "الطول = 14. المساحة = 14 × 7 = 98 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-12",
      prompt_ar: "مربع محيطه 28 سم. كم مساحته؟",
      choices_ar: ["28 سم²", "49 سم²", "56 سم²", "196 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ المحيط كأنه مساحة.",
        2: "ضُوعف المحيط أو حُسب خطأ.",
        3: "رُبّع المحيط بدل الضلع.",
      },
      solve_ar: "الضلع = 28 تقسيم 4 = 7. المساحة = 7 × 7 = 49 سم².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-13",
      prompt_ar: "سجادة 2.5 م × 4 م. كم مساحتها؟",
      choices_ar: ["6.5 م²", "10 م²", "13 م²", "20 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "حُسب المحيط.",
        3: "ضُوعفت المساحة.",
      },
      solve_ar: "المساحة = 2.5 × 4 = 10 م².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-14",
      prompt_ar:
        "مستطيل مساحته 72 م² وطوله 12 م. كم عرضه؟",
      choices_ar: ["6 م", "8 م", "12 م", "60 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "طُرح أو قُسّم خطأ جزئي.",
        2: "أُعيد الطول كما هو.",
        3: "طُرح الطول من المساحة بدل القسمة.",
      },
      solve_ar:
        "المساحة = طول × عرض، فالعرض = 72 تقسيم 12 = 6 م.",
      trick_ref: "rect-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-15",
      prompt_ar: "لوح خشب مربع مساحته 121 سم². كم طول ضلعه؟",
      choices_ar: ["10 سم", "11 سم", "12 سم", "22 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرّب الجذر خطأ.",
        2: "قُرّب الجذر للأعلى.",
        3: "قُسمت المساحة على 5.5 تقريباً.",
      },
      solve_ar: "الضلع = √121 = 11 سم.",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-16",
      prompt_ar:
        "غرفة مستطيلة محيط جدرانها الأرضية 56 م وطولها 18 م. كم مساحة الأرضية؟",
      choices_ar: ["180 م²", "198 م²", "216 م²", "252 م²"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب الطول في 11.",
        2: "ضُرب الطول في 12.",
        3: "ضُرب الطول في نصف المحيط.",
      },
      solve_ar:
        "نصف المحيط = 28. العرض = 28 ناقص 18 = 10. المساحة = 18 × 10 = 180 م².",
      trick_ref: "rect-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-17",
      prompt_ar: "مستطيل 16 سم × 5 سم. كم مساحته؟",
      choices_ar: ["21 سم²", "42 سم²", "80 سم²", "160 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        1: "حُسب المحيط.",
        3: "ضُوعفت المساحة.",
      },
      solve_ar: "المساحة = 16 × 5 = 80 سم².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-18",
      prompt_ar:
        "مربع ضلعه يزيد متراً واحداً عن عرض مستطيل 9×4. كم مساحة المربع؟",
      choices_ar: ["16 م²", "25 م²", "36 م²", "81 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "رُبّع العرض دون الزيادة.",
        2: "رُبّع 6.",
        3: "رُبّع طول المستطيل.",
      },
      solve_ar: "ضلع المربع = 4 + 1 = 5. المساحة = 25 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ra-f01",
      prompt_ar:
        "مستطيل محيطه 48 م وطوله ثلاثة أمثال عرضه. كم مساحته؟",
      choices_ar: ["72 م²", "96 م²", "108 م²", "144 م²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُربت أبعاد مربّع العرض فقط × شيء.",
        1: "استُخدم عرض 8 مع طول 12 خطأ.",
        3: "رُبّع أحد الأبعاد أو ضُرب خطأ.",
      },
      solve_ar:
        "نصف المحيط = 24 = طول + عرض = 3س + س = 4س، فـ س = 6. الطول = 18. المساحة = 18 × 6 = 108 م².",
      trick_ref: "rect-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f02",
      prompt_ar: "مربع ضلعه 12 سم. كم مساحته؟",
      choices_ar: ["24 سم²", "48 سم²", "144 سم²", "96 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ضُرب في 2.",
        1: "حُسب المحيط.",
        3: "ضُرب في 8.",
      },
      solve_ar: "المساحة = 12 × 12 = 144 سم².",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f03",
      prompt_ar:
        "مستطيل مساحته 90 م² وعرضه 6 م. كم طوله؟",
      choices_ar: ["12 م", "15 م", "18 م", "84 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على 7.5.",
        2: "قُسمت على 5.",
        3: "طُرح العرض من المساحة.",
      },
      solve_ar: "الطول = 90 تقسيم 6 = 15 م.",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f04",
      prompt_ar:
        "أرض محيطها 60 م وطولها 20 م. كم مساحتها؟",
      choices_ar: ["100 م²", "200 م²", "300 م²", "400 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب العرض في نفسه.",
        2: "ضُرب الطول في 15.",
        3: "ضُرب الطول في نصف المحيط.",
      },
      solve_ar:
        "نصف المحيط = 30. العرض = 10. المساحة = 20 × 10 = 200 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f05",
      prompt_ar:
        "مربعان ضلع أحدهما 3 م والآخر 4 م. كم مجموع مساحتيهما؟",
      choices_ar: ["7 م²", "12 م²", "25 م²", "49 م²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع الضلعان.",
        1: "ضُرب الضلعان.",
        3: "رُبّع مجموع الضلعين.",
      },
      solve_ar: "9 + 16 = 25 م².",
      trick_ref: "rect-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f06",
      prompt_ar: "مستطيل 7.5 × 4. كم مساحته؟",
      choices_ar: ["11.5", "23", "30", "60"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        1: "حُسب المحيط.",
        3: "ضُوعفت المساحة.",
      },
      solve_ar: "المساحة = 7.5 × 4 = 30.",
      trick_ref: "rect-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ra-f07",
      prompt_ar:
        "مستطيل مساحته ضعف مساحة مربع ضلعه 5 سم، وعرض المستطيل 5 سم. كم طوله؟",
      choices_ar: ["5 سم", "10 سم", "15 سم", "20 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ عرض المستطيل فقط.",
        2: "ضُربت مساحة المربع في 3.",
        3: "ضُوعفت مساحة المربع مرتين إضافيتين.",
      },
      solve_ar:
        "مساحة المربع = 25. مساحة المستطيل = 50. الطول = 50 تقسيم 5 = 10 سم.",
      trick_ref: "rect-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
