import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const specialTriangles: Skill = {
  id: "special-triangles",
  title_ar: "المثلثات الخاصة",
  domain: "geometry",
  hook_ar: "٣-٤-٥ ومضاعفاتها",
  estimated_minutes: 7,
  icon: "△",
  visual: { kind: "custom", component: "special-triangles-lab" },
  intuition_ar: [
    "مثلث قائم أضلاعه ٣ و٤ و٥ شائع جداً؛ أي مضاعف له قائم أيضاً: ٦-٨-١٠، ٩-١٢-١٥، ١٢-١٦-٢٠…",
    "إذا عرفت ضلعين من مضاعف ٣-٤-٥، أكمل الثالث بنفس المضاعف دون جذر طويل.",
    "افحص: هل الأضلاع بنسبة ٣:٤:٥؟ اقسم على ٣ أو ٤ أو ٥ لترى المضاعف.",
    "هذه المهارة للتعرّف السريع على النسبة؛ ليست درس الجذر والجبر العام للقائم.",
  ],
  trick_ar: {
    statement: "ابحث عن مضاعف ٣-٤-٥ ثم أكمل الضلع الناقص بنفس المضاعف.",
    steps: [
      "اقسم الأضلاع المعروفة على ٣ أو ٤ أو ٥ لمعرفة المضاعف",
      "اكتب الثلاثي: ٣ك و٤ك و٥ك",
      "املأ الناقص مباشرة",
    ],
    time_target_sec: 18,
    example_ar:
      "ضلعان ٦ و٨ في قائم: ٦=٣×٢ و٨=٤×٢ فالمضاعف ٢، والوتر =٥×٢=١٠.",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "st-01",
      prompt_ar:
        "مثلث قائم ضلعاه القائمان ٣ و٤. ما طول الوتر؟",
      choices_ar: ["5", "6", "7", "12"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع الضلعان.",
        2: "زِيد واحد على الأكبر.",
        3: "ضُرب الضلعان.",
      },
      solve_ar: "هذا ثلاثي ٣-٤-٥ مباشرة. الوتر = 5.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-02",
      prompt_ar:
        "مثلث قائم ضلعاه القائمان ٦ و٨. ما طول الوتر؟",
      choices_ar: ["10", "12", "14", "9"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع أو أُخذ مضاعف خاطئ.",
        2: "جُمع الضلعان.",
        3: "تُوُسّط بين ٦ و٨.",
      },
      solve_ar: "٦=٣×٢ و٨=٤×٢، فالمضاعف ٢. الوتر =٥×٢ = ١٠.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-03",
      prompt_ar:
        "مثلث قائم وتره ١٠ وأحد ضلعيه القائمين ٦. ما الضلع الآخر؟",
      choices_ar: ["8", "4", "16", "7"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُقص من الوتر خطأ.",
        2: "ضُرب أو جُمع بطريقة غير النسبة.",
        3: "قُدّر تقديراً دون النسبة.",
      },
      solve_ar: "٦ و١٠ = ٣×٢ و٥×٢، فالمضاعف ٢. الضلع الناقص =٤×٢ = ٨.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-04",
      prompt_ar:
        "مثلث قائم ضلعاه القائمان ٩ و١٢. ما طول الوتر؟",
      choices_ar: ["15", "18", "21", "13"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع.",
        2: "جُمع الضلعان.",
        3: "خُلط بثلاثي آخر.",
      },
      solve_ar: "٩=٣×٣ و١٢=٤×٣، فالمضاعف ٣. الوتر =٥×٣ = ١٥.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-05",
      prompt_ar:
        "مثلث قائم وتره ١٥ وأحد ضلعيه ٩. ما الضلع الآخر؟",
      choices_ar: ["12", "6", "18", "10"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق الوتر والضلع.",
        2: "جُمع ٩ و٩ أو ضُعّف خطأ.",
        3: "خُلط بمضاعف ٢.",
      },
      solve_ar: "٩ و١٥ = ٣×٣ و٥×٣. الضلع الناقص =٤×٣ = ١٢.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-06",
      prompt_ar:
        "أي مجموعة أضلاع تمثّل مضاعف ٣-٤-٥؟",
      choices_ar: ["6 و8 و10", "5 و5 و5", "2 و3 و4", "7 و8 و9"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا متساوي الأضلاع لا ٣-٤-٥.",
        2: "النسبة ليست ٣:٤:٥.",
        3: "أعداد متتالية بلا نسبة خاصة.",
      },
      solve_ar: "٦:٨:١٠ = ٣:٤:٥ بعد القسمة على ٢. إذن مضاعف صحيح.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-07",
      prompt_ar:
        "مثلث قائم ضلعاه القائمان ١٢ و١٦. ما طول الوتر؟",
      choices_ar: ["20", "24", "28", "18"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع.",
        2: "جُمع الضلعان.",
        3: "أُخذ متوسط تقريبي.",
      },
      solve_ar: "١٢=٣×٤ و١٦=٤×٤، فالمضاعف ٤. الوتر =٥×٤ = ٢٠.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-08",
      prompt_ar:
        "مثلث قائم وتره ٢٠ وأحد ضلعيه ١٢. ما الضلع الآخر؟",
      choices_ar: ["16", "8", "15", "14"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق الوتر والضلع.",
        2: "خُلط بثلاثي ١٥.",
        3: "قُدّر دون المضاعف.",
      },
      solve_ar: "١٢ و٢٠ = ٣×٤ و٥×٤. الضلع الناقص =٤×٤ = ١٦.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-09",
      prompt_ar:
        "سُلّم يلامس جداراً؛ بعده الأفقي ٩ والميل ١٥. ما ارتفاع نقطة التلامس على الجدار؟",
      choices_ar: ["12", "6", "18", "24"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق ١٥ و٩.",
        2: "جُمع ٩ و٩.",
        3: "ضُعّف الارتفاع خطأ.",
      },
      solve_ar: "٩ و١٥ مضاعف ٣ و٥ بعامل ٣، فالارتفاع =٤×٣ = ١٢.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-10",
      prompt_ar:
        "مثلث قائم أضلاعه ٣ك و٤ك و٥ك. إذا كان الضلع الأصغر ١٨، فما الوتر؟",
      choices_ar: ["30", "24", "36", "20"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا الضلع الأوسط ٤ك.",
        2: "ضُعّف الأصغر.",
        3: "خُلط بمضاعف خاطئ.",
      },
      solve_ar: "٣ك = ١٨ ⇒ ك = ٦. الوتر =٥ك = ٣٠.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-11",
      prompt_ar:
        "مثلث قائم ضلعاه القائمان ١٥ و٢٠. ما طول الوتر؟",
      choices_ar: ["25", "30", "35", "22"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع.",
        2: "جُمع الضلعان.",
        3: "قُدّر دون النسبة.",
      },
      solve_ar: "١٥=٣×٥ و٢٠=٤×٥، فالمضاعف ٥. الوتر =٥×٥ = ٢٥.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-12",
      prompt_ar:
        "أي قيمة تكمل الثلاثي ٩ و؟ و١٥ ليكون مضاعف ٣-٤-٥؟",
      choices_ar: ["12", "10", "14", "6"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "خُلط بمضاعف ٢.",
        2: "قُدّر بين ٩ و١٥.",
        3: "أُخذ فرق ١٥ و٩.",
      },
      solve_ar: "٩ و١٥ = ٣×٣ و٥×٣، فالناقص ٤×٣ = ١٢.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-13",
      prompt_ar:
        "مثلث قائم وتره ٣٠ وأحد ضلعيه ٢٤. ما الضلع الآخر؟",
      choices_ar: ["18", "12", "20", "26"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق الوتر والضلع.",
        2: "خُلط بمضاعف آخر.",
        3: "قُدّر قرب الوتر.",
      },
      solve_ar: "٢٤ و٣٠ = ٤×٦ و٥×٦. الضلع الأصغر =٣×٦ = ١٨.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-14",
      prompt_ar:
        "خريطة مسار قائم: ٦ وحدات شرقاً ثم ٨ شمالاً. ما أقصر مسافة مباشرة لنقطة البداية؟",
      choices_ar: ["10", "14", "12", "9"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع ٦ و٨.",
        2: "ضُعّف أحد البعدين.",
        3: "تُوُسّط البعدين.",
      },
      solve_ar: "٦ و٨ مضاعف ٣-٤ بعامل ٢، فالمسافة المباشرة =١٠.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-15",
      prompt_ar:
        "مثلث قائم أضلاعه ٢١ و٢٨ و؟. ما الوتر؟",
      choices_ar: ["35", "42", "49", "30"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع أو ضُعّف ٢١.",
        2: "جُمع بطريقة خاطئة.",
        3: "خُلط بمضاعف ٦.",
      },
      solve_ar: "٢١=٣×٧ و٢٨=٤×٧، فالمضاعف ٧. الوتر =٥×٧ = ٣٥.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-16",
      prompt_ar:
        "وتر مثلث قائم = ٤٠ والضلع الأصغر = ٢٤. ما الضلع الأوسط؟",
      choices_ar: ["32", "28", "36", "20"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُدّر دون المضاعف.",
        2: "زِيد على الأصغر خطأ.",
        3: "أُخذ فرق الوتر والأصغر.",
      },
      solve_ar: "٢٤ و٤٠ = ٣×٨ و٥×٨. الأوسط =٤×٨ = ٣٢.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-17",
      prompt_ar:
        "أي الثلاثيات ليس مضاعف ٣-٤-٥؟",
      choices_ar: ["5 و12 و13", "9 و12 و15", "6 و8 و10", "12 و16 و20"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "٩-١٢-١٥ مضاعف ٣.",
        2: "٦-٨-١٠ مضاعف ٢.",
        3: "١٢-١٦-٢٠ مضاعف ٤.",
      },
      solve_ar:
        "٥-١٢-١٣ ثلاثي خاص آخر، لكنه ليس مضاعف ٣-٤-٥. الباقي كلها مضاعفات ٣-٤-٥.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-18",
      prompt_ar:
        "لوح خشب يشكّل قائمًا: الضلعان ٢٤ و٣٢. ما طول الوتر؟",
      choices_ar: ["40", "48", "56", "36"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع.",
        2: "جُمع الضلعان.",
        3: "قُدّر دون النسبة.",
      },
      solve_ar: "٢٤=٣×٨ و٣٢=٤×٨، فالمضاعف ٨. الوتر =٥×٨ = ٤٠.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "st-f01",
      prompt_ar: "مثلث قائم ضلعاه ٣ و٤. ما محيطه؟",
      choices_ar: ["12", "10", "7", "15"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا الوتر فقط.",
        2: "جُمع ضلعان فقط.",
        3: "خُلط بمضاعف ٣ للوتر.",
      },
      solve_ar: "الوتر ٥، فالمحيط = ٣+٤+٥ = ١٢.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f02",
      prompt_ar: "مثلث قائم وتره ٢٥ وأحد ضلعيه ١٥. ما الضلع الآخر؟",
      choices_ar: ["20", "10", "18", "22"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق الوتر والضلع.",
        2: "قُدّر دون المضاعف.",
        3: "قُرّب نحو الوتر.",
      },
      solve_ar: "١٥ و٢٥ = ٣×٥ و٥×٥. الناقص =٤×٥ = ٢٠.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f03",
      prompt_ar: "إذا كان المضاعف ك=٩ في ٣-٤-٥، فما الوتر؟",
      choices_ar: ["45", "36", "27", "40"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا ٤ك.",
        2: "هذا ٣ك.",
        3: "مضاعف خاطئ.",
      },
      solve_ar: "الوتر =٥×٩ = ٤٥.",
      trick_ref: "special-triangles",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f04",
      prompt_ar:
        "مسار قائم ١٨ شرقاً و٢٤ شمالاً. ما المسافة المباشرة؟",
      choices_ar: ["30", "36", "42", "28"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف البعدين.",
        2: "جُمع البعدان.",
        3: "قُدّر دون النسبة.",
      },
      solve_ar: "١٨ و٢٤ = ٣×٦ و٤×٦، فالمسافة =٥×٦ = ٣٠.",
      trick_ref: "special-triangles",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f05",
      prompt_ar:
        "مثلث قائم أضلاعه ٤٥ و٦٠ و؟. ما الوتر؟",
      choices_ar: ["75", "90", "105", "70"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع نصف الأضلاع.",
        2: "جُمع الضلعان.",
        3: "قُدّر دون المضاعف.",
      },
      solve_ar: "٤٥=٣×١٥ و٦٠=٤×١٥، فالمضاعف ١٥. الوتر =٥×١٥ = ٧٥.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f06",
      prompt_ar:
        "أي قيمة للمضاعف ك تجعل الأضلاع ٣ك و٤ك و٥ك محيطها ٦٠؟",
      choices_ar: ["5", "4", "6", "3"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "٦٠ تقسيم ١٥ = ٤، لا تقسيم ١٢.",
        2: "قُسم المحيط على ١٠ خطأ.",
        3: "قُسم على ٢٠.",
      },
      solve_ar: "المحيط =١٢ك = ٦٠ ⇒ ك = ٥.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "st-f07",
      prompt_ar: "مثلث قائم وتره ٣٥ وأصغر ضلعيه ٢١. ما الضلع الأوسط؟",
      choices_ar: ["28", "14", "30", "24"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ فرق الوتر والضلع.",
        2: "قُدّر قرب الوتر.",
        3: "خُلط بمضاعف ٦.",
      },
      solve_ar: "٢١ و٣٥ = ٣×٧ و٥×٧. الأوسط =٤×٧ = ٢٨.",
      trick_ref: "special-triangles",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
