import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const surfaceArea: Skill = {
  id: "surface-area",
  title_ar: "المساحة السطحية",
  domain: "geometry",
  hook_ar: "وجوه الشكل — ليست الحجم",
  estimated_minutes: 8,
  icon: "▣",
  visual: { kind: "custom", component: "surface-area-lab" },
  intuition_ar: [
    "المساحة السطحية = مجموع مساحات كل الوجوه الخارجية للمجسم.",
    "المكعب له 6 وجوه مربعة متساوية: المساحة السطحية = 6 × (الضلع)².",
    "متوازي المستطيلات: 2 × (طول×عرض + طول×ارتفاع + عرض×ارتفاع).",
    "الحجم يملأ الداخل؛ المساحة السطحية تغطي الخارج — لا تخلط بينهما.",
  ],
  trick_ar: {
    statement: "اجمع وجوه المجسم؛ للمكعب 6 مربعات، ولمتوازي المستطيلات زوجان لكل بُعد.",
    steps: [
      "حدّد: مكعب أم متوازي مستطيلات؟",
      "مكعب: 6 × ضلع × ضلع",
      "متوازي: 2 × (طول×عرض + طول×ارتفاع + عرض×ارتفاع)",
    ],
    time_target_sec: 24,
    example_ar:
      "صندوق أبعاده 2 و3 و4: الوجوه 2×3 و2×4 و3×4 مساحاتها 6 و8 و12. المجموع 26، والمساحة السطحية 2×26 = 52.",
  },
  timing: {
    excellent_sec: 24,
    good_sec: 34,
    ok_sec: 46,
    slow_sec: 60,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "sa-01",
      prompt_ar: "مكعب ضلعه 3 سم. ما مساحته السطحية؟",
      choices_ar: ["27 سم²", "36 سم²", "54 سم²", "18 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا حجم المكعب لا مساحته السطحية.",
        1: "حُسبت 4 وجوه فقط بدل 6.",
        3: "حُسبت مساحة وجهين فقط.",
      },
      solve_ar:
        "مساحة الوجه الواحد = 3 × 3 = 9. للمكعب 6 وجوه: المساحة السطحية = 6 × 9 = 54 سم².",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-02",
      prompt_ar: "مكعب ضلعه 4. ما مساحته السطحية؟",
      choices_ar: ["64", "96", "48", "16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا حجم المكعب.",
        2: "حُسبت 3 وجوه بدل 6.",
        3: "هذه مساحة وجه واحد فقط.",
      },
      solve_ar: "مساحة الوجه = 4 × 4 = 16. المساحة السطحية = 6 × 16 = 96.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-03",
      prompt_ar:
        "صندوق على شكل متوازي مستطيلات أبعاده 2 و3 و5. ما مساحته السطحية؟",
      choices_ar: ["30", "62", "31", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم (2×3×5) لا المساحة السطحية.",
        2: "جُمعت مساحات الأزواج دون ضربها في 2.",
        3: "نُسي أحد الأزواج أو حُسب خطأ.",
      },
      solve_ar:
        "مجموع مساحات الأزواج = 2×3 + 2×5 + 3×5 = 6 + 10 + 15 = 31. المساحة السطحية = 2 × 31 = 62.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-04",
      prompt_ar: "مكعب ضلعه 5 سم. ما مساحته السطحية؟",
      choices_ar: ["125 سم²", "150 سم²", "100 سم²", "25 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "حُسبت 4 وجوه فقط.",
        3: "هذه مساحة وجه واحد.",
      },
      solve_ar: "مساحة الوجه = 25. المساحة السطحية = 6 × 25 = 150 سم².",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-05",
      prompt_ar: "متوازي مستطيلات أبعاده 1 و4 و6. ما مساحته السطحية؟",
      choices_ar: ["24", "68", "34", "48"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي ضرب مجموع الأزواج في 2.",
        3: "حُسب زوجان فقط ثم ضُربا في 2.",
      },
      solve_ar:
        "1×4 + 1×6 + 4×6 = 4 + 6 + 24 = 34. المساحة السطحية = 2 × 34 = 68.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-06",
      prompt_ar: "مكعب مساحته السطحية 96. ما طول ضلعه؟",
      choices_ar: ["4", "6", "8", "16"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسمت المساحة على عدد وجوه خاطئ.",
        2: "أُخذ جذر المساحة السطحية مباشرة.",
        3: "هذه مساحة الوجه لا الضلع.",
      },
      solve_ar:
        "المساحة السطحية = 6 × (الضلع)² = 96. إذن (الضلع)² = 96 تقسيم 6 = 16. الضلع = 4.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-07",
      prompt_ar: "علبة هدايا أبعادها 3 و3 و8. ما مساحتها السطحية؟",
      choices_ar: ["72", "114", "57", "96"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم (3×3×8).",
        2: "نُسي الضرب في 2.",
        3: "حُسبت وجوه ناقصة.",
      },
      solve_ar:
        "3×3 + 3×8 + 3×8 = 9 + 24 + 24 = 57. المساحة السطحية = 2 × 57 = 114.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-08",
      prompt_ar: "مكعب ضلعه 2. ما مساحته السطحية؟",
      choices_ar: ["8", "12", "24", "6"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        1: "حُسبت 3 وجوه.",
        3: "حُسبت وجوه بعدد خاطئ.",
      },
      solve_ar: "مساحة الوجه = 4. المساحة السطحية = 6 × 4 = 24.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-09",
      prompt_ar: "صندوق شحن أبعاده 4 و5 و6. ما مساحته السطحية؟",
      choices_ar: ["120", "148", "74", "240"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي الضرب في 2.",
        3: "ضُربت الأبعاد بطريقة غير صحيحة للمساحة.",
      },
      solve_ar:
        "4×5 + 4×6 + 5×6 = 20 + 24 + 30 = 74. المساحة السطحية = 2 × 74 = 148.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-10",
      prompt_ar: "مكعب حجمه 27. ما مساحته السطحية؟",
      choices_ar: ["27", "36", "54", "81"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُعيد الحجم كما هو.",
        1: "حُسبت 4 وجوه فقط بعد إيجاد الضلع.",
        3: "ضُرب الضلع في عدد وجوه خطأ.",
      },
      solve_ar:
        "حجم المكعب = (الضلع)³ = 27، فالضلع = 3. المساحة السطحية = 6 × 9 = 54.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-11",
      prompt_ar: "متوازي مستطيلات أبعاده 2 و2 و7. ما مساحته السطحية؟",
      choices_ar: ["28", "64", "32", "48"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي الضرب في 2.",
        3: "جُمعت مساحات دون اكتمال الصيغة.",
      },
      solve_ar:
        "2×2 + 2×7 + 2×7 = 4 + 14 + 14 = 32. المساحة السطحية = 2 × 32 = 64.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-12",
      prompt_ar: "مكعب مساحته السطحية 150. ما طول ضلعه؟",
      choices_ar: ["5", "6", "25", "30"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسمت المساحة على عدد خاطئ.",
        2: "هذه مساحة الوجه لا الضلع.",
        3: "قُسمت المساحة السطحية على 5 فقط.",
      },
      solve_ar:
        "6 × (الضلع)² = 150. (الضلع)² = 25. الضلع = 5.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-13",
      prompt_ar: "ثلاجة صغيرة أبعادها 2 و4 و5. ما مساحتها السطحية؟",
      choices_ar: ["40", "76", "38", "80"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي الضرب في 2.",
        3: "جُمعت أزواج بطريقة مضاعفة خطأ.",
      },
      solve_ar:
        "2×4 + 2×5 + 4×5 = 8 + 10 + 20 = 38. المساحة السطحية = 2 × 38 = 76.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-14",
      prompt_ar: "مكعب ضلعه 10. ما مساحته السطحية؟",
      choices_ar: ["1000", "600", "400", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "حُسبت 4 وجوه.",
        3: "هذه مساحة وجه واحد.",
      },
      solve_ar: "مساحة الوجه = 100. المساحة السطحية = 6 × 100 = 600.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-15",
      prompt_ar: "صندوق أبعاده 3 و4 و5. ما مساحته السطحية؟",
      choices_ar: ["60", "94", "47", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي الضرب في 2.",
        3: "ضُربت الأبعاد كلها ثم رُقّم خطأ.",
      },
      solve_ar:
        "3×4 + 3×5 + 4×5 = 12 + 15 + 20 = 47. المساحة السطحية = 2 × 47 = 94.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-16",
      prompt_ar:
        "مكعبان متطابقان ضلع كل منهما 2، وُضعا ملتصقين بوجه كامل. ما المساحة السطحية للمجسم الناتج؟",
      choices_ar: ["48", "40", "36", "24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت مساحتا المكعبين دون طرح الوجهين المتلامسين.",
        2: "طُرح أكثر من اللازم.",
        3: "حُسبت مساحة مكعب واحد فقط.",
      },
      solve_ar:
        "مساحة مكعب واحد = 6 × 4 = 24. مجموع مكعبين منفصلين = 48. عند الالتصاق يختفي وجهان مساحة كل منهما 4، فيُطرح 8. الناتج = 48 − 8 = 40.",
      trick_ref: "surface-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-17",
      prompt_ar:
        "لمتوازي مستطيلات أبعاده 2 و3 و4، احسب المساحة السطحية والحجم كعددين من الصيغتين. أي العدد الناتج أكبر؟",
      choices_ar: ["عدد المساحة السطحية", "عدد الحجم", "متساويان", "لا يكفي"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "الحجم العددي = 24، والمساحة السطحية = 52، فالحجم أصغر.",
        2: "العددان مختلفان: 52 ≠ 24.",
        3: "الأبعاد كافية لحساب الصيغتين ومقارنة الناتجين العدديين.",
      },
      solve_ar:
        "الحجم العددي = 2×3×4 = 24. المساحة السطحية = 2×(6+8+12) = 52. فعدد المساحة السطحية أكبر.",
      trick_ref: "surface-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-18",
      prompt_ar:
        "مكعب مساحته السطحية 24. ما طول ضلعه؟",
      choices_ar: ["2", "4", "6", "8"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذه مساحة الوجه.",
        2: "قُسمت المساحة على 4.",
        3: "خُلط بالحجم أو بعدد الوجوه خطأ.",
      },
      solve_ar:
        "6 × (الضلع)² = 24 ⇒ (الضلع)² = 4 ⇒ الضلع = 2.",
      trick_ref: "surface-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "sa-f01",
      prompt_ar: "مكعب ضلعه 7. ما مساحته السطحية؟",
      choices_ar: ["294", "343", "196", "49"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا الحجم.",
        2: "حُسبت 4 وجوه.",
        3: "هذه مساحة وجه واحد.",
      },
      solve_ar: "مساحة الوجه = 49. المساحة السطحية = 6 × 49 = 294.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f02",
      prompt_ar: "صندوق أبعاده 1 و5 و8. ما مساحته السطحية؟",
      choices_ar: ["40", "106", "53", "80"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "نُسي الضرب في 2.",
        3: "ضُربت بعض الأبعاد فقط.",
      },
      solve_ar:
        "1×5 + 1×8 + 5×8 = 5 + 8 + 40 = 53. المساحة السطحية = 2 × 53 = 106.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f03",
      prompt_ar: "مكعب مساحته السطحية 54. ما طول ضلعه؟",
      choices_ar: ["3", "9", "6", "27"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذه مساحة الوجه.",
        2: "قُسمت المساحة على 9.",
        3: "خُلط بالحجم.",
      },
      solve_ar:
        "6 × (الضلع)² = 54 ⇒ (الضلع)² = 9 ⇒ الضلع = 3.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f04",
      prompt_ar: "متوازي مستطيلات أبعاده 2 و6 و6. ما مساحته السطحية؟",
      choices_ar: ["72", "120", "96", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذا الحجم.",
        2: "حُسب زوج ناقص.",
        3: "نُسي الضرب في 2 جزئياً.",
      },
      solve_ar:
        "2×6 + 2×6 + 6×6 = 12 + 12 + 36 = 60. المساحة السطحية = 2 × 60 = 120.",
      trick_ref: "surface-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f05",
      prompt_ar:
        "مكعب ضلعه 4 ومتوازي مستطيلات أبعاده 2 و2 و8. أيّهما أكبر مساحة سطحية؟",
      choices_ar: ["المكعب", "المتوازي", "متساويان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "مساحة المتوازي = 72، والمكعب = 96.",
        2: "العددان مختلفان.",
        3: "يمكن حساب الاثنين.",
      },
      solve_ar:
        "المكعب: 6×16 = 96. المتوازي: 2×(2×2 + 2×8 + 2×8) = 2×(4+16+16) = 72. المكعب أكبر.",
      trick_ref: "surface-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f06",
      prompt_ar:
        "حوض زجاجي مفتوح من الأعلى أبعاده 3 و4 و5 (الارتفاع 5). ما مساحة الزجاج المستخدمة؟",
      choices_ar: ["94", "82", "74", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت المساحة السطحية الكاملة بما فيها الغطاء.",
        2: "نُسي القاعدة أو أحد الجوانب.",
        3: "هذا الحجم.",
      },
      solve_ar:
        "المساحة الكاملة = 2×(3×4 + 3×5 + 4×5) = 2×(12+15+20) = 94. بلا الغطاء العلوي مساحته 3×4 = 12، فالزجاج = 94 − 12 = 82.",
      trick_ref: "surface-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "sa-f07",
      prompt_ar: "مكعب ضلعه 8. ما مساحته السطحية؟",
      choices_ar: ["384", "512", "256", "64"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا الحجم.",
        2: "حُسبت 4 وجوه.",
        3: "هذه مساحة وجه واحد.",
      },
      solve_ar: "مساحة الوجه = 64. المساحة السطحية = 6 × 64 = 384.",
      trick_ref: "surface-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
