import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const triangleArea: Skill = {
  id: "triangle-area",
  title_ar: "مساحة المثلث",
  domain: "geometry",
  hook_ar: "مساحة المثلث = نصف × القاعدة × الارتفاع",
  estimated_minutes: 7,
  icon: "△",
  visual: { kind: "custom", component: "triangle-area-lab" },
  intuition_ar: [
    "مساحة المثلث نصف مساحة المستطيل الذي له نفس القاعدة والارتفاع.",
    "الصيغة: نصف ضرب القاعدة ضرب الارتفاع.",
    "أشيع خطأ: نسيان النصف والضرب فقط.",
    "القاعدة والارتفاع المتعامد عليها هما المطلوبان — لا أي ضلعين عشوائيين.",
  ],
  trick_ar: {
    statement: "اضرب القاعدة في الارتفاع، ثم خذ النصف فوراً.",
    steps: [
      "حدّد القاعدة والارتفاع العمودي عليها",
      "اضربهما",
      "اقسم على 2 (أو اضرب في نصف)",
    ],
    time_target_sec: 20,
    example_ar:
      "قاعدة 8 وارتفاع 6: المساحة = نصف × 8 × 6 = 24. وإن نُسي النصف يظهر 48 — وهذا فخ.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 42,
    slow_sec: 55,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ta-01",
      prompt_ar: "مثلث قاعدته 10 سم وارتفاعه 6 سم. كم مساحته؟",
      choices_ar: ["16 سم²", "30 سم²", "60 سم²", "8 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت القاعدة والارتفاع.",
        2: "نُسي النصف فضُرب فقط.",
        3: "قُسم الناتج الصحيح على أكثر من اللازم.",
      },
      solve_ar: "المساحة = نصف × 10 × 6 = 30 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-02",
      prompt_ar: "مثلث قاعدته 8 م وارتفاعه 5 م. كم مساحته؟",
      choices_ar: ["13 م²", "20 م²", "40 م²", "16 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُرب ثم قُسم خطأ.",
      },
      solve_ar: "المساحة = نصف × 8 × 5 = 20 م².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-03",
      prompt_ar: "مثلث قاعدته 12 سم وارتفاعه 7 سم. كم مساحته؟",
      choices_ar: ["19 سم²", "42 سم²", "84 سم²", "36 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام أخرى.",
      },
      solve_ar: "المساحة = نصف × 12 × 7 = 42 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-04",
      prompt_ar:
        "لافتة مثلثة قاعدتها 14 م وارتفاعها 9 م. كم مساحتها؟",
      choices_ar: ["23 م²", "63 م²", "126 م²", "56 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت القاعدة في 4.",
      },
      solve_ar: "المساحة = نصف × 14 × 9 = 63 م².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-05",
      prompt_ar:
        "مثلث مساحته 24 سم² وقاعدته 8 سم. كم ارتفاعه؟",
      choices_ar: ["3 سم", "6 سم", "12 سم", "16 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على القاعدة مباشرة دون ×2.",
        2: "نُسي أن الارتفاع = 2×مساحة÷قاعدة فقُسم عكسياً.",
        3: "ضُوعفت القاعدة أو طُرحت.",
      },
      solve_ar:
        "المساحة = نصف × قاعدة × ارتفاع، إذن 24 = نصف × 8 × ع، أي 24 = 4ع، فـ ع = 6 سم.",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-06",
      prompt_ar:
        "مثلث مساحته 45 م² وارتفاعه 9 م. كم قاعدته؟",
      choices_ar: ["5 م", "10 م", "15 م", "36 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على الارتفاع مباشرة.",
        2: "ضُوعفت القاعدة الصحيحة.",
        3: "طُرح الارتفاع من المساحة.",
      },
      solve_ar:
        "45 = نصف × ق × 9، أي 45 = (9/2)ق، فـ ق = 45 × 2 تقسيم 9 = 10 م.",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-07",
      prompt_ar:
        "حديقة مثلثة قاعدتها 16 م وارتفاعها 5 م. كم مساحتها؟",
      choices_ar: ["21 م²", "40 م²", "80 م²", "32 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 16 × 5 = 40 م².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-08",
      prompt_ar:
        "مثلث قاعدته ضعف ارتفاعه، والارتفاع 6 سم. كم المساحة؟",
      choices_ar: ["18 سم²", "36 سم²", "72 سم²", "12 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ نصف الناتج الصحيح فقط جزئياً.",
        2: "نُسي النصف.",
        3: "ضُرب الارتفاع في 2 فقط.",
      },
      solve_ar:
        "القاعدة = 12. المساحة = نصف × 12 × 6 = 36 سم².",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-09",
      prompt_ar:
        "شراع مثلث قاعدته 9 م وارتفاعه 4 م. شخص حسب 9 × 4 = 36. ما المساحة الصحيحة؟",
      choices_ar: ["13 م²", "18 م²", "36 م²", "72 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "هذا ناتج نسيان النصف — المصيدة.",
        3: "ضُوعف الناتج بلا نصف.",
      },
      solve_ar: "36 ناتج الضرب دون نصف. الصحيح = نصف × 9 × 4 = 18 م².",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-10",
      prompt_ar: "مثلث قاعدته 15 سم وارتفاعه 8 سم. كم مساحته؟",
      choices_ar: ["23 سم²", "60 سم²", "120 سم²", "45 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 15 × 8 = 60 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-11",
      prompt_ar:
        "مثلثان متطابقان لكل منهما قاعدة 6 وارتفاع 5. كم مجموع مساحتيهما؟",
      choices_ar: ["15", "30", "60", "11"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسبت مساحة واحد فقط.",
        2: "نُسي النصف في كل مثلث ثم جُمع.",
        3: "جُمعت القاعدة والارتفاع.",
      },
      solve_ar:
        "مساحة الواحد = نصف × 6 × 5 = 15. المجموع = 30.",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-12",
      prompt_ar:
        "مثلث مساحته 56 م² وقاعدته 14 م. كم الارتفاع؟",
      choices_ar: ["4 م", "8 م", "16 م", "28 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على القاعدة مباشرة.",
        2: "ضُوعف الارتفاع الصحيح.",
        3: "طُرح أو جُمع خطأ.",
      },
      solve_ar:
        "56 = نصف × 14 × ع، أي 56 = 7ع، فـ ع = 8 م.",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-13",
      prompt_ar: "مثلث قاعدته 7 سم وارتفاعه 10 سم. كم مساحته؟",
      choices_ar: ["17 سم²", "35 سم²", "70 سم²", "28 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 7 × 10 = 35 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-14",
      prompt_ar:
        "مثلث ارتفاعه نصف قاعدته، والقاعدة 20 م. كم المساحة؟",
      choices_ar: ["50 م²", "100 م²", "200 م²", "40 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ ربع الناتج الكامل خطأ.",
        2: "نُسي النصف في الصيغة.",
        3: "ضُربت القاعدة في كسر خاطئ.",
      },
      solve_ar:
        "الارتفاع = 10. المساحة = نصف × 20 × 10 = 100 م².",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-15",
      prompt_ar:
        "لوحة مثلثة قاعدتها 11 سم وارتفاعها 6 سم. كم مساحتها؟",
      choices_ar: ["17 سم²", "33 سم²", "66 سم²", "22 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 11 × 6 = 33 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-16",
      prompt_ar:
        "مثلث مساحته تساوي مساحة مستطيل 8 × 3، وقاعدة المثلث 8. كم ارتفاعه؟",
      choices_ar: ["3", "6", "12", "24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ ارتفاع المستطيل مباشرة دون مضاعفة.",
        2: "نُسي العلاقة مع النصف فعُكس الحساب.",
        3: "ضُربت المساحة في شيء زائد.",
      },
      solve_ar:
        "مساحة المستطيل = 24 = مساحة المثلث. 24 = نصف × 8 × ع، أي 24 = 4ع، فـ ع = 6.",
      trick_ref: "triangle-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-17",
      prompt_ar: "مثلث قاعدته 18 م وارتفاعه 4 م. كم مساحته؟",
      choices_ar: ["22 م²", "36 م²", "72 م²", "40 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 18 × 4 = 36 م².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-18",
      prompt_ar:
        "مثلث قاعدته 25 سم وارتفاعه 12 سم. كم مساحته؟",
      choices_ar: ["37 سم²", "150 سم²", "300 سم²", "125 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت القاعدة في 5.",
      },
      solve_ar: "المساحة = نصف × 25 × 12 = 150 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ta-f01",
      prompt_ar:
        "مثلث مساحته 84 م² وارتفاعه 12 م. كم القاعدة؟",
      choices_ar: ["7 م", "14 م", "28 م", "72 م"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على الارتفاع مباشرة.",
        2: "ضُوعفت القاعدة الصحيحة.",
        3: "طُرح الارتفاع من المساحة.",
      },
      solve_ar:
        "84 = نصف × ق × 12، أي 84 = 6ق، فـ ق = 14 م.",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f02",
      prompt_ar: "مثلث قاعدته 4.5 م وارتفاعه 8 م. كم مساحته؟",
      choices_ar: ["12.5 م²", "18 م²", "36 م²", "16 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت أرقام تقريبية.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 4.5 × 8 = 18 م².",
      trick_ref: "triangle-area",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f03",
      prompt_ar:
        "مثلثان يشتركان في نفس الارتفاع 10 سم، وقاعدتاهما 6 سم و 9 سم. كم مجموع المساحتين؟",
      choices_ar: ["15 سم²", "75 سم²", "150 سم²", "30 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمعت القاعدتان فقط.",
        2: "نُسي النصف للمجموع.",
        3: "حُسبت مساحة واحد فقط أو جُمع خطأ.",
      },
      solve_ar:
        "الأولى = نصف × 6 × 10 = 30. الثانية = نصف × 9 × 10 = 45. المجموع = 75 سم².",
      trick_ref: "triangle-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f04",
      prompt_ar: "مثلث قاعدته 13 سم وارتفاعه 4 سم. كم مساحته؟",
      choices_ar: ["17 سم²", "26 سم²", "52 سم²", "30 سم²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت أرقام جزئية.",
      },
      solve_ar: "المساحة = نصف × 13 × 4 = 26 سم².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f05",
      prompt_ar:
        "مثلث مساحته 100 سم² وقاعدته 20 سم. كم الارتفاع؟",
      choices_ar: ["5 سم", "10 سم", "20 سم", "40 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسمت المساحة على القاعدة مباشرة.",
        2: "أُخذت القاعدة كارتفاع.",
        3: "ضُوعف الارتفاع الصحيح.",
      },
      solve_ar:
        "100 = نصف × 20 × ع، أي 100 = 10ع، فـ ع = 10 سم.",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f06",
      prompt_ar:
        "سقف مثلث قاعدته 22 م وارتفاعه 7 م. كم مساحته؟",
      choices_ar: ["29 م²", "77 م²", "154 م²", "44 م²"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع البعدان.",
        2: "نُسي النصف.",
        3: "ضُربت القاعدة في 2.",
      },
      solve_ar: "المساحة = نصف × 22 × 7 = 77 م².",
      trick_ref: "triangle-area",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "ta-f07",
      prompt_ar:
        "مثلث مساحته ثلاثة أضعاف مثلث آخر قاعدته 8 وارتفاعه 5. إذا كانت قاعدة الكبير 12، فكم ارتفاعه؟",
      choices_ar: ["5", "10", "15", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ ارتفاع الصغير.",
        2: "ضُوعف الناتج الصحيح مرة إضافية.",
        3: "نُسي النصف عند الحل العكسي.",
      },
      solve_ar:
        "مساحة الصغير = نصف × 8 × 5 = 20. مساحة الكبير = 60. 60 = نصف × 12 × ع، أي 60 = 6ع، فـ ع = 10.",
      trick_ref: "triangle-area",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
