import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const unitsMeasure: Skill = {
  id: "units-measure",
  title_ar: "القياس وتحويل الوحدات",
  domain: "geometry",
  hook_ar: "سم ومتر — طول ومساحة",
  estimated_minutes: 7,
  icon: "↕",
  visual: { kind: "custom", component: "units-measure-lab" },
  intuition_ar: [
    "الطول: ١ م = ١٠٠ سم، و١ سم = ٠٫٠١ م.",
    "المساحة: ١ م² = ١٠٠ × ١٠٠ = ١٠٠٠٠ سم².",
    "الحجم خفيفاً: ١ م³ = ١٠٠ × ١٠٠ × ١٠٠ = ١٠٠٠٠٠٠ سم³.",
    "مصيدة شائعة: تحويل المساحة بعامل الطول فقط دون تربيعه.",
  ],
  trick_ar: {
    statement: "حدّد نوع الكمية أولاً: طول أم مساحة أم حجم، ثم ارفع عامل ١٠٠ للقوة المناسبة.",
    steps: [
      "طول: ×١٠٠ أو ÷١٠٠ بين م وسم",
      "مساحة: ×١٠٠٠٠ أو ÷١٠٠٠٠ بين م² وسم²",
      "لا تخلط عامل الطول مع عامل المساحة",
    ],
    time_target_sec: 20,
    example_ar:
      "٢ م² = ٢ × ١٠٠٠٠ = ٢٠٠٠٠ سم². بينما ٢ م = ٢٠٠ سم فقط.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "um-01",
      prompt_ar: "حوّل ٣ م إلى سم.",
      choices_ar: ["30 سم", "300 سم", "3000 سم", "0.03 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في ١٠ بدل ١٠٠.",
        2: "ضُرب في ١٠٠٠.",
        3: "قُسم بدل الضرب.",
      },
      solve_ar: "١ م = ١٠٠ سم، فـ ٣ م = ٣ × ١٠٠ = ٣٠٠ سم.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-02",
      prompt_ar: "حوّل ٢٥٠ سم إلى م.",
      choices_ar: ["2.5 م", "25 م", "0.25 م", "250 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠ فقط.",
        2: "قُسم على ١٠٠٠.",
        3: "لم يُحوَّل.",
      },
      solve_ar: "٢٥٠ ÷ ١٠٠ = ٢٫٥ م.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-03",
      prompt_ar: "حوّل ٢ م² إلى سم².",
      choices_ar: ["200 سم²", "2000 سم²", "20000 سم²", "10000 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "استُخدم عامل الطول ١٠٠ فقط.",
        1: "ضُرب في ١٠٠٠.",
        3: "حُوّل ١ م² فقط.",
      },
      solve_ar: "١ م² = ١٠٠٠٠ سم²، فـ ٢ م² = ٢٠٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-04",
      prompt_ar: "حوّل ٥٠٠٠ سم² إلى م².",
      choices_ar: ["0.5 م²", "5 م²", "50 م²", "0.05 م²"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠٠٠.",
        2: "قُسم على ١٠٠.",
        3: "قُسم على ١٠٠٠٠٠.",
      },
      solve_ar: "٥٠٠٠ ÷ ١٠٠٠٠ = ٠٫٥ م².",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-05",
      prompt_ar: "شريط طوله ٧٥ سم. كم طوله بالمتر؟",
      choices_ar: ["0.75 م", "7.5 م", "75 م", "0.075 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠.",
        2: "لم يُحوَّل.",
        3: "قُسم على ١٠٠٠.",
      },
      solve_ar: "٧٥ ÷ ١٠٠ = ٠٫٧٥ م.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-06",
      prompt_ar: "مساحة بلاطة ٠٫٣ م². كم تساوي بالسم²؟",
      choices_ar: ["30 سم²", "300 سم²", "3000 سم²", "30000 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "استُخدم عامل ١٠٠ فقط على ٠٫٣.",
        1: "ضُرب في ١٠٠٠.",
        3: "ضُرب بمعامل أكبر من ١٠٠٠٠.",
      },
      solve_ar: "٠٫٣ × ١٠٠٠٠ = ٣٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-07",
      prompt_ar: "أي تحويل صحيح؟",
      choices_ar: [
        "1 م² = 10000 سم²",
        "1 م² = 100 سم²",
        "1 م = 10000 سم",
        "1 سم² = 100 م²",
      ],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا عامل الطول لا المساحة.",
        2: "١ م = ١٠٠ سم لا ١٠٠٠٠.",
        3: "الاتجاه والمعامل مقلوبان.",
      },
      solve_ar: "١ م = ١٠٠ سم، فالمتر المربع = ١٠٠×١٠٠ = ١٠٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-08",
      prompt_ar: "حوّل ٤ م إلى سم، ثم قارن بالناتج إن حُوّلت ٤ م² بعامل ١٠٠ خطأ. ما التحويل الصحيح لـ ٤ م؟",
      choices_ar: ["400 سم", "40000 سم", "40 سم", "4 سم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "خُلط بعامل المساحة.",
        2: "ضُرب في ١٠.",
        3: "لم يُحوَّل.",
      },
      solve_ar: "٤ م = ٤ × ١٠٠ = ٤٠٠ سم. عامل المساحة لا يُستخدم للطول.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-09",
      prompt_ar: "طاولة مساحتها ١٥٠٠٠ سم². كم بالمتر المربع؟",
      choices_ar: ["1.5 م²", "15 م²", "0.15 م²", "150 م²"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠٠٠.",
        2: "قُسم على ١٠٠٠٠٠.",
        3: "قُسم على ١٠٠.",
      },
      solve_ar: "١٥٠٠٠ ÷ ١٠٠٠٠ = ١٫٥ م².",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-10",
      prompt_ar: "حوّل ٠٫٠٨ م³ إلى سم³ (تذكّر: ١ م³ = ١٠٠٠٠٠٠ سم³).",
      choices_ar: ["80000 سم³", "8000 سم³", "800 سم³", "800000 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُقص صفر من المعامل.",
        2: "استُخدم عامل المساحة تقريباً.",
        3: "ضُرب في ١٠⁷ خطأ.",
      },
      solve_ar: "٠٫٠٨ × ١٠٠٠٠٠٠ = ٨٠٠٠٠ سم³.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-11",
      prompt_ar: "حبل طوله ١٫٢ م. كم بالسم؟",
      choices_ar: ["12 سم", "120 سم", "1200 سم", "0.012 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في ١٠.",
        2: "ضُرب في ١٠٠٠.",
        3: "قُسم بدل الضرب.",
      },
      solve_ar: "١٫٢ × ١٠٠ = ١٢٠ سم.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-12",
      prompt_ar:
        "طالب حوّل ٣ م² إلى سم² بضرب ٣×١٠٠ فحصل على ٣٠٠. ما الخطأ؟",
      choices_ar: [
        "استخدم عامل الطول بدل عامل المساحة",
        "كان عليه القسمة لا الضرب",
        "الناتج صحيح",
        "كان عليه الضرب في ١٠ فقط",
      ],
      correct_index: 0,
      trap_explanations_ar: {
        1: "الاتجاه صحيح (م²→سم²) بالضرب، لكن المعامل خطأ.",
        2: "الناتج غير صحيح؛ الصحيح ٣٠٠٠٠.",
        3: "عامل ١٠ أضعف من المطلوب.",
      },
      solve_ar:
        "للمساحة يُضرب في ١٠٠٠٠ لا ١٠٠. ٣ م² = ٣٠٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-13",
      prompt_ar: "حوّل ٢٥٠٠٠٠ سم³ إلى م³.",
      choices_ar: ["0.25 م³", "2.5 م³", "0.025 م³", "25 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠٠٠٠٠ بخطأ صفري.",
        2: "قُسم على ١٠⁷.",
        3: "قُسم على ١٠٠٠٠.",
      },
      solve_ar: "٢٥٠٠٠٠ ÷ ١٠٠٠٠٠٠ = ٠٫٢٥ م³.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-14",
      prompt_ar: "أي مقدار أكبر؟",
      choices_ar: ["2 م", "150 سم", "0.5 م", "80 سم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "١٥٠ سم = ١٫٥ م أصغر من ٢ م.",
        2: "٠٫٥ م أصغر.",
        3: "٨٠ سم = ٠٫٨ م أصغر.",
      },
      solve_ar: "٢ م = ٢٠٠ سم، وهو أكبر من ١٥٠ سم و٠٫٥ م و٨٠ سم.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-15",
      prompt_ar: "لوحة مساحتها ٤ م². كم بالسم²؟",
      choices_ar: ["400 سم²", "4000 سم²", "40000 سم²", "400000 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عامل طول.",
        1: "عامل ١٠٠٠.",
        3: "عامل ١٠⁵.",
      },
      solve_ar: "٤ × ١٠٠٠٠ = ٤٠٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-16",
      prompt_ar:
        "قُطع خشب طوله ١٨٠ سم وعرض لوح آخر ١٫٥ م. أي الطولين أكبر؟",
      choices_ar: ["متساويان", "١٨٠ سم أكبر", "١٫٥ م أكبر", "لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "١٫٨ م لا يساوي ١٫٥ م.",
        2: "١٫٥ م = ١٥٠ سم أصغر من ١٨٠ سم.",
        3: "يمكن التوحيد والمقارنة.",
      },
      solve_ar: "١٨٠ سم = ١٫٨ م، وهو أكبر من ١٫٥ م.",
      trick_ref: "units-measure",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-17",
      prompt_ar: "أي جملة خاطئة؟",
      choices_ar: [
        "1 م = 100 سم",
        "1 م² = 100 سم²",
        "1 م² = 10000 سم²",
        "50 سم = 0.5 م",
      ],
      correct_index: 1,
      trap_explanations_ar: {
        0: "هذه صحيحة.",
        2: "هذه صحيحة.",
        3: "هذه صحيحة.",
      },
      solve_ar: "١ م² ≠ ١٠٠ سم²؛ الصحيح ١٠٠٠٠ سم². الخيار الثاني خاطئ.",
      trick_ref: "units-measure",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-18",
      prompt_ar: "حوّل ٦٫٥ م إلى سم.",
      choices_ar: ["65 سم", "650 سم", "6500 سم", "0.065 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في ١٠.",
        2: "ضُرب في ١٠٠٠.",
        3: "قُسم.",
      },
      solve_ar: "٦٫٥ × ١٠٠ = ٦٥٠ سم.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "um-f01",
      prompt_ar: "حوّل ٤٢٠ سم إلى م.",
      choices_ar: ["4.2 م", "42 م", "0.42 م", "420 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم على ١٠.",
        2: "قُسم على ١٠٠٠.",
        3: "لم يُحوَّل.",
      },
      solve_ar: "٤٢٠ ÷ ١٠٠ = ٤٫٢ م.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f02",
      prompt_ar: "حوّل ٠٫٧ م² إلى سم².",
      choices_ar: ["70 سم²", "700 سم²", "7000 سم²", "70000 سم²"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عامل ١٠٠.",
        1: "عامل ١٠٠٠.",
        3: "عامل ١٠⁵.",
      },
      solve_ar: "٠٫٧ × ١٠٠٠٠ = ٧٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f03",
      prompt_ar: "أي مقدار أصغر؟",
      choices_ar: ["90 سم", "1 م", "120 سم", "0.95 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "١ م = ١٠٠ سم أكبر من ٩٠.",
        2: "١٢٠ سم أكبر.",
        3: "٠٫٩٥ م = ٩٥ سم أكبر من ٩٠.",
      },
      solve_ar: "٩٠ سم أصغر من ١٠٠ سم و١٢٠ سم و٩٥ سم.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f04",
      prompt_ar: "حوّل ٣ م³ إلى سم³.",
      choices_ar: ["300 سم³", "30000 سم³", "3000000 سم³", "300000 سم³"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عامل طول.",
        1: "عامل مساحة تقريباً.",
        3: "نُقص صفر.",
      },
      solve_ar: "٣ × ١٠٠٠٠٠٠ = ٣٠٠٠٠٠٠ سم³.",
      trick_ref: "units-measure",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f05",
      prompt_ar: "مساحتان: ٢٥٠٠ سم² و٠٫٣ م². أيّهما أكبر؟",
      choices_ar: ["0.3 م²", "2500 سم²", "متساويتان", "لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "٢٥٠٠ سم² = ٠٫٢٥ م² أصغر من ٠٫٣.",
        2: "٠٫٢٥ ≠ ٠٫٣.",
        3: "يمكن التوحيد والمقارنة.",
      },
      solve_ar: "٢٥٠٠ سم² = ٠٫٢٥ م²، و٠٫٣ م² أكبر.",
      trick_ref: "units-measure",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f06",
      prompt_ar: "كم سم في ٢٫٧٥ م؟",
      choices_ar: ["27.5 سم", "275 سم", "2750 سم", "0.0275 سم"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ضُرب في ١٠.",
        2: "ضُرب في ١٠٠٠.",
        3: "قُسم.",
      },
      solve_ar: "٢٫٧٥ × ١٠٠ = ٢٧٥ سم.",
      trick_ref: "units-measure",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "um-f07",
      prompt_ar:
        "حُوّلت مساحة من م² إلى سم² بالضرب في ١٠٠. الناتج ظهر ٢٠٠ لمساحة أصلها ٢ م². ما الناتج الصحيح؟",
      choices_ar: ["20000 سم²", "200 سم²", "2000 سم²", "2 سم²"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا ناتج العامل الخاطئ.",
        2: "عامل ١٠٠٠.",
        3: "لم يُحوَّل.",
      },
      solve_ar: "٢ × ١٠٠٠٠ = ٢٠٠٠٠ سم².",
      trick_ref: "units-measure",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
