import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const volume: Skill = {
  id: "volume",
  title_ar: "حجوم المجسمات",
  domain: "geometry",
  hook_ar: "المكعب: ض³ · متوازي المستطيلات: طول × عرض × ارتفاع",
  estimated_minutes: 7,
  icon: "▢",
  visual: { kind: "custom", component: "volume-lab" },
  intuition_ar: [
    "الحجم يقيس ما يملأ المجسّم من الداخل.",
    "حجم المكعب = طول الضلع × نفسه × نفسه.",
    "حجم متوازي المستطيلات = الطول × العرض × الارتفاع.",
  ],
  trick_ar: {
    statement: "ثلاث أبعاد متكاثرة — لا تجمعها ولا تحسب الوجوه.",
    steps: [
      "حدّد الشكل: مكعب أم متوازي مستطيلات",
      "المكعب: حجم = ض × ض × ض",
      "المتوازي: حجم = طول × عرض × ارتفاع",
    ],
    time_target_sec: 20,
    example_ar:
      "صندوق 4×3×2: الحجم = 4 × 3 × 2 = 24.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "vo-01",
      prompt_ar: "مكعب طول ضلعه 4 سم. كم حجمه؟",
      choices_ar: ["64 سم³", "16 سم³", "48 سم³", "12 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط (مساحة وجه).",
        2: "حُسبت مساحة سطحية تقريبية 6×ض² خطأ جزئي.",
        3: "جُمعت أبعاد أو ضُعف خطأ.",
      },
      solve_ar: "الحجم = 4 × 4 × 4 = 64 سم³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-02",
      prompt_ar:
        "صندوق متوازي مستطيلات أبعاده 5 م و 3 م و 2 م. كم حجمه؟",
      choices_ar: ["30 م³", "10 م³", "31 م³", "15 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "جُمعت ثم ضُرب خطأ.",
        3: "ضُرب بُعدان فقط.",
      },
      solve_ar: "الحجم = 5 × 3 × 2 = 30 م³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-03",
      prompt_ar: "مكعب طول ضلعه 6 سم. كم حجمه؟",
      choices_ar: ["216 سم³", "36 سم³", "216 سم²", "18 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "العدد صحيح لكن الوحدة مساحة لا حجم.",
        3: "جُمع أو ضُعف خطأ.",
      },
      solve_ar: "الحجم = 6 × 6 × 6 = 216 سم³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-04",
      prompt_ar:
        "حوض سباحة مستطيل القاعدة طوله 10 م وعرضه 4 م وعمقه 2 م. كم حجمه؟",
      choices_ar: ["80 م³", "16 م³", "40 م³", "32 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد أو ضُرب بُعدان فقط بشكل خاطئ.",
        2: "ضُرب الطول في العرض دون العمق.",
        3: "حُسب محيط×عمق أو خلط مشابه.",
      },
      solve_ar: "الحجم = 10 × 4 × 2 = 80 م³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-05",
      prompt_ar: "مكعب طول ضلعه 3 م. كم حجمه؟",
      choices_ar: ["27 م³", "9 م³", "18 م³", "12 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "حُسبت مساحة سطحية جزئية.",
        3: "جُمعت أبعاد خطأ.",
      },
      solve_ar: "الحجم = 3 × 3 × 3 = 27 م³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-06",
      prompt_ar:
        "علبة أحذية أبعادها 30 سم و 20 سم و 10 سم. كم حجمها؟",
      choices_ar: ["6000 سم³", "60 سم³", "600 سم³", "1200 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط ثم نُسي صِفر.",
        3: "ضُرب بُعدان فقط.",
      },
      solve_ar: "الحجم = 30 × 20 × 10 = 6000 سم³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-07",
      prompt_ar:
        "مكعب حجمه 125 سم³. كم طول ضلعه؟",
      choices_ar: ["5 سم", "25 سم", "15 سم", "41.7 سم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم الحجم على 5 دون جذر تكعيبي صحيح.",
        2: "خُلط مع محيط أو مجموع.",
        3: "قُسم الحجم على 3.",
      },
      solve_ar: "ض³ = 125 ⇒ ض = 5 سم لأن 5 × 5 × 5 = 125.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-08",
      prompt_ar:
        "صندوق أبعاده 8 سم و 5 سم و 4 سم. كم حجمه؟",
      choices_ar: ["160 سم³", "17 سم³", "40 سم³", "96 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط.",
        3: "ضُرب بُعدان مع خلط ثالث.",
      },
      solve_ar: "الحجم = 8 × 5 × 4 = 160 سم³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-09",
      prompt_ar: "مكعب طول ضلعه 8 سم. كم حجمه؟",
      choices_ar: ["512 سم³", "64 سم³", "384 سم³", "24 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "حُسبت مساحة سطحية 6×ض².",
        3: "جُمعت أبعاد خطأ.",
      },
      solve_ar: "الحجم = 8 × 8 × 8 = 512 سم³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-10",
      prompt_ar:
        "ثلاجة داخلها فراغ على شكل متوازي مستطيلات: 1.2 م × 0.5 م × 0.8 م. كم حجم الفراغ؟",
      choices_ar: ["0.48 م³", "2.5 م³", "0.96 م³", "1.5 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط.",
        3: "خُلط جمع وضرب.",
      },
      solve_ar: "الحجم = 1.2 × 0.5 × 0.8 = 0.48 م³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-11",
      prompt_ar:
        "متوازي مستطيلات حجمه 120 م³، وارتفاعه 5 م، وعرضه 4 م. كم طوله؟",
      choices_ar: ["6 م", "24 م", "15 م", "111 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب العرض في الارتفاع فقط وتُرك.",
        2: "قُسم الحجم على الارتفاع فقط.",
        3: "طُرح الأبعاد من الحجم.",
      },
      solve_ar:
        "120 = طول × 4 × 5 ⇒ 120 = طول × 20 ⇒ الطول = 6 م.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-12",
      prompt_ar: "مكعب طول ضلعه 10 سم. كم حجمه؟",
      choices_ar: ["1000 سم³", "100 سم³", "600 سم³", "30 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "حُسبت مساحة سطحية.",
        3: "جُمعت أبعاد خطأ.",
      },
      solve_ar: "الحجم = 10 × 10 × 10 = 1000 سم³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-13",
      prompt_ar:
        "صندوقان متطابقان أبعاد كل منهما 3×2×4 م. كم الحجم الكلي؟",
      choices_ar: ["48 م³", "24 م³", "18 م³", "9 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب حجم صندوق واحد فقط.",
        2: "جُمعت أبعاد صندوق واحد.",
        3: "ضُرب بُعدان فقط.",
      },
      solve_ar:
        "حجم الواحد = 3 × 2 × 4 = 24. والكلي = 24 × 2 = 48 م³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-14",
      prompt_ar:
        "مكعب حجمه 64 م³. كم طول ضلعه؟",
      choices_ar: ["4 م", "8 م", "16 م", "21.3 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم الحجم على 8 خطأ كضلع.",
        2: "رُبّع أو نصف خطأ.",
        3: "قُسم الحجم على 3.",
      },
      solve_ar: "ض³ = 64 ⇒ ض = 4 م لأن 4 × 4 × 4 = 64.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-15",
      prompt_ar:
        "حاوية أبعادها 2.5 م و 2 م و 1.6 م. كم حجمها؟",
      choices_ar: ["8 م³", "6.1 م³", "5 م³", "4 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط.",
        3: "تقريب ناقص.",
      },
      solve_ar: "الحجم = 2.5 × 2 × 1.6 = 8 م³.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-16",
      prompt_ar:
        "متوازي مستطيلات قاعدته مربّعة طول ضلعها 5 سم وارتفاعه 9 سم. كم حجمه؟",
      choices_ar: ["225 سم³", "45 سم³", "90 سم³", "19 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب ضلع القاعدة في الارتفاع فقط.",
        2: "ضُرب محيط أو بُعدان خطأ.",
        3: "جُمعت الأبعاد.",
      },
      solve_ar:
        "الحجم = 5 × 5 × 9 = 225 سم³.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-17",
      prompt_ar:
        "مكعبان طول ضلع كل منهما 5 سم. كم الحجم الكلي؟",
      choices_ar: ["250 سم³", "125 سم³", "50 سم³", "150 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب مكعب واحد فقط.",
        2: "رُبّع الضلع أو جُمع خطأ.",
        3: "خُلط مساحة وحجم.",
      },
      solve_ar:
        "حجم الواحد = 125. والكلي = 125 × 2 = 250 سم³.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-18",
      prompt_ar:
        "صندوق حجمه 180 سم³، وطوله 6 سم، وعرضه 5 سم. كم ارتفاعه؟",
      choices_ar: ["6 سم", "30 سم", "15 سم", "169 سم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب الطول في العرض وتُرك.",
        2: "قُسم الحجم على الطول فقط.",
        3: "طُرح الأبعاد من الحجم.",
      },
      solve_ar:
        "180 = 6 × 5 × ارتفاع ⇒ 180 = 30 × ارتفاع ⇒ الارتفاع = 6 سم.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "vo-f01",
      prompt_ar: "مكعب طول ضلعه 2 م. كم حجمه؟",
      choices_ar: ["8 م³", "4 م³", "6 م³", "12 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "حُسبت مساحة سطحية جزئية.",
        3: "جُمعت أبعاد خطأ.",
      },
      solve_ar: "الحجم = 2 × 2 × 2 = 8 م³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f02",
      prompt_ar:
        "صندوق أبعاده 7 سم و 3 سم و 2 سم. كم حجمه؟",
      choices_ar: ["42 سم³", "12 سم³", "21 سم³", "14 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط.",
        3: "ضُرب بُعدان آخران فقط.",
      },
      solve_ar: "الحجم = 7 × 3 × 2 = 42 سم³.",
      trick_ref: "volume",
      difficulty: "easy",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f03",
      prompt_ar: "مكعب طول ضلعه 9 سم. كم حجمه؟",
      choices_ar: ["729 سم³", "81 سم³", "486 سم³", "27 سم³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع الضلع فقط.",
        2: "حُسبت مساحة سطحية.",
        3: "جُمعت أو ضُعفت أبعاد خطأ.",
      },
      solve_ar: "الحجم = 9 × 9 × 9 = 729 سم³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f04",
      prompt_ar:
        "غرفة على شكل متوازي مستطيلات: 6 م × 4 م × 3 م. كم حجم الهواء فيها؟",
      choices_ar: ["72 م³", "13 م³", "24 م³", "48 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمعت الأبعاد.",
        2: "ضُرب بُعدان فقط.",
        3: "ضُرب بُعدان مع نسيان واحد جزئياً.",
      },
      solve_ar: "الحجم = 6 × 4 × 3 = 72 م³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f05",
      prompt_ar:
        "متوازي مستطيلات حجمه 96 م³ وطوله 8 م وعرضه 3 م. كم ارتفاعه؟",
      choices_ar: ["4 م", "24 م", "12 م", "85 م"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ضُرب الطول في العرض وتُرك.",
        2: "قُسم الحجم على الطول فقط.",
        3: "طُرح الأبعاد من الحجم.",
      },
      solve_ar:
        "96 = 8 × 3 × ارتفاع ⇒ 96 = 24 × ارتفاع ⇒ الارتفاع = 4 م.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f06",
      prompt_ar:
        "مكعب حجمه 1000 سم³. كم طول ضلعه؟",
      choices_ar: ["10 سم", "100 سم", "31.6 سم", "300 سم"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "رُبّع أو قُسم خطأ كبير.",
        2: "أُخذ جذر تربيعي تقريباً بدل تكعيبي.",
        3: "قُسم الحجم على 3 تقريباً.",
      },
      solve_ar: "ض³ = 1000 ⇒ ض = 10 سم.",
      trick_ref: "volume",
      difficulty: "hard",
      sub_pattern: "geometry",
      ...review,
    },
    {
      id: "vo-f07",
      prompt_ar:
        "خزانتان متطابقتان أبعاد كل منهما 2×1.5×1 م. كم الحجم الكلي؟",
      choices_ar: ["6 م³", "3 م³", "4.5 م³", "4 م³"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسبت خزانة واحدة فقط.",
        2: "ضُرب بُعدان فقط لخزانة واحدة.",
        3: "خُلط جمع الأبعاد.",
      },
      solve_ar:
        "حجم الواحدة = 2 × 1.5 × 1 = 3. والكلي = 3 × 2 = 6 م³.",
      trick_ref: "volume",
      difficulty: "mid",
      sub_pattern: "geometry",
      ...review,
    },
  ],
};
