import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const charts: Skill = {
  id: "charts",
  title_ar: "قراءة الرسوم",
  domain: "statistics",
  hook_ar: "أعلى، أقل، ومقارنة فترتين",
  estimated_minutes: 7,
  icon: "▥",
  visual: { kind: "custom", component: "charts-lab" },
  intuition_ar: [
    "في الأعمدة: الأطول هو الأكبر قيمة.",
    "لقراءة قيمة: انظر إلى الرقم المكتوب على العمود أو الشريحة.",
    "لمقارنة فترتين: اطرح الأصغر من الأكبر.",
    "في الدائرة: الأكبر مساحةً هو الأكبر عدداً إن وُجدت الأرقام."
  ],
  trick_ar: {
    statement: "اقرأ الرقم من الرسم مباشرة، ثم قارن أو اطرح — بلا تخمين بصري فقط.",
    steps: [
          "حدّد أعلى أو أقل عمود/شريحة",
          "إن طُلب فرق فترتين: اطرح القيمتين",
          "إن طُلب مجموع أعمدة: اجمعها كما في الجدول"
    ],
    time_target_sec: 18,
    example_ar: "أعمدة: السبت 4 والثلاثاء 9. الفرق = 9 − 4 = 5.",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "cht-01",
      prompt_ar: "رسم أعمدة لمبيعات أيام: السبت=4، الأحد=7، الإثنين=5، الثلاثاء=9. أي يوم هو الأعلى؟",
      choices_ar: ["السبت","الأحد","الإثنين","الثلاثاء"],
      correct_index: 3,
      trap_explanations_ar: {
        0: "أُخذ ثاني أعلى عمود.",
        1: "أُخذ وسط الأيام.",
        2: "أُخذ أقل الأيام خطأً كأعلى.",
      },
      solve_ar: "الأعمدة: 4، 7، 5، 9. الأعلى 9 وهو يوم الثلاثاء.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-02",
      prompt_ar: "أعمدة حضور: صباح=12، ظهر=8، عصر=10، مساء=6. ما قيمة عمود العصر؟",
      choices_ar: ["8","10","12","6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ عمود الظهر.",
        2: "أُخذ عمود الصباح.",
        3: "أُخذ عمود المساء.",
      },
      solve_ar: "من وصف الرسم: عصر = 10.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-03",
      prompt_ar: "أعمدة مبيعات: السبت=4 والثلاثاء=9. كم يزيد الثلاثاء عن السبت؟",
      choices_ar: ["3","5","7","13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من عمود آخر.",
        2: "جُمع العمودين.",
        3: "أُخذ أحد العمودين فقط.",
      },
      solve_ar: "9 − 4 = 5.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-04",
      prompt_ar: "دائرة مقسمة: أحمر 40، أزرق 35، أخضر 25. أي شريحة الأكبر؟",
      choices_ar: ["أحمر","أزرق","أخضر","متساوية"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى الأقرب عدداً.",
        2: "أُخذ الأصغر.",
        3: "اُفترض التساوي.",
      },
      solve_ar: "40 أكبر من 35 و 25؛ الشريحة الأكبر حمراء.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-05",
      prompt_ar: "أعمدة نقاط: جولة1=3، جولة2=8، جولة3=5. أي جولة الأقل؟",
      choices_ar: ["1","2","3","لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ الأوسط.",
        2: "أُخذ الأعلى بالخطأ.",
        3: "البيانات كافية.",
      },
      solve_ar: "الأقل بين 3 و 8 و 5 هو 3 (الجولة 1).",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-06",
      prompt_ar: "أعمدة حضور: صباح=12 ومساء=6. ما الفرق بينهما؟",
      choices_ar: ["4","6","8","18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح ظهر من صباح.",
        2: "جُمع الفترتين.",
        3: "نُصف أحد العمودين خطأ.",
      },
      solve_ar: "12 − 6 = 6.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-07",
      prompt_ar: "مقارنة فترتين في أعمدة: يناير=20 وفبراير=28. أي شهر أعلى؟",
      choices_ar: ["يناير","فبراير","متساويان","لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرئ العمود الأقصر أعلى.",
        2: "اُفترض التساوي.",
        3: "الوصف كافٍ.",
      },
      solve_ar: "28 > 20؛ فبراير أعلى.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-08",
      prompt_ar: "أعمدة: السبت=4، الأحد=7، الإثنين=5، الثلاثاء=9. ما مجموع قيم الأعمدة الأربعة؟",
      choices_ar: ["20","25","30","16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي أحد الأعمدة.",
        2: "زِيد على المجموع.",
        3: "جُمع عمودين فقط.",
      },
      solve_ar: "4 + 7 + 5 + 9 = 25.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-09",
      prompt_ar: "دائرة: رياضيات 50، علوم 30، عربي 20. أي مادتين مجموعهما يساوي شريحة الرياضيات؟",
      choices_ar: ["علوم وعربي","رياضيات وعلوم","عربي فقط","لا شيء"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع مع الرياضيات خطأ.",
        2: "أُخذت شريحة واحدة.",
        3: "اُفترض لا يوجد تطابق.",
      },
      solve_ar: "علوم + عربي = 30 + 20 = 50 وهو يساوي الرياضيات.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-10",
      prompt_ar: "أعمدة: ظهر=8 وعصر=10. كم يزيد العصر عن الظهر؟",
      choices_ar: ["1","2","4","18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح بالعكس.",
        2: "جُمع الفترتين.",
        3: "أُخذ فرق مع فترة أخرى.",
      },
      solve_ar: "10 − 8 = 2.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-11",
      prompt_ar: "أعمدة إنتاج: آلة أ=14، آلة ب=11، آلة ج=14، آلة د=9. كم آلة تصل إلى القيمة الأعلى؟",
      choices_ar: ["1","2","3","4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّت آلة واحدة فقط.",
        2: "عُدّت ثلاث آلات.",
        3: "عُدّت كل الآلات.",
      },
      solve_ar: "الأعلى 14 تظهر عند أ وج؛ إذن آلتان.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-12",
      prompt_ar: "دائرة نسب مبيعات: كتب 45، أدوات 30، أخرى 25. ما قيمة شريحة الأدوات؟",
      choices_ar: ["25","30","45","55"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت شريحة أخرى.",
        2: "أُخذت شريحة الكتب.",
        3: "جُمعت شريحتان.",
      },
      solve_ar: "من وصف الدائرة: أدوات = 30.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-13",
      prompt_ar: "مقارنة عمودين: يناير=20 وفبراير=28. ما الزيادة من يناير إلى فبراير؟",
      choices_ar: ["6","8","10","48"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح بالعكس.",
        2: "قُرّب الفرق.",
        3: "جُمع الشهرين.",
      },
      solve_ar: "28 − 20 = 8.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-14",
      prompt_ar: "أعمدة حرارة تقديرية لأيام: الأحد=31، الإثنين=29، الثلاثاء=33، الأربعاء=30. أي يوم الأعلى؟",
      choices_ar: ["الأحد","الإثنين","الثلاثاء","الأربعاء"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذ ثاني أعلى.",
        1: "أُخذ الأقل.",
        3: "أُخذ يوم الأحد لأنه الأول.",
      },
      solve_ar: "القيم 31، 29، 33، 30؛ الأعلى 33 يوم الثلاثاء.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-15",
      prompt_ar: "دائرة: أحمر 40، أزرق 35، أخضر 25. ما مجموع الشرائح الثلاث؟",
      choices_ar: ["90","95","100","110"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُسيت شريحة.",
        1: "نُقص من المجموع.",
        3: "زِيد على المجموع.",
      },
      solve_ar: "40 + 35 + 25 = 100.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-16",
      prompt_ar: "أعمدة زيارات: س1=15، س2=22، س3=18، س4=22. أي أسبوعين متساويان في الأعلى؟",
      choices_ar: ["س1 وس3","س2 وس4","س2 وس3","س1 وس4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُورنت قيم متوسطة.",
        2: "خُلط س3 مع الأعلى.",
        3: "خُلط س1 مع الأعلى.",
      },
      solve_ar: "الأعلى 22 عند س2 وس4.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-17",
      prompt_ar: "أعمدة: آلة أ=14 وآلة د=9. ما الفرق؟",
      choices_ar: ["3","5","7","23"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من آلة أخرى.",
        2: "جُمع الآلتين.",
        3: "نُصف الفرق خطأ.",
      },
      solve_ar: "14 − 9 = 5.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-18",
      prompt_ar: "دائرة ميزانية: إيجار 50، طعام 30، مواصلات 20. أي شريحة تعادل مجموع الطعام والمواصلات؟",
      choices_ar: ["إيجار","طعام","مواصلات","لا شيء"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذت شريحة الطعام.",
        2: "أُخذت المواصلات.",
        3: "اُفترض لا تطابق.",
      },
      solve_ar: "طعام + مواصلات = 30 + 20 = 50 = الإيجار.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "cht-f01",
      prompt_ar: "أعمدة أهداف: فريق1=5، فريق2=8، فريق3=6. أي فريق الأعلى؟",
      choices_ar: ["1","2","3","متساوون"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الأوسط.",
        2: "أُخذ الأقل.",
        3: "اُفترض التساوي.",
      },
      solve_ar: "الأعلى 8 وهو الفريق 2.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f02",
      prompt_ar: "من نفس الأعمدة: فريق1=5 وفريق2=8. ما الفرق؟",
      choices_ar: ["2","3","4","13"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح مع فريق 3.",
        2: "جُمع الفريقين.",
        3: "طُرح بالعكس.",
      },
      solve_ar: "8 − 5 = 3.",
      trick_ref: "charts",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f03",
      prompt_ar: "دائرة ألوان: أصفر 20، بنفسجي 45، رمادي 35. ما لون الشريحة الأكبر؟",
      choices_ar: ["أصفر","بنفسجي","رمادي","متساوية"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ الأصغر.",
        2: "أُخذ الأوسط.",
        3: "اُفترض التساوي.",
      },
      solve_ar: "45 هو الأكبر؛ البنفسجي.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f04",
      prompt_ar: "أعمدة مطر تقديري (مم): يوم1=12، يوم2=7، يوم3=12، يوم4=9. كم يوماً يساوي الأعلى؟",
      choices_ar: ["1","2","3","4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّ يوم واحد.",
        2: "عُدّت ثلاثة أيام.",
        3: "عُدّت كل الأيام.",
      },
      solve_ar: "الأعلى 12 في يوم1 ويوم3؛ يومان.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f05",
      prompt_ar: "أعمدة زيارات: 15، 22، 18، 22. ما مجموعها؟",
      choices_ar: ["70","77","80","55"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي عمود.",
        2: "زِيد على المجموع.",
        3: "جُمع ثلاثة فقط.",
      },
      solve_ar: "15+22+18+22 = 77.",
      trick_ref: "charts",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f06",
      prompt_ar: "مقارنة فترتين: الصباح عمود=16 والمساء=21. أي فترة أعلى؟",
      choices_ar: ["صباح","مساء","متساويتان","لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرئ العمود الأقصر أعلى.",
        2: "اُفترض التساوي.",
        3: "الوصف كافٍ.",
      },
      solve_ar: "21 > 16؛ المساء أعلى.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "cht-f07",
      prompt_ar: "أعمدة حرارة: الإثنين=29 والثلاثاء=33. ما الفرق؟",
      choices_ar: ["2","4","5","62"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح يوم آخر.",
        2: "جُمع اليومين.",
        3: "طُرح بالعكس.",
      },
      solve_ar: "33 − 29 = 4.",
      trick_ref: "charts",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
