import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const dataPercent: Skill = {
  id: "data-percent",
  title_ar: "نسب من بيانات",
  domain: "statistics",
  hook_ar: "نسبة فئة من مجموع الجدول",
  estimated_minutes: 7,
  icon: "％",
  visual: { kind: "custom", component: "data-percent-lab" },
  intuition_ar: [
    "نسبة الفئة = قيمة الفئة ÷ مجموع الجدول × 100.",
    "اجمع كل الفئات أولاً لتحصل على المجموع.",
    "لا تكتب العدد نفسه كأنه نسبة مئوية دون قسمة.",
    "هذه المهارة عن النسبة المئوية من بيانات — لا عن مجرد قراءة خلية."
  ],
  trick_ar: {
    statement: "اجمع الكلي، ثم اقسم الفئة على الكلي واضرب في 100.",
    steps: [
          "اجمع أرقام الجدول",
          "اقسم الفئة المطلوبة على المجموع",
          "اضرب في 100 وألحق رمز النسبة"
    ],
    time_target_sec: 20,
    example_ar: "كتب 40 من مجموع 100: 40 ÷ 100 × 100 = 40٪.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "dp-01",
      prompt_ar: "جدول مبيعات:\nكتب 40، أقلام 25، دفاتر 35.\nما نسبة الكتب من المجموع؟",
      choices_ar: ["25٪","35٪","40٪","50٪"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذت فئة الأقلام.",
        1: "أُخذت فئة الدفاتر.",
        3: "قُسم خطأ.",
      },
      solve_ar: "المجموع = 40+25+35 = 100. نسبة الكتب = 40 ÷ 100 × 100 = 40٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-02",
      prompt_ar: "من الجدول نفسه: كتب 40، أقلام 25، دفاتر 35. ما نسبة الأقلام؟",
      choices_ar: ["25٪","40٪","35٪","60٪"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذت الكتب.",
        2: "أُخذت الدفاتر.",
        3: "نُسب إلى غير المجموع.",
      },
      solve_ar: "25 ÷ 100 × 100 = 25٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-03",
      prompt_ar: "حضور:\nناجح 48، راسب 12، غائب 20.\nما نسبة الناجحين؟",
      choices_ar: ["48٪","60٪","80٪","12٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد نسبةً مباشرة دون قسمة على المجموع.",
        2: "أُخذ المجموع نفسه.",
        3: "أُخذت نسبة الراسب.",
      },
      solve_ar: "المجموع = 80. النسبة = 48 ÷ 80 × 100 = 60٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-04",
      prompt_ar: "ألوان:\nأحمر 15، أزرق 35، أخضر 50.\nما نسبة الأحمر؟",
      choices_ar: ["15٪","35٪","50٪","65٪"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذ الأزرق.",
        2: "أُخذ الأخضر.",
        3: "جُمع لونان.",
      },
      solve_ar: "المجموع 100. 15 ÷ 100 × 100 = 15٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-05",
      prompt_ar: "حضور: ناجح 48، راسب 12، غائب 20. ما نسبة الراسبين؟",
      choices_ar: ["12٪","15٪","20٪","25٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد 12 كنسبة.",
        2: "أُخذ الغائب.",
        3: "قُسم على 48.",
      },
      solve_ar: "12 ÷ 80 × 100 = 15٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-06",
      prompt_ar: "مبيعات: كتب 40، أقلام 25، دفاتر 35. ما نسبة الدفاتر؟",
      choices_ar: ["25٪","35٪","40٪","75٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أقلام.",
        2: "كتب.",
        3: "مجموع فئتين.",
      },
      solve_ar: "35 ÷ 100 × 100 = 35٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-07",
      prompt_ar: "مواد:\nرياضيات 50، علوم 30، عربي 20.\nما نسبة العلوم؟",
      choices_ar: ["20٪","30٪","50٪","60٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عربي.",
        2: "رياضيات.",
        3: "علوم+عربي.",
      },
      solve_ar: "المجموع 100. 30 ÷ 100 × 100 = 30٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-08",
      prompt_ar: "جدول:\nصباح 18، ظهر 27، مساء 15.\nما نسبة فترة الصباح من المجموع؟",
      choices_ar: ["18٪","30٪","45٪","27٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب 18٪ مباشرة.",
        2: "قُسم على غير المجموع.",
        3: "أُخذ الظهر.",
      },
      solve_ar: "المجموع = 60. 18 ÷ 60 × 100 = 30٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-09",
      prompt_ar: "من الجدول: صباح 18، ظهر 27، مساء 15. ما نسبة الظهر؟",
      choices_ar: ["27٪","45٪","30٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد نسبة.",
        2: "أُخذ الصباح.",
        3: "قُرّب خطأ.",
      },
      solve_ar: "27 ÷ 60 × 100 = 45٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-10",
      prompt_ar: "مبيعات فروع:\nفرع أ 10، فرع ب 20، فرع ج 20.\nما نسبة فرع أ؟",
      choices_ar: ["10٪","20٪","40٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب 10٪ مباشرة.",
        2: "أُخذ فرع ب.",
        3: "مجموع ب وج.",
      },
      solve_ar: "المجموع = 50. 10 ÷ 50 × 100 = 20٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-11",
      prompt_ar: "فروع: أ 10، ب 20، ج 20. ما نسبة فرع ب؟",
      choices_ar: ["20٪","40٪","50٪","10٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "أُخذ نصف المجموع خطأ كـ 50٪ دون فرع.",
        3: "أُخذ أ.",
      },
      solve_ar: "20 ÷ 50 × 100 = 40٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-12",
      prompt_ar: "جدول عمودين:\nنجاح 24، تعثر 16.\nما نسبة النجاح؟",
      choices_ar: ["24٪","40٪","60٪","16٪"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        1: "كُتب المجموع.",
        3: "نسبة التعثر.",
      },
      solve_ar: "المجموع 40. 24 ÷ 40 × 100 = 60٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-13",
      prompt_ar: "استطلاع:\nموافق 35، غير موافق 15.\nما نسبة الموافقين؟",
      choices_ar: ["35٪","70٪","15٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة الغير.",
        3: "ظُنّ مناصفة.",
      },
      solve_ar: "المجموع 50. 35 ÷ 50 × 100 = 70٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-14",
      prompt_ar: "جدول:\nأ 8، ب 12، ج 12.\nما نسبة فئة أ؟",
      choices_ar: ["8٪","25٪","33٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "قُسم على 3 فئات بالتساوي تقريباً.",
        3: "قُسم أ على ب.",
      },
      solve_ar: "المجموع 32. 8 ÷ 32 × 100 = 25٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-15",
      prompt_ar: "مبيعات:\nمدينة 45، قرية 30، طريق 15.\nما نسبة المدينة؟",
      choices_ar: ["45٪","50٪","30٪","75٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "أُخذت القرية.",
        3: "مدينة+قرية.",
      },
      solve_ar: "المجموع 90. 45 ÷ 90 × 100 = 50٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-16",
      prompt_ar: "مبيعات:\nمدينة 45، قرية 27، طريق 18.\nما نسبة القرية؟",
      choices_ar: ["27٪","30٪","40٪","33٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "قُسم خطأ إلى 40.",
        3: "قُرّب إلى 33.",
      },
      solve_ar: "المجموع 90. 27 ÷ 90 × 100 = 30٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-17",
      prompt_ar: "جدول حصص:\nنشاط أ 14، نشاط ب 21، نشاط ج 15.\nما نسبة النشاط أ؟",
      choices_ar: ["14٪","28٪","42٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة ب.",
        3: "نصف تقريبي.",
      },
      solve_ar: "المجموع 50. 14 ÷ 50 × 100 = 28٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-18",
      prompt_ar: "من الجدول: أ 14، ب 21، ج 15. ما نسبة النشاط ب؟",
      choices_ar: ["21٪","42٪","28٪","35٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة أ.",
        3: "قُسم خطأ.",
      },
      solve_ar: "21 ÷ 50 × 100 = 42٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "dp-f01",
      prompt_ar: "جدول: تفاح 20، برتقال 30. ما نسبة التفاح؟",
      choices_ar: ["20٪","40٪","30٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة البرتقال.",
        3: "ظُنّ مناصفة.",
      },
      solve_ar: "المجموع 50. 20 ÷ 50 × 100 = 40٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f02",
      prompt_ar: "ناجح 36، راسب 14. ما نسبة الناجح؟",
      choices_ar: ["36٪","72٪","14٪","50٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة الراسب.",
        3: "مناصفة.",
      },
      solve_ar: "المجموع 50. 36 ÷ 50 × 100 = 72٪.",
      trick_ref: "data-percent",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f03",
      prompt_ar: "أ 25، ب 25، ج 50. ما نسبة ج؟",
      choices_ar: ["25٪","50٪","75٪","100٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أ.",
        2: "أ+ب.",
        3: "الكل.",
      },
      solve_ar: "المجموع 100. 50 ÷ 100 × 100 = 50٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f04",
      prompt_ar: "ذكور 18، إناث 27. ما نسبة الإناث؟",
      choices_ar: ["27٪","60٪","40٪","45٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة الذكور 18 ÷ 45 × 100 = 40٪.",
        3: "قُرّب.",
      },
      solve_ar: "المجموع 45. 27 ÷ 45 × 100 = 60٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f05",
      prompt_ar: "صباح 16، مساء 24. ما نسبة الصباح؟",
      choices_ar: ["16٪","40٪","60٪","24٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة المساء.",
        3: "كُتب 24.",
      },
      solve_ar: "المجموع 40. 16 ÷ 40 × 100 = 40٪.",
      trick_ref: "data-percent",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f06",
      prompt_ar: "أ 10، ب 20، ج 10. ما نسبة ب؟",
      choices_ar: ["20٪","50٪","25٪","40٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "نسبة أ.",
        3: "قُسم خطأ إلى 40٪.",
      },
      solve_ar: "المجموع 40. 20 ÷ 40 × 100 = 50٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "dp-f07",
      prompt_ar: "جدول ثلاث فئات: 12 و 18 و 10. ما نسبة الفئة الوسطى (18)؟",
      choices_ar: ["18٪","45٪","40٪","30٪"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "كُتب العدد.",
        2: "قُسم على 45 خطأ كـ 40٪.",
        3: "قُسم 12/40.",
      },
      solve_ar: "المجموع 40. 18 ÷ 40 × 100 = 45٪.",
      trick_ref: "data-percent",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
