import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const meanList: Skill = {
  id: "mean-list",
  title_ar: "المتوسط من قائمة",
  domain: "statistics",
  hook_ar: "اجمع القيم ثم اقسم على عددها — لا أكثر",
  estimated_minutes: 6,
  icon: "⌀",
  visual: { kind: "custom", component: "mean-list-lab" },
  intuition_ar: [
    "المتوسط من قائمة = مجموع القيم ÷ عدد القيم.",
    "اجمع أولاً، ثم اقسم على العدد الظاهر في القائمة.",
    "المجموع وحده ليس المتوسط، والقيمة الوسطى ليست المتوسط الحسابي هنا.",
  ],
  trick_ar: {
    statement: "مجموع القائمة ÷ عدد عناصرها.",
    steps: [
      "اجمع كل القيم في القائمة",
      "عدّ كم قيمة لديك",
      "اقسم المجموع على العدد",
    ],
    time_target_sec: 16,
    example_ar:
      "القيم 6 و 8 و 10 و 12: المجموع 36 والعدد 4، فالمتوسط = 36 ÷ 4 = 9.",
  },
  timing: {
    excellent_sec: 16,
    good_sec: 26,
    ok_sec: 36,
    slow_sec: 50,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ml-01",
      prompt_ar:
        "سجّل لاعب كرة سلة 6 و 8 و 10 و 12 نقطة في أربع مباريات. ما متوسط نقاطه؟",
      choices_ar: ["8", "9", "10", "36"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم المجموع على عدد أكبر من أربع.",
        2: "اختيرت قيمة من القائمة دون حساب.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 6 + 8 + 10 + 12 = 36. العدد = 4. المتوسط = 36 ÷ 4 = 9.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-02",
      prompt_ar: "درجات طالب في ثلاثة اختبارات: 12 و 15 و 18. ما متوسط درجاته؟",
      choices_ar: ["14", "15", "16", "45"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص واحد من المتوسط الصحيح.",
        2: "زِيد واحد على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 12 + 15 + 18 = 45. العدد = 3. المتوسط = 45 ÷ 3 = 15.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-03",
      prompt_ar:
        "قراءات حرارة في خمسة أيام: 22 و 24 و 26 و 28 و 30. ما متوسط الحرارة؟",
      choices_ar: ["24", "25", "26", "130"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        1: "حُسب متوسط طرفي القائمة فقط.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 22 + 24 + 26 + 28 + 30 = 130. العدد = 5. المتوسط = 130 ÷ 5 = 26.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-04",
      prompt_ar: "أوزان أربعة صناديق بالكيلو: 4 و 6 و 8 و 10. ما متوسط الوزن؟",
      choices_ar: ["6", "7", "8", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت أصغر قيمة تقريباً.",
        2: "اختيرت أكبر قيمة تقريباً.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 4 + 6 + 8 + 10 = 28. العدد = 4. المتوسط = 28 ÷ 4 = 7.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-05",
      prompt_ar: "نتائج خمس جولات نقاط: 2 و 4 و 6 و 8 و 10. ما المتوسط؟",
      choices_ar: ["5", "6", "7", "30"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم المجموع على ستة.",
        2: "قُسم المجموع على عدد أصغر.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 2 + 4 + 6 + 8 + 10 = 30. العدد = 5. المتوسط = 30 ÷ 5 = 6.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-06",
      prompt_ar: "مبيعات ثلاثة فروع بالآلاف: 100 و 120 و 80. ما متوسط المبيعات؟",
      choices_ar: ["90", "100", "110", "300"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أصغر قيمة كمتوسط تقريباً.",
        2: "أُخذ أكبر قيمة تقريباً.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 100 + 120 + 80 = 300. العدد = 3. المتوسط = 300 ÷ 3 = 100.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-07",
      prompt_ar: "أهداف فريق في أربع مباريات: 1 و 3 و 2 و 4. ما متوسط الأهداف؟",
      choices_ar: ["2", "2.5", "3", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُرب المتوسط إلى أسفل دون حساب.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 1 + 3 + 2 + 4 = 10. العدد = 4. المتوسط = 10 ÷ 4 = 2.5.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-08",
      prompt_ar: "درجات أربع مواد: 80 و 70 و 90 و 60. ما متوسط الدرجات؟",
      choices_ar: ["70", "75", "80", "300"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت أصغر درجة تقريباً.",
        2: "اختيرت أكبر درجة تقريباً.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 80 + 70 + 90 + 60 = 300. العدد = 4. المتوسط = 300 ÷ 4 = 75.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-09",
      prompt_ar:
        "أوقات انتظار بالدقائق في أربعة طوابير: 12 و 18 و 15 و 21. ما المتوسط؟",
      choices_ar: ["15", "16", "16.5", "66"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        1: "قُرب المتوسط إلى عدد صحيح دون حساب دقيق.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 12 + 18 + 15 + 21 = 66. العدد = 4. المتوسط = 66 ÷ 4 = 16.5.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-10",
      prompt_ar: "أوزان أربعة طلاب بالكيلو: 50 و 55 و 60 و 65. ما المتوسط؟",
      choices_ar: ["55", "57.5", "60", "230"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 50 + 55 + 60 + 65 = 230. العدد = 4. المتوسط = 230 ÷ 4 = 57.5.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-11",
      prompt_ar: "ست قراءات سرعة: 4 و 6 و 8 و 10 و 12 و 14. ما المتوسط؟",
      choices_ar: ["8", "9", "10", "54"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص واحد من المتوسط الصحيح.",
        2: "زِيد واحد على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 4 + 6 + 8 + 10 + 12 + 14 = 54. العدد = 6. المتوسط = 54 ÷ 6 = 9.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-12",
      prompt_ar: "قائمة أعداد: 5 و 5 و 5 و 15. ما المتوسط؟",
      choices_ar: ["5", "7.5", "10", "30"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ المنوال أو القيمة الأكثر ظهوراً بدل المتوسط.",
        2: "حُسب متوسط 5 و 15 فقط.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 5 + 5 + 5 + 15 = 30. العدد = 4. المتوسط = 30 ÷ 4 = 7.5.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-13",
      prompt_ar:
        "أسعار خمسة أصناف بالريال: 11 و 13 و 15 و 17 و 19. ما متوسط السعر؟",
      choices_ar: ["13", "15", "17", "75"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 11 + 13 + 15 + 17 + 19 = 75. العدد = 5. المتوسط = 75 ÷ 5 = 15.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-14",
      prompt_ar: "عدد الكتب في أربعة رفوف: 8 و 8 و 10 و 14. ما المتوسط؟",
      choices_ar: ["8", "10", "12", "40"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت أصغر قيمة.",
        2: "حُسب متوسط الطرفين فقط.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 8 + 8 + 10 + 14 = 40. العدد = 4. المتوسط = 40 ÷ 4 = 10.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-15",
      prompt_ar: "قائمة: 0 و 10 و 20 و 30. ما المتوسط؟",
      choices_ar: ["10", "15", "20", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 0 + 10 + 20 + 30 = 60. العدد = 4. المتوسط = 60 ÷ 4 = 15.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-16",
      prompt_ar:
        "مسافات خمس جولات بالكيلو: 3 و 5 و 7 و 9 و 11. ما متوسط المسافة؟",
      choices_ar: ["5", "7", "9", "35"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 3 + 5 + 7 + 9 + 11 = 35. العدد = 5. المتوسط = 35 ÷ 5 = 7.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-17",
      prompt_ar: "درجات ست طالبات: 14 و 16 و 18 و 12 و 20 و 10. ما المتوسط؟",
      choices_ar: ["14", "15", "16", "90"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص واحد من المتوسط الصحيح.",
        2: "زِيد واحد على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 14 + 16 + 18 + 12 + 20 + 10 = 90. العدد = 6. المتوسط = 90 ÷ 6 = 15.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-18",
      prompt_ar:
        "استهلاك وقود لثلاث رحلات باللتر: 24 و 30 و 36. ما متوسط الاستهلاك؟",
      choices_ar: ["28", "30", "32", "90"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص اثنان من المتوسط الصحيح.",
        2: "زِيد اثنان على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 24 + 30 + 36 = 90. العدد = 3. المتوسط = 90 ÷ 3 = 30.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ml-f01",
      prompt_ar: "سبع درجات حضور: 9 و 8 و 10 و 7 و 9 و 8 و 5. ما المتوسط؟",
      choices_ar: ["7", "8", "9", "56"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم المجموع على ثمانية.",
        2: "اختيرت قيمة شائعة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 9 + 8 + 10 + 7 + 9 + 8 + 5 = 56. العدد = 7. المتوسط = 56 ÷ 7 = 8.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f02",
      prompt_ar: "أسعار أربعة تذاكر: 45 و 55 و 65 و 35. ما متوسط السعر؟",
      choices_ar: ["45", "50", "55", "200"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 45 + 55 + 65 + 35 = 200. العدد = 4. المتوسط = 200 ÷ 4 = 50.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f03",
      prompt_ar: "أطوال خمسة أعواد بالسنتيمتر: 12 و 16 و 20 و 24 و 28. ما المتوسط؟",
      choices_ar: ["18", "20", "22", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص اثنان من المتوسط الصحيح.",
        2: "زِيد اثنان على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 12 + 16 + 20 + 24 + 28 = 100. العدد = 5. المتوسط = 100 ÷ 5 = 20.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f04",
      prompt_ar: "قائمة: 3 و 3 و 3 و 3 و 18. ما المتوسط؟",
      choices_ar: ["3", "6", "9", "30"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت القيمة الأكثر ظهوراً بدل المتوسط.",
        2: "حُسب متوسط 3 و 18 فقط.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 3 + 3 + 3 + 3 + 18 = 30. العدد = 5. المتوسط = 30 ÷ 5 = 6.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f05",
      prompt_ar:
        "عدد الرسائل في ستة أيام: 10 و 14 و 18 و 22 و 26 و 30. ما المتوسط؟",
      choices_ar: ["18", "20", "22", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 10 + 14 + 18 + 22 + 26 + 30 = 120. العدد = 6. المتوسط = 120 ÷ 6 = 20.",
      trick_ref: "mean-list",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f06",
      prompt_ar: "سرعات أربع سيارات بالكم/س: 60 و 80 و 100 و 40. ما المتوسط؟",
      choices_ar: ["60", "70", "80", "280"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "اختيرت قيمة من القائمة.",
        2: "اختيرت قيمة من القائمة.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar: "المجموع = 60 + 80 + 100 + 40 = 280. العدد = 4. المتوسط = 280 ÷ 4 = 70.",
      trick_ref: "mean-list",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "ml-f07",
      prompt_ar: "درجات ثمانية طلاب: 5 و 7 و 9 و 11 و 13 و 15 و 17 و 19. ما المتوسط؟",
      choices_ar: ["11", "12", "13", "96"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُقص واحد من المتوسط الصحيح.",
        2: "زِيد واحد على المتوسط الصحيح.",
        3: "هذا هو المجموع لا المتوسط.",
      },
      solve_ar:
        "المجموع = 5 + 7 + 9 + 11 + 13 + 15 + 17 + 19 = 96. العدد = 8. المتوسط = 96 ÷ 8 = 12.",
      trick_ref: "mean-list",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
