import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const median: Skill = {
  id: "median",
  title_ar: "الوسيط",
  domain: "statistics",
  hook_ar: "رتّب القائمة ثم خذ الأوسط — أو متوسط العددين الأوسطين",
  estimated_minutes: 7,
  icon: "◇",
  visual: { kind: "custom", component: "median-lab" },
  intuition_ar: [
    "الوسيط يحتاج ترتيباً تصاعدياً أولاً.",
    "إذا كان العدد فردياً: الوسيط هو القيمة في المنتصف.",
    "إذا كان العدد زوجياً: الوسيط = متوسط العددين الأوسطين.",
  ],
  trick_ar: {
    statement: "رتّب → أوسط واحد (فردي) أو متوسط الأوسطين (زوجي).",
    steps: [
      "رتّب القيم من الأصغر إلى الأكبر",
      "إن كان العدد فردياً خذ القيمة الوسطى",
      "إن كان زوجياً خذ متوسط القيمتين في المنتصف",
    ],
    time_target_sec: 18,
    example_ar:
      "القيم 9 و 3 و 7 و 1 و 5 بعد الترتيب: 1، 3، 5، 7، 9. الوسيط = 5.",
  },
  timing: {
    excellent_sec: 18,
    good_sec: 28,
    ok_sec: 38,
    slow_sec: 52,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "md-01",
      prompt_ar: "درجات: 9 و 3 و 7 و 1 و 5. ما الوسيط؟",
      choices_ar: ["3", "5", "7", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط بعد الترتيب.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت أكبر قيمة بدل الوسيط.",
      },
      solve_ar: "بعد الترتيب: 1، 3، 5، 7، 9. العدد فردي؛ الوسط هو 5.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-02",
      prompt_ar: "أهداف: 8 و 2 و 6 و 4. ما الوسيط؟",
      choices_ar: ["4", "5", "6", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد العددين الأوسطين دون متوسطهما.",
        2: "أُخذ أحد العددين الأوسطين دون متوسطهما.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "بعد الترتيب: 2، 4، 6، 8. الأوسطان 4 و 6. الوسيط = (4 + 6) ÷ 2 = 5.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-03",
      prompt_ar: "أوزان بالكيلو: 12 و 4 و 9 و 1 و 7 و 15 و 3. ما الوسيط؟",
      choices_ar: ["4", "7", "9", "12"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت قيمة من القائمة دون ترتيب صحيح.",
      },
      solve_ar:
        "بعد الترتيب: 1، 3، 4، 7، 9، 12، 15. العدد 7 فردي؛ الوسط (الرابع) = 7.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-04",
      prompt_ar: "أسعار: 10 و 3 و 8 و 1 و 6 و 5. ما الوسيط؟",
      choices_ar: ["5", "5.5", "6", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت قيمة بعيدة عن الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 1، 3، 5، 6، 8، 10. الأوسطان 5 و 6. الوسيط = (5 + 6) ÷ 2 = 5.5.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-05",
      prompt_ar: "قراءات: 20 و 11 و 15. ما الوسيط؟",
      choices_ar: ["11", "15", "20", "46"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم بدل الوسيط.",
      },
      solve_ar: "بعد الترتيب: 11، 15، 20. الوسط = 15.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-06",
      prompt_ar: "أوقات بالدقائق: 14 و 8 و 22 و 10. ما الوسيط؟",
      choices_ar: ["10", "12", "14", "22"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar:
        "بعد الترتيب: 8، 10، 14، 22. الأوسطان 10 و 14. الوسيط = (10 + 14) ÷ 2 = 12.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-07",
      prompt_ar: "درجات: 70 و 90 و 80 و 60 و 100. ما الوسيط؟",
      choices_ar: ["70", "80", "90", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت أكبر درجة.",
      },
      solve_ar: "بعد الترتيب: 60، 70، 80، 90، 100. الوسط = 80.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-08",
      prompt_ar: "مسافات: 5 و 17 و 9 و 2 و 11 و 14. ما الوسيط؟",
      choices_ar: ["9", "10", "11", "14"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت قيمة بعد الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 2، 5، 9، 11، 14، 17. الأوسطان 9 و 11. الوسيط = (9 + 11) ÷ 2 = 10.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-09",
      prompt_ar: "أعداد: 4 و 4 و 4 و 10 و 2. ما الوسيط؟",
      choices_ar: ["2", "4", "10", "24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "بعد الترتيب: 2، 4، 4، 4، 10. الوسط = 4.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-10",
      prompt_ar: "سرعات: 60 و 40 و 80 و 50. ما الوسيط؟",
      choices_ar: ["50", "55", "60", "70"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "حُسب متوسط أكبر قيمتين.",
      },
      solve_ar:
        "بعد الترتيب: 40، 50، 60، 80. الأوسطان 50 و 60. الوسيط = (50 + 60) ÷ 2 = 55.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-11",
      prompt_ar: "درجات حضور: 8 و 6 و 9 و 7 و 5 و 10 و 4. ما الوسيط؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت قيمة بعيدة عن الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 4، 5، 6، 7، 8، 9، 10. الوسط (الرابع) = 7.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-12",
      prompt_ar: "أسعار تذاكر: 45 و 30 و 60 و 25. ما الوسيط؟",
      choices_ar: ["30", "37.5", "45", "60"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar:
        "بعد الترتيب: 25، 30، 45، 60. الأوسطان 30 و 45. الوسيط = (30 + 45) ÷ 2 = 37.5.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-13",
      prompt_ar: "أطوال: 18 و 12 و 15. ما الوسيط؟",
      choices_ar: ["12", "15", "18", "45"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "بعد الترتيب: 12، 15، 18. الوسط = 15.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-14",
      prompt_ar: "نتائج: 3 و 9 و 1 و 7 و 5 و 11. ما الوسيط؟",
      choices_ar: ["5", "6", "7", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت قيمة بعد الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 1، 3، 5، 7، 9، 11. الأوسطان 5 و 7. الوسيط = (5 + 7) ÷ 2 = 6.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-15",
      prompt_ar: "درجات: 95 و 70 و 85 و 60 و 80 و 75 و 90. ما الوسيط؟",
      choices_ar: ["75", "80", "85", "90"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت قيمة بعيدة عن الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 60، 70، 75، 80، 85، 90، 95. الوسط = 80.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-16",
      prompt_ar: "أوزان طرود: 2 و 8 و 2 و 8. ما الوسيط؟",
      choices_ar: ["2", "5", "8", "20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "جُمعت القيم.",
      },
      solve_ar:
        "بعد الترتيب: 2، 2، 8، 8. الأوسطان 2 و 8. الوسيط = (2 + 8) ÷ 2 = 5.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-17",
      prompt_ar: "استهلاك لتر: 24 و 30 و 18 و 36 و 12. ما الوسيط؟",
      choices_ar: ["18", "24", "30", "36"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "بعد الترتيب: 12، 18، 24، 30، 36. الوسط = 24.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-18",
      prompt_ar: "أعداد رسائل: 10 و 40 و 20 و 30. ما الوسيط؟",
      choices_ar: ["20", "25", "30", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "جُمعت القيم.",
      },
      solve_ar:
        "بعد الترتيب: 10، 20، 30، 40. الأوسطان 20 و 30. الوسيط = (20 + 30) ÷ 2 = 25.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "md-f01",
      prompt_ar: "درجات: 13 و 7 و 21 و 9 و 17 و 5 و 11. ما الوسيط؟",
      choices_ar: ["9", "11", "13", "17"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت قيمة بعيدة عن الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 5، 7، 9، 11، 13، 17، 21. الوسط = 11.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f02",
      prompt_ar: "أسعار: 16 و 4 و 12 و 8 و 20 و 0. ما الوسيط؟",
      choices_ar: ["8", "10", "12", "16"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت قيمة بعد الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 0، 4، 8، 12، 16، 20. الأوسطان 8 و 12. الوسيط = (8 + 12) ÷ 2 = 10.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f03",
      prompt_ar: "أهداف: 0 و 3 و 1 و 2 و 5. ما الوسيط؟",
      choices_ar: ["1", "2", "3", "5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "بعد الترتيب: 0، 1، 2، 3، 5. الوسط = 2.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f04",
      prompt_ar: "أوزان: 55 و 48 و 62 و 51. ما الوسيط؟",
      choices_ar: ["51", "53", "55", "62"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar:
        "بعد الترتيب: 48، 51، 55، 62. الأوسطان 51 و 55. الوسيط = (51 + 55) ÷ 2 = 53.",
      trick_ref: "median",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f05",
      prompt_ar: "درجات: 100 و 40 و 70. ما الوسيط؟",
      choices_ar: ["40", "70", "100", "210"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم (هذا ليس الوسيط).",
      },
      solve_ar: "بعد الترتيب: 40، 70، 100. الوسط = 70.",
      trick_ref: "median",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f06",
      prompt_ar: "قراءات: 9 و 1 و 8 و 2 و 7 و 3. ما الوسيط؟",
      choices_ar: ["3", "5", "7", "8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ أحد الأوسطين فقط.",
        2: "أُخذ أحد الأوسطين فقط.",
        3: "أُخذت قيمة بعد الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 1، 2، 3، 7، 8، 9. الأوسطان 3 و 7. الوسيط = (3 + 7) ÷ 2 = 5.",
      trick_ref: "median",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "md-f07",
      prompt_ar: "أطوال: 28 و 16 و 22 و 10 و 34 و 19 و 25. ما الوسيط؟",
      choices_ar: ["19", "22", "25", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة قبل الوسط.",
        2: "أُخذت قيمة بعد الوسط.",
        3: "أُخذت قيمة بعيدة عن الوسط.",
      },
      solve_ar:
        "بعد الترتيب: 10، 16، 19، 22، 25، 28، 34. الوسط = 22.",
      trick_ref: "median",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
