import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const mode: Skill = {
  id: "mode",
  title_ar: "المنوال",
  domain: "statistics",
  hook_ar: "ابحث عن القيمة الأكثر تكراراً في القائمة",
  estimated_minutes: 6,
  icon: "▣",
  visual: { kind: "custom", component: "mode-lab" },
  intuition_ar: [
    "المنوال هو القيمة التي تظهر أكثر من غيرها.",
    "عدّ تكرار كل قيمة؛ الأعلى تكراراً هو المنوال.",
    "إن تعادلت قيمتان في أعلى تكرار فللقائمة منوالان — انتبه لصياغة السؤال.",
  ],
  trick_ar: {
    statement: "الأكثر ظهوراً = المنوال.",
    steps: [
      "مرّ على القائمة وعدّ تكرار كل قيمة",
      "اختر القيمة ذات أكبر تكرار",
      "إن طلب السؤال منوالاً واحداً فتأكد أنه لا تعادل",
    ],
    time_target_sec: 16,
    example_ar:
      "القيم 2 و 3 و 2 و 5 و 2 و 4: الرقم 2 يظهر ثلاث مرات؛ فهو المنوال.",
  },
  timing: {
    excellent_sec: 16,
    good_sec: 26,
    ok_sec: 36,
    slow_sec: 50,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "mo-01",
      prompt_ar: "أهداف مباريات: 2 و 3 و 2 و 5 و 2 و 4. ما المنوال؟",
      choices_ar: ["2", "3", "4", "5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهرت مرة واحدة فقط.",
        2: "ظهرت مرة واحدة فقط.",
        3: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 2 يظهر ثلاث مرات، وباقي الأرقام مرة واحدة. المنوال = 2.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-02",
      prompt_ar: "درجات: 7 و 8 و 7 و 9 و 7 و 6. ما المنوال؟",
      choices_ar: ["6", "7", "8", "9"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        2: "ظهرت مرة واحدة فقط.",
        3: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 7 يظهر ثلاث مرات. المنوال = 7.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-03",
      prompt_ar: "أحجام علب: 1 و 4 و 4 و 4 و 2 و 3. ما المنوال؟",
      choices_ar: ["1", "2", "3", "4"],
      correct_index: 3,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        1: "ظهرت مرة واحدة فقط.",
        2: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 4 يظهر ثلاث مرات. المنوال = 4.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-04",
      prompt_ar: "ألوان قمصان مرمّزة بأرقام: 5 و 5 و 3 و 2 و 5 و 3. ما المنوال؟",
      choices_ar: ["2", "3", "5", "18"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        1: "ظهرت مرتين فقط، أقل من 5.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 5 يظهر ثلاث مرات، و 3 يظهر مرتين. المنوال = 5.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-05",
      prompt_ar: "درجات حرارة: 30 و 28 و 30 و 29 و 30 و 31. ما المنوال؟",
      choices_ar: ["28", "29", "30", "31"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        1: "ظهرت مرة واحدة فقط.",
        3: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 30 يظهر ثلاث مرات. المنوال = 30.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-06",
      prompt_ar: "عدد الركاب في رحلات: 12 و 15 و 12 و 18 و 12 و 15. ما المنوال؟",
      choices_ar: ["12", "15", "18", "84"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 12.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 12 يظهر ثلاث مرات. المنوال = 12.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-07",
      prompt_ar: "نتائج اختبار قصير: 10 و 8 و 9 و 8 و 7 و 8 و 9. ما المنوال؟",
      choices_ar: ["7", "8", "9", "10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        2: "ظهرت مرتين فقط، أقل من 8.",
        3: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 8 يظهر ثلاث مرات. المنوال = 8.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-08",
      prompt_ar: "أهداف لاعبين: 1 و 0 و 1 و 2 و 1 و 3 و 0. ما المنوال؟",
      choices_ar: ["0", "1", "2", "3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظهر مرتين فقط، أقل من 1.",
        2: "ظهر مرة واحدة فقط.",
        3: "ظهر مرة واحدة فقط.",
      },
      solve_ar: "الرقم 1 يظهر ثلاث مرات. المنوال = 1.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-09",
      prompt_ar: "أسعار أصناف: 20 و 25 و 20 و 30 و 20 و 25 و 20. ما المنوال؟",
      choices_ar: ["20", "25", "30", "160"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 20.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 20 يظهر أربع مرات. المنوال = 20.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-10",
      prompt_ar:
        "قائمة: 6 و 4 و 6 و 4 و 6. ما المنوال؟",
      choices_ar: ["4", "5", "6", "26"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهر مرتين فقط، أقل من 6.",
        1: "هذا متوسط القيمتين لا المنوال.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 6 يظهر ثلاث مرات، و 4 مرتين. المنوال = 6.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-11",
      prompt_ar: "أوقات انتظار: 5 و 10 و 5 و 15 و 5 و 10 و 5 و 20. ما المنوال؟",
      choices_ar: ["5", "10", "15", "20"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 5.",
        2: "ظهر مرة واحدة فقط.",
        3: "ظهر مرة واحدة فقط.",
      },
      solve_ar: "الرقم 5 يظهر أربع مرات. المنوال = 5.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-12",
      prompt_ar: "أرقام مقاعد محجوزة بكثرة: 11 و 13 و 11 و 14 و 11 و 13 و 11. ما المنوال؟",
      choices_ar: ["11", "13", "14", "84"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 11.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 11 يظهر أربع مرات. المنوال = 11.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-13",
      prompt_ar:
        "القيم 9 و 7 و 9 و 8 و 7 و 9. أي وصف صحيح؟",
      choices_ar: [
        "المنوال 7",
        "المنوال 9",
        "المنوال 8",
        "لا يوجد منوال",
      ],
      correct_index: 1,
      trap_explanations_ar: {
        0: "الرقم 7 يظهر مرتين فقط، أقل من 9.",
        2: "الرقم 8 يظهر مرة واحدة فقط.",
        3: "يوجد منوال واضح وهو 9.",
      },
      solve_ar: "الرقم 9 يظهر ثلاث مرات، و 7 مرتين، و 8 مرة. إذن المنوال 9.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-14",
      prompt_ar: "نتائج رمي: 2 و 2 و 2 و 5 و 5 و 5 و 5. ما المنوال؟",
      choices_ar: ["2", "3.5", "5", "26"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهر ثلاث مرات فقط، أقل من 5.",
        1: "هذا متوسط 2 و 5 لا المنوال.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 5 يظهر أربع مرات، و 2 ثلاث مرات. المنوال = 5.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-15",
      prompt_ar: "درجات: 100 و 90 و 100 و 80 و 100 و 90. ما المنوال؟",
      choices_ar: ["80", "90", "100", "560"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        1: "ظهرت مرتين فقط، أقل من 100.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 100 يظهر ثلاث مرات. المنوال = 100.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-16",
      prompt_ar:
        "القائمة: 3 و 5 و 3 و 5 و 3 و 5 و 3. ما المنوال؟",
      choices_ar: ["3", "4", "5", "27"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا متوسط 3 و 5 لا المنوال.",
        2: "ظهر ثلاث مرات فقط، أقل من 3.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 3 يظهر أربع مرات، و 5 ثلاث مرات. المنوال = 3.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-17",
      prompt_ar: "أعداد صناديق: 8 و 8 و 6 و 8 و 10 و 6 و 8. ما المنوال؟",
      choices_ar: ["6", "8", "10", "54"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظهر مرتين فقط، أقل من 8.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 8 يظهر أربع مرات. المنوال = 8.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-18",
      prompt_ar:
        "قيمتان فقط في القائمة: 4 و 4 و 4 و 7 و 7. ما المنوال؟",
      choices_ar: ["4", "5.5", "7", "26"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا متوسط 4 و 7 لا المنوال.",
        2: "ظهر مرتين فقط، أقل من 4.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 4 يظهر ثلاث مرات، و 7 مرتين. المنوال = 4.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "mo-f01",
      prompt_ar: "مسافات: 3 و 6 و 3 و 9 و 3 و 6 و 3 و 12. ما المنوال؟",
      choices_ar: ["3", "6", "9", "12"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 3.",
        2: "ظهر مرة واحدة فقط.",
        3: "ظهر مرة واحدة فقط.",
      },
      solve_ar: "الرقم 3 يظهر أربع مرات. المنوال = 3.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f02",
      prompt_ar: "درجات: 15 و 12 و 15 و 18 و 15 و 12 و 15 و 10. ما المنوال؟",
      choices_ar: ["10", "12", "15", "18"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظهرت مرة واحدة فقط.",
        1: "ظهرت مرتين فقط، أقل من 15.",
        3: "ظهرت مرة واحدة فقط.",
      },
      solve_ar: "الرقم 15 يظهر أربع مرات. المنوال = 15.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f03",
      prompt_ar:
        "القائمة: 2 و 8 و 2 و 8 و 2 و 8 و 2 و 8 و 2. ما المنوال؟",
      choices_ar: ["2", "5", "8", "42"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "هذا متوسط 2 و 8 لا المنوال.",
        2: "ظهر أربع مرات فقط، أقل من 2.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 2 يظهر خمس مرات، و 8 أربع مرات. المنوال = 2.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f04",
      prompt_ar: "أوزان: 40 و 45 و 40 و 50 و 40 و 45 و 40 و 55. ما المنوال؟",
      choices_ar: ["40", "45", "50", "55"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 40.",
        2: "ظهر مرة واحدة فقط.",
        3: "ظهر مرة واحدة فقط.",
      },
      solve_ar: "الرقم 40 يظهر أربع مرات. المنوال = 40.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f05",
      prompt_ar:
        "تعادل منوالان في قائمة: 1 و 1 و 2 و 2 و 3. أي صياغة أدق؟",
      choices_ar: [
        "المنوال الوحيد 1",
        "المنوالان 1 و 2",
        "المنوال الوحيد 2",
        "المنوال 3",
      ],
      correct_index: 1,
      trap_explanations_ar: {
        0: "1 ليس منوالاً وحيداً؛ 2 بنفس التكرار.",
        2: "2 ليس منوالاً وحيداً؛ 1 بنفس التكرار.",
        3: "3 يظهر مرة واحدة فقط.",
      },
      solve_ar: "1 و 2 يظهر كل منهما مرتين، و 3 مرة واحدة. إذن المنوالان 1 و 2.",
      trick_ref: "mode",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f06",
      prompt_ar: "نتائج: 6 و 6 و 6 و 9 و 9 و 12. ما المنوال؟",
      choices_ar: ["6", "9", "12", "48"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 6.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 6 يظهر ثلاث مرات. المنوال = 6.",
      trick_ref: "mode",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "mo-f07",
      prompt_ar: "أرقام طلبات: 101 و 102 و 101 و 103 و 101 و 102 و 101. ما المنوال؟",
      choices_ar: ["101", "102", "103", "711"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظهر مرتين فقط، أقل من 101.",
        2: "ظهر مرة واحدة فقط.",
        3: "هذا مجموع القيم لا المنوال.",
      },
      solve_ar: "الرقم 101 يظهر أربع مرات. المنوال = 101.",
      trick_ref: "mode",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
