import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const probWithoutReplace: Skill = {
  id: "prob-without-replace",
  title_ar: "احتمال بلا إرجاع",
  domain: "statistics",
  hook_ar: "سحبتان — حدّث المقام",
  estimated_minutes: 7,
  icon: "◎",
  visual: { kind: "custom", component: "prob-without-replace-lab" },
  intuition_ar: [
    "بلا إرجاع: بعد السحبة الأولى ينقص المطلوب أو الكلي.",
    "احتمال السحبتين = احتمال الأولى × احتمال الثانية بعد التحديث.",
    "المصيدة الشائعة: الإبقاء على نفس المقام كأن السحب بإرجاع.",
    "لا تكتفِ بالسحبة الأولى إن طُلبت سحبتان."
  ],
  trick_ar: {
    statement: "حدّث البسط والمقام بعد السحبة الأولى، ثم اضرب.",
    steps: [
          "اكتب احتمال السحبة الأولى",
          "أنقص الكرة المسحوبة من العدّ",
          "اضرب في احتمال السحبة الثانية بالمقام الجديد"
    ],
    time_target_sec: 22,
    example_ar: "4 حمراء من 6 ثم حمراء ثانية: (4 ÷ 6) × (3 ÷ 5) = 2 ÷ 5.",
  },
  timing: {
    excellent_sec: 22,
    good_sec: 32,
    ok_sec: 42,
    slow_sec: 56,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "pwr-01",
      prompt_ar: "كيس فيه 4 حمراء و 2 زرقاء. تُسحب كرتان متتاليتان بلا إرجاع. ما احتمال أن تكونا حمراوين؟",
      choices_ar: ["4/6","2/5","16/36","1/2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "وُقف عند السحبة الأولى فقط.",
        2: "حُسب كأنه بإرجاع: (4/6)×(4/6).",
        3: "قُرّب دون ضرب الاحتمالين.",
      },
      solve_ar: "الأولى حمراء: 4/6. بعد سحبها يبقى 3 حمراء من 5. الثانية: 3/5. الاحتمال = (4/6)×(3/5) = 12/30 = 2/5.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-02",
      prompt_ar: "نفس الكيس: 4 حمراء و 2 زرقاء بلا إرجاع. ما احتمال حمراء ثم زرقاء؟",
      choices_ar: ["4/15","8/36","1/3","2/5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب بإرجاع (4/6)×(2/6).",
        2: "بُسّط خطأ.",
        3: "أُخذ احتمال حمراوين.",
      },
      solve_ar: "(4/6)×(2/5) = 8/30 = 4/15.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-03",
      prompt_ar: "كيس 3 أحمر و 3 أزرق. سُحبت حمراء أولاً بلا إرجاع. ما احتمال أن تكون الثانية حمراء؟",
      choices_ar: ["3/6","2/5","3/5","2/6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث المقام (بقي 3/6).",
        2: "زيد البسط خطأ.",
        3: "نُقص البسط والمقام كإرجاع جزئي خاطئ.",
      },
      solve_ar: "بعد سحب حمراء: أحمر 2 والكلي 5. الاحتمال = 2/5.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-04",
      prompt_ar: "كيس 5 بطاقات حمراء و 1 زرقاء. سحبتان بلا إرجاع. ما احتمال زرقاوين؟",
      choices_ar: ["0","1/6","1/30","1/5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ وجود زرقاوين.",
        2: "حُسب مسار واحد مستحيل ككسر.",
        3: "خُلط مع احتمال زرقاء واحدة.",
      },
      solve_ar: "يوجد زرقاء واحدة فقط؛ لا يمكن سحب زرقاوين. الاحتمال = 0.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-05",
      prompt_ar: "كيس 3 خضراء و 2 حمراء. سحبتان بلا إرجاع. ما احتمال خضراوين؟",
      choices_ar: ["3/5","9/25","3/10","1/2"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "وُقف عند الأولى.",
        1: "بإرجاع (3/5)×(3/5).",
        3: "قُرّب.",
      },
      solve_ar: "(3/5)×(2/4) = 6/20 = 3/10.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-06",
      prompt_ar: "كيس 2 أبيض و 2 أسود. سُحب أبيض أولاً بلا إرجاع. ما احتمال أن تكون الثانية سوداء؟",
      choices_ar: ["2/4","2/3","1/3","1/4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث الكلي.",
        2: "نُقص بسط الأسود خطأ.",
        3: "قُسم خطأ على 4.",
      },
      solve_ar: "بعد سحب أبيض: أسود 2 والكلي 3. الاحتمال = 2/3.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-07",
      prompt_ar: "كيس 4 حمراء و 2 زرقاء بلا إرجاع. ما احتمال زرقاوين؟",
      choices_ar: ["1/15","4/36","1/5","2/6"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "حُسب كأنه بإرجاع.",
        2: "قُسم خطأ.",
        3: "وُقف عند السحبة الأولى.",
      },
      solve_ar: "(2/6)×(1/5) = 2/30 = 1/15.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-08",
      prompt_ar: "كيس 5 أحمر و 3 أخضر. سُحبت حمراء أولاً. ما احتمال الثانية خضراء؟",
      choices_ar: ["3/8","3/7","5/7","2/7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث المقام.",
        2: "أُخذ احتمال حمراء ثانية.",
        3: "نُقص الأخضر خطأ.",
      },
      solve_ar: "بعد حمراء: أخضر 3 والكلي 7. الاحتمال = 3/7.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-09",
      prompt_ar: "كيس 5 أحمر و 3 أخضر بلا إرجاع. ما احتمال حمراوين؟",
      choices_ar: ["5/8","25/64","5/14","1/2"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "الأولى فقط.",
        1: "بإرجاع.",
        3: "تقريب.",
      },
      solve_ar: "(5/8)×(4/7) = 20/56 = 5/14.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-10",
      prompt_ar: "كيس 6 كرات متمايزة السحب عشوائي. سُحبت كرة وبقيت 5. ما الكلي في السحبة الثانية؟",
      choices_ar: ["6","5","4","7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "بقي الكلي 6 كإرجاع.",
        2: "نُقص أكثر من كرة.",
        3: "زِيد الكلي.",
      },
      solve_ar: "بلا إرجاع ينقص الكلي واحداً فيصير 5.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-11",
      prompt_ar: "كيس بطاقتان «أ» وبطاقتان «ب». سحبتان بلا إرجاع. ما احتمال «أ» ثم «أ»؟",
      choices_ar: ["1/4","1/6","1/2","1/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حُسب كأنه بإرجاع.",
        2: "وُقف عند السحبة الأولى.",
        3: "تُرك الكسر دون ضرب.",
      },
      solve_ar: "(2/4)×(1/3) = 2/12 = 1/6.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-12",
      prompt_ar: "كيس 4 أصفر و 1 أحمر. سُحب أصفر أولاً بلا إرجاع. ما احتمال الثانية أصفر؟",
      choices_ar: ["4/5","3/4","3/5","1/4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث.",
        2: "نُقص الكلي دون البسط فقط بشكل خاطئ مع خيار 3/5.",
        3: "نُقص أكثر.",
      },
      solve_ar: "بعد أصفر: أصفر 3 والكلي 4. الاحتمال = 3/4.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-13",
      prompt_ar: "كيس 4 حمراء و 2 زرقاء بلا إرجاع. ما احتمال زرقاء ثم حمراء؟",
      choices_ar: ["4/15","8/36","1/3","2/5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "بإرجاع.",
        2: "تقريب.",
        3: "حُسب احتمال زرقاء بعد سحب حمراء (2/5) بدل المسار المطلوب: زرقاء ثم حمراء.",
      },
      solve_ar: "(2/6)×(4/5) = 8/30 = 4/15.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-14",
      prompt_ar: "كيس 7 كرات: 4 معلّمة. سُحبت معلّمة أولاً. ما احتمال أن تكون الثانية غير معلّمة؟",
      choices_ar: ["3/7","3/6","4/6","2/6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث المقام.",
        2: "أُخذ معلّمة ثانية.",
        3: "نُقص غير المعلّم خطأ.",
      },
      solve_ar: "غير المعلّم أصلاً 3. بعد سحب معلّمة: غير معلّم 3 والكلي 6. الاحتمال = 3/6 = 1/2، والخيار 3/6.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-15",
      prompt_ar: "كيس 7 كرات منها 4 معلّمة. سحبتان بلا إرجاع. ما احتمال معلّمتين؟",
      choices_ar: ["4/7","16/49","2/7","1/2"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "الأولى فقط.",
        1: "بإرجاع.",
        3: "تقريب.",
      },
      solve_ar: "(4/7)×(3/6) = 12/42 = 2/7.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-16",
      prompt_ar: "كيس 3 أحمر فقط. سحبتان بلا إرجاع. ما احتمال حمراوين؟",
      choices_ar: ["1","2/3","1/2","0"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "ظُنّ 2/3.",
        2: "ظُنّ 1/2.",
        3: "ظُنّ صفراً.",
      },
      solve_ar: "(3/3)×(2/2) = 1.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-17",
      prompt_ar: "كيس 6 أحمر و 2 أزرق. سُحب أزرق أولاً. ما احتمال الثانية أحمر؟",
      choices_ar: ["6/8","6/7","5/7","2/7"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث الكلي.",
        2: "نُقص الأحمر خطأ.",
        3: "أُخذ احتمال أزرق.",
      },
      solve_ar: "بعد أزرق: أحمر 6 والكلي 7. الاحتمال = 6/7.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-18",
      prompt_ar: "كيس 6 أحمر و 2 أزرق بلا إرجاع. ما احتمال حمراوين؟",
      choices_ar: ["6/8","36/64","15/28","5/7"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "وُقف عند السحبة الأولى.",
        1: "حُسب كأنه بإرجاع.",
        3: "أُخذ احتمال السحبة الثانية فقط.",
      },
      solve_ar: "(6/8)×(5/7) = 30/56 = 15/28.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "pwr-f01",
      prompt_ar: "كيس 2 أحمر و 1 أزرق. سُحب أحمر أولاً بلا إرجاع. ما احتمال الثانية أحمر؟",
      choices_ar: ["2/3","1/2","1/3","2/2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث.",
        2: "نُقص أكثر.",
        3: "كُتب 2/2.",
      },
      solve_ar: "بعد أحمر: أحمر 1 والكلي 2. الاحتمال = 1/2.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f02",
      prompt_ar: "كيس 2 أحمر و 1 أزرق بلا إرجاع. ما احتمال حمراوين؟",
      choices_ar: ["1/3","4/9","2/3","1/2"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "بإرجاع.",
        2: "وُقف عند الأولى.",
        3: "تقريب.",
      },
      solve_ar: "(2/3)×(1/2) = 2/6 = 1/3.",
      trick_ref: "prob-without-replace",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f03",
      prompt_ar: "كيس 4 أخضر و 4 أصفر. سُحب أخضر أولاً. ما احتمال الثانية أصفر؟",
      choices_ar: ["4/8","4/7","3/7","3/8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث المقام.",
        2: "نُقص الأصفر خطأ.",
        3: "قُسم خطأ.",
      },
      solve_ar: "أصفر 4 والكلي 7. الاحتمال = 4/7.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f04",
      prompt_ar: "كيس 3 بطاقات «نعم» و 2 «لا». سحبتان بلا إرجاع. ما احتمال «نعم» ثم «لا»؟",
      choices_ar: ["3/10","6/25","1/2","2/5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "بإرجاع.",
        2: "وُقف عند الأولى.",
        3: "خُلط ترتيب.",
      },
      solve_ar: "(3/5)×(2/4) = 6/20 = 3/10.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f05",
      prompt_ar: "كيس 10 كرات منها 1 ذهبية. سُحبت غير ذهبية أولاً. ما احتمال الثانية ذهبية؟",
      choices_ar: ["1/10","1/9","9/10","0"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "لم يُحدَّث المقام.",
        2: "احتمال غير الذهبية.",
        3: "ظُنّ انعدام الذهبية.",
      },
      solve_ar: "الذهبية ما زالت 1 والكلي صار 9. الاحتمال = 1/9.",
      trick_ref: "prob-without-replace",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f06",
      prompt_ar: "كيس 5 أحمر و 5 أزرق بلا إرجاع. ما احتمال زرقاوين؟",
      choices_ar: ["1/4","5/9","2/9","1/2"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُرّب الناتج.",
        1: "حُسب كأنه بإرجاع أو مسار خاطئ.",
        3: "وُقف عند نصف السحبة الأولى.",
      },
      solve_ar: "(5/10)×(4/9) = 20/90 = 2/9.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "pwr-f07",
      prompt_ar: "كيس 1 أحمر و 4 أزرق. سحبتان بلا إرجاع. ما احتمال أحمر ثم أزرق؟",
      choices_ar: ["1/5","4/25","1/4","2/5"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "بإرجاع (1/5)×(4/5).",
        2: "نُسي أن الثانية أزرق مؤكدة تقريباً مع مقام خاطئ.",
        3: "خُلط البسط.",
      },
      solve_ar: "(1/5)×(4/4) = 1/5.",
      trick_ref: "prob-without-replace",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
  ],
};
