import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const probSimple: Skill = {
  id: "prob-simple",
  title_ar: "الاحتمال البسيط",
  domain: "statistics",
  hook_ar: "المطلوب تقسيم الكلي",
  estimated_minutes: 7,
  icon: "◉",
  visual: { kind: "custom", component: "prob-simple-lab" },
  intuition_ar: [
    "الاحتمال البسيط = عدد حالات المطلوب ÷ عدد الحالات الكلي.",
    "عدّ المطلوب بعناية، ثم عدّ الكلي من الكيس أو الحجر أو البطاقات.",
    "بسّط الكسر إن أمكن بعد القسمة.",
    "سحبة واحدة فقط في هذه المهارة — بلا سحبتين متتاليتين."
  ],
  trick_ar: {
    statement: "اكتب كسراً واحداً: المطلوب على الكلي.",
    steps: [
          "عدّ حالات المطلوب",
          "عدّ الكلي",
          "اقسم وبسّط"
    ],
    time_target_sec: 16,
    example_ar: "3 حمراء من 8 كرات: الاحتمال = 3 ÷ 8.",
  },
  timing: {
    excellent_sec: 16,
    good_sec: 26,
    ok_sec: 36,
    slow_sec: 50,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "ps-01",
      prompt_ar: "كيس فيه 3 كرات حمراء و 5 زرقاء. تُسحب كرة واحدة عشوائياً. ما احتمال أن تكون حمراء؟",
      choices_ar: ["3/5","3/8","5/8","1/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم الأحمر على الأزرق فقط.",
        2: "أُخذ احتمال الأزرق.",
        3: "نُسي أن الكلي هو المجموع.",
      },
      solve_ar: "المطلوب = 3 والكلي = 3 + 5 = 8. الاحتمال = 3/8.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-02",
      prompt_ar: "حجر نرد منتظم من 1 إلى 6. ما احتمال ظهور عدد زوجي؟",
      choices_ar: ["1/6","1/3","1/2","2/3"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عُدّ زوجي واحد فقط.",
        1: "عُدّ زوجيان فقط من ستة.",
        3: "عُدّ أربعة أعداد زوجية خطأ.",
      },
      solve_ar: "الأعداد الزوجية 2 و 4 و 6؛ المطلوب = 3 والكلي = 6. الاحتمال = 3/6 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-03",
      prompt_ar: "صندوق بطاقات فيه 4 بطاقات مميزة من 1 إلى 4. تُسحب بطاقة واحدة. ما احتمال أن يكون الرقم أكبر من 2؟",
      choices_ar: ["1/4","1/2","3/4","2/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّ رقم واحد فقط.",
        2: "عُدّ ثلاثة أرقام أكبر من 2 خطأ (3 و 4 فقط).",
        3: "قُسم على 3.",
      },
      solve_ar: "المطلوب: 3 و 4 أي حالتان. الكلي = 4. الاحتمال = 2/4 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-04",
      prompt_ar: "كيس فيه 2 خضراء و 3 حمراء و 2 زرقاء. ما احتمال سحب خضراء؟",
      choices_ar: ["2/5","2/7","3/7","2/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على غير الكلي.",
        2: "أُخذ احتمال الأحمر.",
        3: "قُسم الأخضر على الأحمر.",
      },
      solve_ar: "المطلوب = 2 والكلي = 2+3+2 = 7. الاحتمال = 2/7.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-05",
      prompt_ar: "حجر نرد. ما احتمال ظهور 5؟",
      choices_ar: ["1/5","1/6","5/6","1/2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على 5.",
        2: "احتمال عدم ظهور 5.",
        3: "خُلط مع احتمال الزوجي.",
      },
      solve_ar: "المطلوب حالة واحدة والكلي 6. الاحتمال = 1/6.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-06",
      prompt_ar: "كيس 10 كرات: منها 4 بيضاء. ما احتمال سحب بيضاء؟",
      choices_ar: ["4/6","3/10","2/5","1/4"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم على الباقي فقط.",
        1: "أُخذ عدد قريب غير صحيح.",
        3: "أُخذ 1 على عدد الأبيض.",
      },
      solve_ar: "المطلوب = 4 والكلي = 10. الاحتمال = 4/10 = 2/5.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-07",
      prompt_ar: "بطاقات من 1 إلى 5. ما احتمال أن يكون الرقم فردياً؟",
      choices_ar: ["1/5","2/5","3/5","4/5"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عُدّ فردي واحد.",
        1: "عُدّ فرديان فقط.",
        3: "عُدّ أربعة أرقام فردية خطأ.",
      },
      solve_ar: "الفردي: 1 و 3 و 5. المطلوب = 3 والكلي = 5. الاحتمال = 3/5.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-08",
      prompt_ar: "كيس فيه 6 كرات حمراء فقط. تُسحب كرة. ما احتمال أن تكون حمراء؟",
      choices_ar: ["0","1/6","1","6"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "ظُنّ أن الاحتمال صفر.",
        1: "قُسم 1 على العدد.",
        3: "كُتب العدد بدل الاحتمال.",
      },
      solve_ar: "المطلوب = الكلي = 6. الاحتمال = 6/6 = 1.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-09",
      prompt_ar: "حجر نرد. ما احتمال ظهور عدد أكبر من 4؟",
      choices_ar: ["1/6","1/3","1/2","2/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّت حالة واحدة (6 فقط).",
        2: "عُدّت 4 و 5 و 6.",
        3: "عُدّت أربعة أعداد.",
      },
      solve_ar: "أكبر من 4: 5 و 6. المطلوب = 2 والكلي = 6. الاحتمال = 2/6 = 1/3.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-10",
      prompt_ar: "كيس: 5 أحمر و 5 أزرق. ما احتمال سحب أزرق؟",
      choices_ar: ["1/5","2/5","1/2","5/5"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم على الأحمر فقط.",
        1: "بُسّط خطأ.",
        3: "كُتب 5/5.",
      },
      solve_ar: "المطلوب = 5 والكلي = 10. الاحتمال = 5/10 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-11",
      prompt_ar: "صندوق 8 بطاقات متمايزة. بطاقتان منهما تحملان علامة نجمة. ما احتمال سحب بطاقة نجمة؟",
      choices_ar: ["2/6","1/8","1/4","2/4"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم على الباقي.",
        1: "أُخذ بطاقة واحدة من 8.",
        3: "بُسّط مع مقام خاطئ.",
      },
      solve_ar: "المطلوب = 2 والكلي = 8. الاحتمال = 2/8 = 1/4.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-12",
      prompt_ar: "كيس فيه 1 حمراء و 9 زرقاء. ما احتمال سحب حمراء؟",
      choices_ar: ["1/9","1/10","9/10","1/2"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على الأزرق فقط.",
        2: "احتمال الأزرق.",
        3: "خُلط بالتساوي.",
      },
      solve_ar: "المطلوب = 1 والكلي = 10. الاحتمال = 1/10.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-13",
      prompt_ar: "حجر نرد. ما احتمال ألا يظهر الرقم 1؟",
      choices_ar: ["1/6","5/6","1/5","4/6"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ احتمال ظهور 1.",
        2: "قُسم على 5.",
        3: "نُسي تبسيط أو عُدّ خطأ.",
      },
      solve_ar: "عدم ظهور 1: 5 حالات من 6. الاحتمال = 5/6.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-14",
      prompt_ar: "كيس: 3 أحمر و 6 أخضر. ما احتمال سحب أخضر؟",
      choices_ar: ["3/6","1/3","2/3","6/3"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم الأخضر على الأحمر.",
        1: "أُخذ احتمال الأحمر المبسّط.",
        3: "كُتب مقلوب النسبة.",
      },
      solve_ar: "المطلوب = 6 والكلي = 9. الاحتمال = 6/9 = 2/3.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-15",
      prompt_ar: "بطاقات من 1 إلى 6. ما احتمال رقم يقبل القسمة على 3؟",
      choices_ar: ["1/6","1/3","1/2","2/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّت حالة واحدة.",
        2: "عُدّت 3 حالات مع 6 خطأ كـ 1/2.",
        3: "عُدّت أربعة.",
      },
      solve_ar: "يقبل القسمة على 3: 3 و 6. المطلوب = 2 والكلي = 6. الاحتمال = 2/6 = 1/3.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-16",
      prompt_ar: "كيس فارغ من الأحمر وفيه 7 زرقاء فقط. ما احتمال سحب حمراء؟",
      choices_ar: ["0","1/7","1","7"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "قُسم 1 على 7.",
        2: "ظُنّ الاحتمال مؤكد.",
        3: "كُتب العدد.",
      },
      solve_ar: "المطلوب = 0 والكلي = 7. الاحتمال = 0.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-17",
      prompt_ar: "كيس: 4 أصفر و 2 أبيض و 2 أسود. ما احتمال سحب أصفر؟",
      choices_ar: ["4/6","1/2","2/8","3/8"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على مجموع غير كامل.",
        2: "أُخذ الأبيض على الكلي.",
        3: "أُخذ قيمة قريبة غير صحيحة.",
      },
      solve_ar: "المطلوب = 4 والكلي = 8. الاحتمال = 4/8 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-18",
      prompt_ar: "حجر نرد. ما احتمال ظهور عدد أولي؟ (الأولي هنا: 2 و 3 و 5)",
      choices_ar: ["1/2","1/3","2/3","1/6"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "عُدّ عددان فقط.",
        2: "عُدّ أربعة أعداد.",
        3: "عُدّت حالة واحدة.",
      },
      solve_ar: "المطلوب 2 و 3 و 5 أي 3 من 6. الاحتمال = 3/6 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "ps-f01",
      prompt_ar: "كيس 2 أحمر و 2 أزرق. ما احتمال سحب أحمر؟",
      choices_ar: ["1/4","1/2","2/2","1/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم 1 على الكلي.",
        2: "كُتب 2/2.",
        3: "نُسي كرة.",
      },
      solve_ar: "المطلوب = 2 والكلي = 4. الاحتمال = 2/4 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f02",
      prompt_ar: "حجر نرد. ما احتمال ظهور 2 أو 4؟",
      choices_ar: ["1/6","1/3","1/2","2/5"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "حالة واحدة.",
        2: "ثلاث حالات.",
        3: "خُلط بعددين من 5.",
      },
      solve_ar: "المطلوب حالتان والكلي 6. الاحتمال = 2/6 = 1/3.",
      trick_ref: "prob-simple",
      difficulty: "easy",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f03",
      prompt_ar: "بطاقات 1 إلى 3. ما احتمال الرقم 2؟",
      choices_ar: ["1/2","1/3","2/3","1"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم خطأ.",
        2: "عُدّ حالتان.",
        3: "ظُنّ مؤكد.",
      },
      solve_ar: "المطلوب = 1 والكلي = 3. الاحتمال = 1/3.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f04",
      prompt_ar: "كيس: 7 كرات منها 3 معلّمة. ما احتمال سحب معلّمة؟",
      choices_ar: ["3/4","3/7","4/7","3/10"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُسم على الباقي.",
        2: "احتمال غير المعلّمة.",
        3: "كُتب مقام خاطئ.",
      },
      solve_ar: "المطلوب = 3 والكلي = 7. الاحتمال = 3/7.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f05",
      prompt_ar: "حجر نرد. ما احتمال عدد أصغر من 3؟",
      choices_ar: ["1/6","1/3","1/2","2/3"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "عُدّت 1 فقط.",
        2: "عُدّت 1 و 2 و 3.",
        3: "عُدّت أربعة.",
      },
      solve_ar: "أصغر من 3: 1 و 2. الاحتمال = 2/6 = 1/3.",
      trick_ref: "prob-simple",
      difficulty: "mid",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f06",
      prompt_ar: "كيس 5 خضراء و 1 حمراء. ما احتمال سحب خضراء؟",
      choices_ar: ["1/5","1/6","5/6","5/1"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "قُسم 1 على الأخضر.",
        1: "احتمال الأحمر.",
        3: "كُتب مقلوب.",
      },
      solve_ar: "المطلوب = 5 والكلي = 6. الاحتمال = 5/6.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
    {
      id: "ps-f07",
      prompt_ar: "بطاقات من 1 إلى 8. ما احتمال رقم زوجي؟",
      choices_ar: ["1/8","1/4","1/2","3/8"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "عُدّت حالة.",
        1: "عُدّت حالتان.",
        3: "عُدّت ثلاث.",
      },
      solve_ar: "الزوجي: 2,4,6,8 أي 4 من 8. الاحتمال = 4/8 = 1/2.",
      trick_ref: "prob-simple",
      difficulty: "hard",
      sub_pattern: "probability",
      ...review,
    },
  ],
};
