import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const rangeSkill: Skill = {
  id: "range",
  title_ar: "المدى",
  domain: "statistics",
  hook_ar: "المدى = أكبر قيمة ناقص أصغر قيمة",
  estimated_minutes: 5,
  icon: "↔",
  visual: { kind: "custom", component: "range-lab" },
  intuition_ar: [
    "المدى يقيس اتساع القائمة: من الأصغر إلى الأكبر.",
    "ابحث عن أكبر قيمة وأصغر قيمة ثم اطرح.",
    "لا تحتاج ترتيباً كاملاً — يكفي طرفا القائمة.",
  ],
  trick_ar: {
    statement: "المدى = الأكبر − الأصغر.",
    steps: [
      "عيّن أكبر قيمة في القائمة",
      "عيّن أصغر قيمة",
      "اطرح: الأكبر ناقص الأصغر",
    ],
    time_target_sec: 14,
    example_ar: "القيم 4 و 9 و 12 و 7 و 15: الأكبر 15 والأصغر 4، فالمدى = 11.",
  },
  timing: {
    excellent_sec: 14,
    good_sec: 24,
    ok_sec: 34,
    slow_sec: 48,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "rg-01",
      prompt_ar: "درجات: 4 و 9 و 12 و 7 و 15. ما المدى؟",
      choices_ar: ["8", "11", "12", "15"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة ليست الأصغر أو الأكبر.",
        2: "أُخذت قيمة من القائمة بدل الفرق.",
        3: "أُخذت أكبر قيمة بدل المدى.",
      },
      solve_ar: "الأكبر = 15 والأصغر = 4. المدى = 15 − 4 = 11.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-02",
      prompt_ar: "مسافات بالكيلو: 2 و 8 و 5 و 14 و 11. ما المدى؟",
      choices_ar: ["9", "12", "14", "40"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة وسطية.",
        2: "أُخذت أكبر قيمة بدل المدى.",
        3: "جُمعت القيم بدل طرح الطرفين.",
      },
      solve_ar: "الأكبر = 14 والأصغر = 2. المدى = 14 − 2 = 12.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-03",
      prompt_ar: "أسعار: 6 و 6 و 18 و 10 و 3. ما المدى؟",
      choices_ar: ["12", "15", "18", "43"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 6 من 18 بدل أصغر قيمة 3.",
        2: "أُخذت أكبر قيمة بدل المدى.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 18 والأصغر = 3. المدى = 18 − 3 = 15.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-04",
      prompt_ar: "أهداف: 0 و 3 و 1 و 5 و 2. ما المدى؟",
      choices_ar: ["3", "5", "11", "0"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة وسطية.",
        2: "جُمعت القيم.",
        3: "أُخذت أصغر قيمة بدل المدى.",
      },
      solve_ar: "الأكبر = 5 والأصغر = 0. المدى = 5 − 0 = 5.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-05",
      prompt_ar: "درجات حرارة: 22 و 28 و 19 و 31 و 25. ما المدى؟",
      choices_ar: ["9", "12", "19", "31"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة ليست الطرفين.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 31 والأصغر = 19. المدى = 31 − 19 = 12.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-06",
      prompt_ar: "أوزان بالكيلو: 50 و 55 و 48 و 62 و 51. ما المدى؟",
      choices_ar: ["12", "14", "50", "62"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة ليست الأصغر.",
        2: "أُخذت قيمة من القائمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 62 والأصغر = 48. المدى = 62 − 48 = 14.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-07",
      prompt_ar: "أوقات بالدقائق: 12 و 18 و 9 و 21 و 15. ما المدى؟",
      choices_ar: ["9", "12", "21", "75"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة بدل المدى.",
        2: "أُخذت أكبر قيمة بدل المدى.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 21 والأصغر = 9. المدى = 21 − 9 = 12.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-08",
      prompt_ar: "سرعات: 60 و 80 و 40 و 100 و 70. ما المدى؟",
      choices_ar: ["40", "60", "100", "350"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة بدل المدى.",
        2: "أُخذت أكبر قيمة بدل المدى.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 100 والأصغر = 40. المدى = 100 − 40 = 60.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-09",
      prompt_ar: "أسعار تذاكر: 45 و 55 و 35 و 65 و 50. ما المدى؟",
      choices_ar: ["20", "30", "35", "65"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة وسطية.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 65 والأصغر = 35. المدى = 65 − 35 = 30.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-10",
      prompt_ar: "قائمة: 8 و 8 و 8 و 8. ما المدى؟",
      choices_ar: ["0", "8", "16", "32"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُخذت القيمة نفسها بدل الفرق.",
        2: "ضُوعفت القيمة بلا معنى للمدى.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 8 والأصغر = 8. المدى = 8 − 8 = 0.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-11",
      prompt_ar: "أطوال بالسنتيمتر: 12 و 28 و 16 و 20 و 24. ما المدى؟",
      choices_ar: ["12", "16", "28", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت أصغر قيمة بدل المدى.",
        2: "أُخذت أكبر قيمة بدل المدى.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 28 والأصغر = 12. المدى = 28 − 12 = 16.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-12",
      prompt_ar: "درجات: 70 و 90 و 60 و 100 و 80. ما المدى؟",
      choices_ar: ["30", "40", "60", "100"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة ليست الأصغر.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 100 والأصغر = 60. المدى = 100 − 60 = 40.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-13",
      prompt_ar: "استهلاك لتر: 24 و 30 و 18 و 36 و 12. ما المدى؟",
      choices_ar: ["18", "24", "36", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت قيمة وسطية.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 36 والأصغر = 12. المدى = 36 − 12 = 24.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-14",
      prompt_ar: "أعداد رسائل: 10 و 40 و 20 و 30 و 5. ما المدى؟",
      choices_ar: ["30", "35", "40", "105"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 10 من 40 ونُسي الأصغر 5.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 40 والأصغر = 5. المدى = 40 − 5 = 35.",
      trick_ref: "range",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-15",
      prompt_ar: "أوزان طرود: 2 و 8 و 2 و 8 و 5. ما المدى؟",
      choices_ar: ["3", "6", "8", "25"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة وسطية.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 8 والأصغر = 2. المدى = 8 − 2 = 6.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-16",
      prompt_ar: "قراءات ضغط: 110 و 130 و 105 و 140 و 120. ما المدى؟",
      choices_ar: ["30", "35", "105", "140"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 110 من 140 ونُسي الأصغر 105.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 140 والأصغر = 105. المدى = 140 − 105 = 35.",
      trick_ref: "range",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-17",
      prompt_ar: "أرقام طلبات مختصرة: 101 و 108 و 95 و 112 و 100. ما المدى؟",
      choices_ar: ["12", "17", "95", "112"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من قيمة ليست الطرفين.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 112 والأصغر = 95. المدى = 112 − 95 = 17.",
      trick_ref: "range",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-18",
      prompt_ar: "درجات: 0 و 50 و 25 و 75 و 100. ما المدى؟",
      choices_ar: ["50", "75", "100", "250"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "أُخذت قيمة وسطية.",
        1: "طُرح 25 من 100.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 100 والأصغر = 0. المدى = 100 − 0 = 100.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "rg-f01",
      prompt_ar: "مسافات: 3 و 9 و 1 و 15 و 7. ما المدى؟",
      choices_ar: ["12", "14", "15", "35"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 3 من 15.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 15 والأصغر = 1. المدى = 15 − 1 = 14.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f02",
      prompt_ar: "أسعار: 99 و 80 و 120 و 75 و 110. ما المدى؟",
      choices_ar: ["40", "45", "75", "120"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 80 من 120.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 120 والأصغر = 75. المدى = 120 − 75 = 45.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f03",
      prompt_ar: "أهداف: 4 و 4 و 4 و 10. ما المدى؟",
      choices_ar: ["0", "6", "10", "22"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "ظُنّ أن تكرار 4 يجعل المدى صفراً.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 10 والأصغر = 4. المدى = 10 − 4 = 6.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f04",
      prompt_ar: "درجات: 88 و 72 و 95 و 60 و 81. ما المدى؟",
      choices_ar: ["28", "35", "60", "95"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 67 من قيمة خاطئة.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 95 والأصغر = 60. المدى = 95 − 60 = 35.",
      trick_ref: "range",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f05",
      prompt_ar: "أوزان: 1 و 2 و 3 و 4 و 5 و 6. ما المدى؟",
      choices_ar: ["4", "5", "6", "21"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 2 من 6.",
        2: "أُخذت أكبر قيمة.",
        3: "جُمعت القيم.",
      },
      solve_ar: "الأكبر = 6 والأصغر = 1. المدى = 6 − 1 = 5.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f06",
      prompt_ar: "قراءات: 7 و 0 و 14 و سالب 3 و 10. ما المدى؟",
      choices_ar: ["14", "17", "10", "28"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 0 من 14 ونُسي سالب 3.",
        2: "أُخذت قيمة وسطية.",
        3: "جُمعت القيم المطلقة تقريباً.",
      },
      solve_ar: "الأكبر = 14 والأصغر = سالب 3. المدى = 14 − (سالب 3) = 17.",
      trick_ref: "range",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "rg-f07",
      prompt_ar: "أطوال: 42 و 28 و 35 و 50 و 31. ما المدى؟",
      choices_ar: ["14", "22", "28", "50"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح 28 من 42.",
        2: "أُخذت أصغر قيمة.",
        3: "أُخذت أكبر قيمة.",
      },
      solve_ar: "الأكبر = 50 والأصغر = 28. المدى = 50 − 28 = 22.",
      trick_ref: "range",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
