import type { Skill } from "@/lib/types";

const review = {
  source: "style-modeled-practice-2024",
  review_status: "approved" as const,
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
};

export const tables: Skill = {
  id: "tables",
  title_ar: "قراءة الجداول",
  domain: "statistics",
  hook_ar: "استخرج المطلوب من الصف والعمود",
  estimated_minutes: 7,
  icon: "▦",
  visual: { kind: "custom", component: "tables-lab" },
  intuition_ar: [
    "الجدول صفوف وأعمدة؛ اقرأ تقاطع الصف مع العمود.",
    "مجموع الصف = جمع أرقام ذلك الصف فقط.",
    "الفرق = اطرح الرقمين المطلوبين بدقة.",
    "لمعرفة أكبر صف: احسب مجموع كل صف ثم قارن."
  ],
  trick_ar: {
    statement: "حدّد الصف والعمود أولاً، ثم اجمع أو اطرح — لا تخلط الصفوف.",
    steps: [
          "اقرأ عنوان الصف وعنوان العمود",
          "استخرج الرقم أو اجمع صفّاً أو عموداً كاملاً",
          "إن طُلب الأكبر: قارن المجاميع لا خلية واحدة عشوائية"
    ],
    time_target_sec: 20,
    example_ar: "صباح: كتب 12 وأقلام 8. مجموع صف الصباح = 12 + 8 = 20.",
  },
  timing: {
    excellent_sec: 20,
    good_sec: 30,
    ok_sec: 40,
    slow_sec: 54,
  },
  review_status: "approved",
  reviewed_by: "founder",
  reviewed_at: "2026-09-13T00:00:00.000Z",
  drill: [
    {
      id: "tbl-01",
      prompt_ar: "مبيعات مكتبة:\n        كتب  أقلام\nصباح   12     8\nمساء    9    15\nما مجموع مبيعات الصباح؟",
      choices_ar: ["17","20","24","21"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع صف المساء بدل الصباح.",
        2: "جُمع عمود الكتب مع رقم إضافي.",
        3: "خُلطت خلية من المساء مع الصباح.",
      },
      solve_ar: "صف الصباح = 12 + 8 = 20.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-02",
      prompt_ar: "حضور فصلين:\n         ذكور  إناث\nأول       18    22\nثاني      20    16\nكم يزيد عدد إناث الصف الأول عن ذكور الصف الأول؟",
      choices_ar: ["2","4","6","40"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح من صف آخر.",
        2: "حُسب فرق صفين كاملين.",
        3: "جُمع العددان بدل طرحهما.",
      },
      solve_ar: "إناث الأول 22 وذكور الأول 18. الفرق = 22 − 18 = 4.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-03",
      prompt_ar: "نتائج فريقين:\n         فوز  خسارة\nفريق أ    8     3\nفريق ب    5     5\nأي صف مجموعه أكبر؟",
      choices_ar: ["فريق أ","فريق ب","متساويان","لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى تعادل فريق ب دون جمع.",
        2: "اُفترض التساوي دون حساب.",
        3: "المجاميع واضحة من الجدول.",
      },
      solve_ar: "مجموع فريق أ = 8 + 3 = 11. مجموع فريق ب = 5 + 5 = 10. الأكبر فريق أ.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-04",
      prompt_ar: "طلبات توصيل:\n         حي أ  حي ب\nالسبت     14     9\nالأحد     11    16\nما مجموع طلبات حي ب في اليومين؟",
      choices_ar: ["23","25","30","20"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع صف السبت بدل عمود حي ب.",
        2: "جُمع الجدول كله تقريباً.",
        3: "أُخذ أحد اليومين فقط.",
      },
      solve_ar: "عمود حي ب = 9 + 16 = 25.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-05",
      prompt_ar: "درجات مسابقة:\n         شفوي  تحريري\nسارة      17      19\nنورة      15      20\nما الفرق بين مجموع درجات سارة ومجموع درجات نورة؟",
      choices_ar: ["1","2","3","0"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "طُرح عمود واحد فقط.",
        2: "خُلطت خلايا بين الطالبتين.",
        3: "اُفترض التساوي دون جمع.",
      },
      solve_ar: "مجموع سارة = 17 + 19 = 36. مجموع نورة = 15 + 20 = 35. الفرق = 36 − 35 = 1.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-06",
      prompt_ar: "مخزون محل:\n         كبير  صغير\nأرفف      6     10\nصناديق    4      8\nما المجموع الكلي لكل القطع في الجدول؟",
      choices_ar: ["24","28","20","18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي صف أو عمود عند الجمع.",
        2: "جُمع صف الأرفف فقط مع جزء.",
        3: "جُمع عمود واحد فقط.",
      },
      solve_ar: "6 + 10 + 4 + 8 = 28.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-07",
      prompt_ar: "زيارات عيادة:\n         صباح  مساء\nالسبت     22    18\nالأحد     19    25\nأي يوم مجموع زياراته أكبر؟",
      choices_ar: ["السبت","الأحد","متساويان","لا يكفي"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "قُورن صباح السبت فقط دون جمع الصف.",
        2: "اُفترض التساوي دون حساب.",
        3: "الجدول كافٍ للمقارنة.",
      },
      solve_ar: "مجموع السبت = 22 + 18 = 40. مجموع الأحد = 19 + 25 = 44. الأكبر الأحد.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-08",
      prompt_ar: "إنتاج ورشة:\n         قطعة أ  قطعة ب\nوردية 1     30       12\nوردية 2     18       24\nكم يزيد إنتاج قطعة أ الكلي عن قطعة ب الكلي؟",
      choices_ar: ["6","12","18","48"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح فرق وردية واحدة فقط.",
        2: "خُلطت خلايا الورديتين.",
        3: "جُمع العمودان بدل طرحهما.",
      },
      solve_ar: "قطعة أ = 30 + 18 = 48. قطعة ب = 12 + 24 = 36. الفرق = 48 − 36 = 12.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-09",
      prompt_ar: "اشتراكات نادٍ:\n         شهري  سنوي\nرجال      40     15\nنساء      35     25\nما مجموع الاشتراكات السنوية؟",
      choices_ar: ["40","50","75","55"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "جُمع عمود خاطئ أو أُضيف 10 زيادة.",
        2: "جُمع صف الرجال كله.",
        3: "خُلط عمود شهري مع سنوي.",
      },
      solve_ar: "عمود السنوي = 15 + 25 = 40.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-10",
      prompt_ar: "مباريات دوري:\n         فاز  تعادل  خسر\nالفريق س  6     2      1\nالفريق ص  4     4      1\nأي فريق لعب مباريات أكثر؟ (اجمع صف كل فريق)",
      choices_ar: ["س","ص","متساويان","لا يمكن"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر إلى عدد الفوز فقط دون جمع الصف.",
        1: "نُظر إلى التعادلات فقط.",
        3: "المجاميع موجودة في الجدول.",
      },
      solve_ar: "س = 6 + 2 + 1 = 9. ص = 4 + 4 + 1 = 9. المجموعان متساويان.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-11",
      prompt_ar: "مبيعات عصير:\n         تفاح  برتقال\nفرع شمال   28      17\nفرع جنوب   21      26\nما مجموع مبيعات فرع الشمال؟",
      choices_ar: ["45","47","49","43"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "أُضيف رقم من فرع الجنوب.",
        2: "جُمع عمود التفاح كله خطأ.",
        3: "نُقص رقم عند الجمع.",
      },
      solve_ar: "28 + 17 = 45.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-12",
      prompt_ar: "عدد الحافلات:\n         صباحي  مسائي\nخط 1      9       6\nخط 2      7       8\nخط 3      8       10\nأي خط مجموع رحلاته الأكبر؟",
      choices_ar: ["خط 1","خط 2","خط 3","خط 1 وخط 2"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "خُلط أكبر خلية صباحية مع مجموع الصف.",
        1: "حُسب مجموع خط 2 فقط.",
        3: "قُورن خطان متقاربان دون خط 3.",
      },
      solve_ar: "خط 1 = 15. خط 2 = 15. خط 3 = 18. الأكبر خط 3.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-13",
      prompt_ar: "درجات اختبار:\n         قصير  نهائي\nأحمد      14     26\nخالد      18     22\nما درجة خالد في الاختبار القصير؟",
      choices_ar: ["14","18","22","26"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذت درجة أحمد القصير.",
        2: "أُخذت درجة خالد النهائية.",
        3: "أُخذت درجة أحمد النهائية.",
      },
      solve_ar: "تقاطع صف خالد مع عمود القصير = 18.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-14",
      prompt_ar: "مبيعات مكتبة:\n        كتب  أقلام\nصباح   12     8\nمساء    9    15\nما الفرق بين مجموع عمود الكتب ومجموع عمود الأقلام؟",
      choices_ar: ["2","3","4","7"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "طُرح خليتان من صف واحد فقط.",
        2: "خُلطت مجاميع الصفوف.",
        3: "جُمع الفرقين خطأ.",
      },
      solve_ar: "كتب = 12 + 9 = 21. أقلام = 8 + 15 = 23. الفرق = 23 − 21 = 2.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-15",
      prompt_ar: "مبيعات:\n         شمال  جنوب\nيناير     40     35\nفبراير    28     32\nأي عمود مجموعه أكبر؟",
      choices_ar: ["شمال","جنوب","متساويان","لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى فبراير فقط.",
        2: "اُفترض التساوي.",
        3: "الجدول كافٍ.",
      },
      solve_ar: "شمال = 40 + 28 = 68. جنوب = 35 + 32 = 67. الأكبر شمال.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-16",
      prompt_ar: "حضور معرض:\n         كبار  أطفال\nالجمعة    20     12\nالسبت     11     14\nالأحد     16     18\nما مجموع حضور يوم السبت؟",
      choices_ar: ["22","25","30","19"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع يوم الجمعة.",
        2: "جُمع يوم الأحد.",
        3: "خُلط عمود الأطفال فقط.",
      },
      solve_ar: "11 + 14 = 25.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-17",
      prompt_ar: "نقاط مسابقة:\n         جولة1  جولة2\nفريق م     10      8\nفريق ن      9      9\nفريق هـ    12      8\nأي فريق مجموعه أكبر؟",
      choices_ar: ["م","ن","هـ","م ون"],
      correct_index: 2,
      trap_explanations_ar: {
        0: "نُظر إلى مجموع م دون مقارنة الباقي.",
        1: "نُظر إلى تعادل ن في الجولتين دون جمع الكل.",
        3: "اُفترض تساوي م ون دون مقارنة هـ.",
      },
      solve_ar: "م = 10 + 8 = 18. ن = 9 + 9 = 18. هـ = 12 + 8 = 20. الأكبر هـ.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-18",
      prompt_ar: "شحنات:\n         صندوق  كيس\nاليوم1      8      6\nاليوم2      5      7\nاليوم3      4      9\nما مجموع شحنات اليوم1 واليوم3 معاً؟",
      choices_ar: ["12","27","39","24"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "أُخذ مجموع اليوم2 فقط.",
        2: "جُمع الجدول كله.",
        3: "نُسي أحد اليومين.",
      },
      solve_ar: "اليوم1 = 14 واليوم3 = 13. المجموع = 14 + 13 = 27. أو الكلي 39 − اليوم2 12 = 27.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
  final_extra: [
    {
      id: "tbl-f01",
      prompt_ar: "مقصف مدرسة:\n         ساندويتش  عصير\nالفسحة1      13       9\nالفسحة2      10      12\nما مجموع مبيعات الفسحة الأولى؟",
      choices_ar: ["20","22","24","18"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الفسحة الثانية.",
        2: "جُمع عمود واحد مع زيادة.",
        3: "نُقص رقم.",
      },
      solve_ar: "13 + 9 = 22.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f02",
      prompt_ar: "أهداف دوري:\n         له  عليه\nالفريق أ   8    3\nالفريق ب   6    4\nكم يزيد «له» عند أ عن «له» عند ب؟",
      choices_ar: ["1","2","3","4"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح عليه بدل له.",
        2: "حُسب فرق الصفين كاملين.",
        3: "طُرح بالعكس.",
      },
      solve_ar: "8 − 6 = 2.",
      trick_ref: "tables",
      difficulty: "easy",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f03",
      prompt_ar: "قراءات عدّاد:\n         صباح  ظهر  مساء\nالسبت     4     5     6\nالأحد     3     7     4\nأي يوم مجموعه أكبر؟",
      choices_ar: ["السبت","الأحد","متساويان","لا يمكن"],
      correct_index: 0,
      trap_explanations_ar: {
        1: "نُظر إلى أعلى خلية ظهر الأحد.",
        2: "اُفترض التساوي.",
        3: "الجدول كافٍ.",
      },
      solve_ar: "السبت = 4+5+6 = 15. الأحد = 3+7+4 = 14. الأكبر السبت.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f04",
      prompt_ar: "تسجيل حضور:\n         حاضر  غائب\nشعبة1     21     4\nشعبة2     19     6\nما مجموع الحاضرين في الشعبتين؟",
      choices_ar: ["38","40","42","35"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "جُمع الغائبين.",
        2: "جُمع الجدول كله.",
        3: "نُسي شعبة.",
      },
      solve_ar: "21 + 19 = 40.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f05",
      prompt_ar: "مبيعات أحذية:\n         رجالي  نسائي\nالمعرض أ    16      14\nالمعرض ب    12      20\nأي معرض مجموعه أكبر؟",
      choices_ar: ["أ","ب","متساويان","لا يمكن"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُظر إلى الرجالي فقط.",
        2: "اُفترض التساوي 30 و 32 دون دقة.",
        3: "الجدول كافٍ.",
      },
      solve_ar: "أ = 16+14 = 30. ب = 12+20 = 32. الأكبر ب.",
      trick_ref: "tables",
      difficulty: "mid",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f06",
      prompt_ar: "تمرينات:\n         جري  قفز\nمجموعة1   10    8\nمجموعة2    7    9\nما الفرق بين مجموعَي المجموعتين؟",
      choices_ar: ["1","2","3","17"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "طُرح عمود واحد فقط.",
        2: "طُرح بالعكس مع خطأ.",
        3: "جُمع بدل طرح.",
      },
      solve_ar: "مجموعة1 = 18. مجموعة2 = 16. الفرق = 2.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
    {
      id: "tbl-f07",
      prompt_ar: "مخزون أدوية:\n         شراب  أقراص\nرف أ       9      11\nرف ب       7      13\nرف ج      10       8\nما المجموع الكلي لكل العبوات؟",
      choices_ar: ["54","58","60","52"],
      correct_index: 1,
      trap_explanations_ar: {
        0: "نُسي رف.",
        2: "زِيد على المجموع.",
        3: "نُقص رف.",
      },
      solve_ar: "9+11+7+13+10+8 = 58.",
      trick_ref: "tables",
      difficulty: "hard",
      sub_pattern: "statistics",
      ...review,
    },
  ],
};
